package hl7.model.V2_5.table;

import hl7.bean.table.Table;

public class Table0440 extends Table{
	private static final String VERSION = "2.5";
	public static Table getInstance(){
		if(table==null) new Table0440();
		return table;
	}

	public static final String AD = "AD";
	public static final String AUI = "AUI";
	public static final String CCD = "CCD";
	public static final String CCP = "CCP";
	public static final String CD = "CD";
	public static final String CE = "CE";
	public static final String CF = "CF";
	public static final String CK = "CK";
	public static final String CM = "CM";
	public static final String CN = "CN";
	public static final String CNE = "CNE";
	public static final String CNS = "CNS";
	public static final String CP = "CP";
	public static final String CQ = "CQ";
	public static final String CSU = "CSU";
	public static final String CWE = "CWE";
	public static final String CX = "CX";
	public static final String DDI = "DDI";
	public static final String DIN = "DIN";
	public static final String DLD = "DLD";
	public static final String DLN = "DLN";
	public static final String DLT = "DLT";
	public static final String DR = "DR";
	public static final String DT = "DT";
	public static final String DTM = "DTM";
	public static final String DTN = "DTN";
	public static final String ED = "ED";
	public static final String EI = "EI";
	public static final String EIP = "EIP";
	public static final String ELD = "ELD";
	public static final String ERL = "ERL";
	public static final String FC = "FC";
	public static final String FN = "FN";
	public static final String FT = "FT";
	public static final String GTS = "GTS";
	public static final String HD = "HD";
	public static final String ICD = "ICD";
	public static final String ID = "ID";
	public static final String IS = "IS";
	public static final String JCC = "JCC";
	public static final String LA1 = "LA1";
	public static final String LA2 = "LA2";
	public static final String MA = "MA";
	public static final String MO = "MO";
	public static final String MOC = "MOC";
	public static final String MOP = "MOP";
	public static final String MSG = "MSG";
	public static final String NA = "NA";
	public static final String NDL = "NDL";
	public static final String NM = "NM";
	public static final String NR = "NR";
	public static final String OCD = "OCD";
	public static final String OSD = "OSD";
	public static final String OSP = "OSP";
	public static final String PIP = "PIP";
	public static final String PL = "PL";
	public static final String PLN = "PLN";
	public static final String PN = "PN";
	public static final String PPN = "PPN";
	public static final String PRL = "PRL";
	public static final String PT = "PT";
	public static final String PTA = "PTA";
	public static final String QIP = "QIP";
	public static final String QSC = "QSC";
	public static final String RCD = "RCD";
	public static final String RFR = "RFR";
	public static final String RI = "RI";
	public static final String RMC = "RMC";
	public static final String RP = "RP";
	public static final String RPT = "RPT";
	public static final String SAD = "SAD";
	public static final String SCV = "SCV";
	public static final String SI = "SI";
	public static final String SN = "SN";
	public static final String SPD = "SPD";
	public static final String SPS = "SPS";
	public static final String SRT = "SRT";
	public static final String ST = "ST";
	public static final String TM = "TM";
	public static final String TN = "TN";
	public static final String TQ = "TQ";
	public static final String TS = "TS";
	public static final String TX = "TX";
	public static final String UVC = "UVC";
	public static final String VH = "VH";
	public static final String VID = "VID";
	public static final String VR = "VR";
	public static final String WVI = "WVI";
	public static final String WVS = "WVS";
	public static final String XAD = "XAD";
	public static final String XCN = "XCN";
	public static final String XON = "XON";
	public static final String XPN = "XPN";
	public static final String XTN = "XTN";

	private Table0440(){
		setTableName("Data types");
		setOID("2.16.840.1.113883.12.440");

		putMap("AD", "Address");
		putMap("AUI", "Authorization information");
		putMap("CCD", "Charge code and date");
		putMap("CCP", "Channel calibration parameters");
		putMap("CD", "Channel definition");
		putMap("CE", "Coded element");
		putMap("CF", "Coded element with formatted values");
		putMap("CK", "Composite ID with check digit");
		putMap("CM", "Composite");
		putMap("CN", "Composite ID number and name");
		putMap("CNE", "Coded with no exceptions");
		putMap("CNS", "Composite ID number and name simplified");
		putMap("CP", "Composite price");
		putMap("CQ", "Composite quantity with units");
		putMap("CSU", "Channel sensitivity");
		putMap("CWE", "Coded with exceptions");
		putMap("CX", "Extended composite ID with check digit");
		putMap("DDI", "Daily deductible information");
		putMap("DIN", "Date and institution name");
		putMap("DLD", "Discharge to location and date");
		putMap("DLN", "Driver's license number");
		putMap("DLT", "Delta");
		putMap("DR", "Date/time range");
		putMap("DT", "Date");
		putMap("DTM", "Date/time");
		putMap("DTN", "Day type and number");
		putMap("ED", "Encapsulated data");
		putMap("EI", "Entity identifier");
		putMap("EIP", "Entity identifier pair");
		putMap("ELD", "Error location and description");
		putMap("ERL", "Error location");
		putMap("FC", "Financial class");
		putMap("FN", "Family name");
		putMap("FT", "Formatted text");
		putMap("GTS", "General timing specification");
		putMap("HD", "Hierarchic designator");
		putMap("ICD", "Insurance certification definition");
		putMap("ID", "Coded values for HL7 tables");
		putMap("IS", "Coded value for user-defined tables");
		putMap("JCC", "Job code/class");
		putMap("LA1", "Location with address variation 1");
		putMap("LA2", "Location with address variation 2");
		putMap("MA", "Multiplexed array");
		putMap("MO", "Money");
		putMap("MOC", "Money and charge code");
		putMap("MOP", "Money or percentage");
		putMap("MSG", "Message type");
		putMap("NA", "Numeric array");
		putMap("NDL", "Name with location and date");
		putMap("NM", "Numeric");
		putMap("NR", "Numeric range");
		putMap("OCD", "Occurrence code and date");
		putMap("OSD", "Order sequence definition");
		putMap("OSP", "Occurrence span code and date");
		putMap("PIP", "Practitioner institutional privileges");
		putMap("PL", "Person location");
		putMap("PLN", "Practitioner license or other ID number");
		putMap("PN", "Person name");
		putMap("PPN", "Performing person time stamp");
		putMap("PRL", "Parent result link");
		putMap("PT", "Processing type");
		putMap("PTA", "Policy type and amount");
		putMap("QIP", "Query input parameter list");
		putMap("QSC", "Query selection criteria");
		putMap("RCD", "Row column definition");
		putMap("RFR", "Reference range");
		putMap("RI", "Repeat interval");
		putMap("RMC", "Room coverage");
		putMap("RP", "Reference pointer");
		putMap("RPT", "Repeat pattern");
		putMap("SAD", "Street Address");
		putMap("SCV", "Scheduling class value pair");
		putMap("SI", "Sequence ID");
		putMap("SN", "Structured numeric");
		putMap("SPD", "Specialty description");
		putMap("SPS", "Specimen source");
		putMap("SRT", "Sort order");
		putMap("ST", "String");
		putMap("TM", "Time");
		putMap("TN", "Telephone number");
		putMap("TQ", "Timing/quantity");
		putMap("TS", "Time stamp");
		putMap("TX", "Text data");
		putMap("UVC", "UB value code and amount");
		putMap("VH", "Visiting hours");
		putMap("VID", "Version identifier");
		putMap("VR", "Value range");
		putMap("WVI", "Channel Identifier");
		putMap("WVS", "Waveform source");
		putMap("XAD", "Extended address");
		putMap("XCN", "Extended composite ID number and name");
		putMap("XON", "Extended composite name and ID number for organizations");
		putMap("XPN", "Extended person name");
		putMap("XTN", "Extended telecommunications number");

	}

}
