package hl7.model.V2_5.table;

import hl7.bean.table.Table;

public class Table0487 extends Table{
	private static final String VERSION = "2.5";
	public static Table getInstance(){
		if(table==null) new Table0487();
		return table;
	}

	public static final String ABS = "ABS";
	public static final String ACNE = "ACNE";
	public static final String ACNFLD = "ACNFLD";
	public static final String AIRS = "AIRS";
	public static final String ALL = "ALL";
	public static final String AMP = "AMP";
	public static final String ANGI = "ANGI";
	public static final String ARTC = "ARTC";
	public static final String ASERU = "ASERU";
	public static final String ASP = "ASP";
	public static final String ATTE = "ATTE";
	public static final String AUTOC = "AUTOC";
	public static final String AUTP = "AUTP";
	public static final String BBL = "BBL";
	public static final String BCYST = "BCYST";
	public static final String BITE = "BITE";
	public static final String BLEB = "BLEB";
	public static final String BLIST = "BLIST";
	public static final String BOIL = "BOIL";
	public static final String BONE = "BONE";
	public static final String BOWL = "BOWL";
	public static final String BPU = "BPU";
	public static final String BRN = "BRN";
	public static final String BRSH = "BRSH";
	public static final String BRTH = "BRTH";
	public static final String BRUS = "BRUS";
	public static final String BUB = "BUB";
	public static final String BULLA = "BULLA";
	public static final String BX = "BX";
	public static final String CALC = "CALC";
	public static final String CARBU = "CARBU";
	public static final String CAT = "CAT";
	public static final String CBITE = "CBITE";
	public static final String CLIPP = "CLIPP";
	public static final String CNJT = "CNJT";
	public static final String COL = "COL";
	public static final String CONE = "CONE";
	public static final String CSCR = "CSCR";
	public static final String CSERU = "CSERU";
	public static final String CSITE = "CSITE";
	public static final String CSMY = "CSMY";
	public static final String CST = "CST";
	public static final String CSVR = "CSVR";
	public static final String CTP = "CTP";
	public static final String CVPS = "CVPS";
	public static final String CVPT = "CVPT";
	public static final String CYN = "CYN";
	public static final String CYST = "CYST";
	public static final String DBITE = "DBITE";
	public static final String DCS = "DCS";
	public static final String DEC = "DEC";
	public static final String DEION = "DEION";
	public static final String DIA = "DIA";
	public static final String DISCHG = "DISCHG";
	public static final String DIV = "DIV";
	public static final String DRN = "DRN";
	public static final String DRNG = "DRNG";
	public static final String DRNGP = "DRNGP";
	public static final String EARW = "EARW";
	public static final String EBRUSH = "EBRUSH";
	public static final String EEYE = "EEYE";
	public static final String EFF = "EFF";
	public static final String EFFUS = "EFFUS";
	public static final String EFOD = "EFOD";
	public static final String EISO = "EISO";
	public static final String ELT = "ELT";
	public static final String ENVIR = "ENVIR";
	public static final String EOTH = "EOTH";
	public static final String ESOI = "ESOI";
	public static final String ESOS = "ESOS";
	public static final String ETA = "ETA";
	public static final String ETTP = "ETTP";
	public static final String ETTUB = "ETTUB";
	public static final String EWHI = "EWHI";
	public static final String EXG = "EXG";
	public static final String EXS = "EXS";
	public static final String EXUDTE = "EXUDTE";
	public static final String FAW = "FAW";
	public static final String FBLOOD = "FBLOOD";
	public static final String FGA = "FGA";
	public static final String FIST = "FIST";
	public static final String FLD = "FLD";
	public static final String FLT = "FLT";
	public static final String FLU = "FLU";
	public static final String FLUID = "FLUID";
	public static final String FOLEY = "FOLEY";
	public static final String FRS = "FRS";
	public static final String FSCLP = "FSCLP";
	public static final String FUR = "FUR";
	public static final String GAS = "GAS";
	public static final String GASA = "GASA";
	public static final String GASAN = "GASAN";
	public static final String GASBR = "GASBR";
	public static final String GASD = "GASD";
	public static final String GAST = "GAST";
	public static final String GENV = "GENV";
	public static final String GRAFT = "GRAFT";
	public static final String GRANU = "GRANU";
	public static final String GROSH = "GROSH";
	public static final String GSOL = "GSOL";
	public static final String GSPEC = "GSPEC";
	public static final String GT = "GT";
	public static final String GTUBE = "GTUBE";
	public static final String HBITE = "HBITE";
	public static final String HBLUD = "HBLUD";
	public static final String HEMAQ = "HEMAQ";
	public static final String HEMO = "HEMO";
	public static final String HERNI = "HERNI";
	public static final String HEV = "HEV";
	public static final String HIC = "HIC";
	public static final String HYDC = "HYDC";
	public static final String IBITE = "IBITE";
	public static final String ICYST = "ICYST";
	public static final String IDC = "IDC";
	public static final String IHG = "IHG";
	public static final String ILEO = "ILEO";
	public static final String ILLEG = "ILLEG";
	public static final String IMP = "IMP";
	public static final String INCI = "INCI";
	public static final String INFIL = "INFIL";
	public static final String INS = "INS";
	public static final String INTRD = "INTRD";
	public static final String IT = "IT";
	public static final String IUD = "IUD";
	public static final String IVCAT = "IVCAT";
	public static final String IVFLD = "IVFLD";
	public static final String IVTIP = "IVTIP";
	public static final String JEJU = "JEJU";
	public static final String JNTFLD = "JNTFLD";
	public static final String JP = "JP";
	public static final String KELOI = "KELOI";
	public static final String KIDFLD = "KIDFLD";
	public static final String LAVG = "LAVG";
	public static final String LAVGG = "LAVGG";
	public static final String LAVGP = "LAVGP";
	public static final String LAVPG = "LAVPG";
	public static final String LENS1 = "LENS1";
	public static final String LENS2 = "LENS2";
	public static final String LESN = "LESN";
	public static final String LIQ = "LIQ";
	public static final String LIQO = "LIQO";
	public static final String LSAC = "LSAC";
	public static final String MAHUR = "MAHUR";
	public static final String MASS = "MASS";
	public static final String MBLD = "MBLD";
	public static final String MUCOS = "MUCOS";
	public static final String MUCUS = "MUCUS";
	public static final String NASDR = "NASDR";
	public static final String NEDL = "NEDL";
	public static final String NEPH = "NEPH";
	public static final String NGASP = "NGASP";
	public static final String NGAST = "NGAST";
	public static final String NGS = "NGS";
	public static final String NODUL = "NODUL";
	public static final String NSECR = "NSECR";
	public static final String ORH = "ORH";
	public static final String ORL = "ORL";
	public static final String OTH = "OTH";
	public static final String PACEM = "PACEM";
	public static final String PCFL = "PCFL";
	public static final String PDSIT = "PDSIT";
	public static final String PDTS = "PDTS";
	public static final String PELVA = "PELVA";
	public static final String PENIL = "PENIL";
	public static final String PERIA = "PERIA";
	public static final String PILOC = "PILOC";
	public static final String PINS = "PINS";
	public static final String PIS = "PIS";
	public static final String PLAN = "PLAN";
	public static final String PLAS = "PLAS";
	public static final String PLB = "PLB";
	public static final String PLEVS = "PLEVS";
	public static final String PND = "PND";
	public static final String POL = "POL";
	public static final String POPGS = "POPGS";
	public static final String POPLG = "POPLG";
	public static final String POPLV = "POPLV";
	public static final String PORTA = "PORTA";
	public static final String PPP = "PPP";
	public static final String PROST = "PROST";
	public static final String PRP = "PRP";
	public static final String PSC = "PSC";
	public static final String PUNCT = "PUNCT";
	public static final String PUSFR = "PUSFR";
	public static final String PUST = "PUST";
	public static final String QC3 = "QC3";
	public static final String RANDU = "RANDU";
	public static final String RBITE = "RBITE";
	public static final String RECT = "RECT";
	public static final String RECTA = "RECTA";
	public static final String RENALC = "RENALC";
	public static final String RENC = "RENC";
	public static final String RES = "RES";
	public static final String SAL = "SAL";
	public static final String SCAR = "SCAR";
	public static final String SCLV = "SCLV";
	public static final String SCROA = "SCROA";
	public static final String SECRE = "SECRE";
	public static final String SER = "SER";
	public static final String SHU = "SHU";
	public static final String SHUNF = "SHUNF";
	public static final String SHUNT = "SHUNT";
	public static final String SITE = "SITE";
	public static final String SKBP = "SKBP";
	public static final String SKN = "SKN";
	public static final String SMM = "SMM";
	public static final String SNV = "SNV";
	public static final String SPRM = "SPRM";
	public static final String SPRP = "SPRP";
	public static final String SPRPB = "SPRPB";
	public static final String SPS = "SPS";
	public static final String SPT = "SPT";
	public static final String SPTC = "SPTC";
	public static final String SPTT = "SPTT";
	public static final String SPUT1 = "SPUT1";
	public static final String SPUTIN = "SPUTIN";
	public static final String SPUTSP = "SPUTSP";
	public static final String STER = "STER";
	public static final String STL = "STL";
	public static final String STONE = "STONE";
	public static final String SUBMA = "SUBMA";
	public static final String SUBMX = "SUBMX";
	public static final String SUMP = "SUMP";
	public static final String SUP = "SUP";
	public static final String SUTUR = "SUTUR";
	public static final String SWGZ = "SWGZ";
	public static final String TASP = "TASP";
	public static final String TISS = "TISS";
	public static final String TISU = "TISU";
	public static final String TLC = "TLC";
	public static final String TRAC = "TRAC";
	public static final String TRANS = "TRANS";
	public static final String TSERU = "TSERU";
	public static final String TSTES = "TSTES";
	public static final String TTRA = "TTRA";
	public static final String TUBES = "TUBES";
	public static final String TUMOR = "TUMOR";
	public static final String TZANC = "TZANC";
	public static final String UDENT = "UDENT";
	public static final String UR = "UR";
	public static final String URC = "URC";
	public static final String URINB = "URINB";
	public static final String URINC = "URINC";
	public static final String URINM = "URINM";
	public static final String URINN = "URINN";
	public static final String URINP = "URINP";
	public static final String URT = "URT";
	public static final String USCOP = "USCOP";
	public static final String USPEC = "USPEC";
	public static final String VASTIP = "VASTIP";
	public static final String VENT = "VENT";
	public static final String VITF = "VITF";
	public static final String WASH = "WASH";
	public static final String WASI = "WASI";
	public static final String WAT = "WAT";
	public static final String WB = "WB";
	public static final String WEN = "WEN";
	public static final String WICK = "WICK";
	public static final String WND = "WND";
	public static final String WNDA = "WNDA";
	public static final String WNDD = "WNDD";
	public static final String WNDE = "WNDE";
	public static final String WORM = "WORM";
	public static final String WRT = "WRT";
	public static final String WWA = "WWA";
	public static final String WWO = "WWO";
	public static final String WWT = "WWT";

	private Table0487(){
		setTableName("Specimen Type");
		setOID("2.16.840.1.113883.12.487");

		putMap("ABS", "Abscess");
		putMap("ACNE", "Tissue, Acne");
		putMap("ACNFLD", "Fluid, Acne");
		putMap("AIRS", "Air Sample");
		putMap("ALL", "Allograft");
		putMap("AMP", "Amputation");
		putMap("ANGI", "Catheter Tip, Angio");
		putMap("ARTC", "Catheter Tip, Arterial");
		putMap("ASERU", "Serum, Acute");
		putMap("ASP", "Aspirate");
		putMap("ATTE", "Environmental, Autoclave Ampule");
		putMap("AUTOC", "Environment, Attest");
		putMap("AUTP", "Autopsy");
		putMap("BBL", "Blood Bag");
		putMap("BCYST", "Cyst, Baker's");
		putMap("BITE", "Bite");
		putMap("BLEB", "Bleb");
		putMap("BLIST", "Blister");
		putMap("BOIL", "Boil");
		putMap("BONE", "Bone");
		putMap("BOWL", "Bowel contents");
		putMap("BPU", "Blood product unit");
		putMap("BRN", "Burn");
		putMap("BRSH", "Brush");
		putMap("BRTH", "Brwath (use EXHLD)");
		putMap("BRUS", "Brushing");
		putMap("BUB", "Bubo");
		putMap("BULLA", "Bulla/Bullae");
		putMap("BX", "Biopsy");
		putMap("CALC", "Caculus (=Stone)");
		putMap("CARBU", "Carbuncle");
		putMap("CAT", "Catheter");
		putMap("CBITE", "Bite, Cat");
		putMap("CLIPP", "Clippings");
		putMap("CNJT", "Conjunctiva");
		putMap("COL", "Colostrum");
		putMap("CONE", "Biospy, Cone");
		putMap("CSCR", "Scratch, Cat");
		putMap("CSERU", "Serum, Convalescent");
		putMap("CSITE", "Catheter Insertion Site");
		putMap("CSMY", "Fluid,  Cystostomy Tube");
		putMap("CST", "Fluid, Cyst");
		putMap("CSVR", "Blood, Cell Saver");
		putMap("CTP", "Catheter tip");
		putMap("CVPS", "Site, CVP");
		putMap("CVPT", "Catheter Tip, CVP");
		putMap("CYN", "Nodule, Cystic");
		putMap("CYST", "Cyst");
		putMap("DBITE", "Bite, Dog");
		putMap("DCS", "Sputum, Deep Cough");
		putMap("DEC", "Ulcer, Decubitus");
		putMap("DEION", "Environmental, Water  (Deionized)");
		putMap("DIA", "Dialysate");
		putMap("DISCHG", "Discharge");
		putMap("DIV", "Diverticulum");
		putMap("DRN", "Drain");
		putMap("DRNG", "Drainage, Tube");
		putMap("DRNGP", "Drainage, Penrose");
		putMap("EARW", "Ear wax (cerumen)");
		putMap("EBRUSH", "Brush, Esophageal");
		putMap("EEYE", "Environmental, Eye Wash");
		putMap("EFF", "Environmental, Effluent");
		putMap("EFFUS", "Effusion");
		putMap("EFOD", "Environmental, Food");
		putMap("EISO", "Environmental, Isolette");
		putMap("ELT", "Electrode");
		putMap("ENVIR", "Environmental, Unidentified Substance");
		putMap("EOTH", "Environmental, Other Substance");
		putMap("ESOI", "Environmental, Soil");
		putMap("ESOS", "Environmental, Solution (Sterile)");
		putMap("ETA", "Aspirate,  Endotrach");
		putMap("ETTP", "Catheter Tip, Endotracheal");
		putMap("ETTUB", "Tube, Endotracheal");
		putMap("EWHI", "Environmental, Whirlpool");
		putMap("EXG", "Gas, exhaled (=breath)");
		putMap("EXS", "Shunt, External");
		putMap("EXUDTE", "Exudate");
		putMap("FAW", "Environmental, Water  (Well)");
		putMap("FBLOOD", "Blood, Fetal");
		putMap("FGA", "Fluid,  Abdomen");
		putMap("FIST", "Fistula");
		putMap("FLD", "Fluid, Other");
		putMap("FLT", "Filter");
		putMap("FLU", "Fluid, Body unsp");
		putMap("FLUID", "Fluid");
		putMap("FOLEY", "Catheter Tip, Foley");
		putMap("FRS", "Fluid, Respiratory");
		putMap("FSCLP", "Scalp, Fetal");
		putMap("FUR", "Furuncle");
		putMap("GAS", "Gas");
		putMap("GASA", "Aspirate, Gastric");
		putMap("GASAN", "Antrum, Gastric");
		putMap("GASBR", "Brushing, Gastric");
		putMap("GASD", "Drainage, Gastric");
		putMap("GAST", "Fluid/contents, Gastric");
		putMap("GENV", "Genital vaginal");
		putMap("GRAFT", "Graft");
		putMap("GRANU", "Granuloma");
		putMap("GROSH", "Catheter, Groshong");
		putMap("GSOL", "Solution, Gastrostomy");
		putMap("GSPEC", "Biopsy, Gastric");
		putMap("GT", "Tube, Gastric");
		putMap("GTUBE", "Drainage Tube, Drainage (Gastrostomy)");
		putMap("HBITE", "Bite, Human");
		putMap("HBLUD", "Blood, Autopsy");
		putMap("HEMAQ", "Catheter Tip, Hemaquit");
		putMap("HEMO", "Catheter Tip, Hemovac");
		putMap("HERNI", "Tissue, Herniated");
		putMap("HEV", "Drain, Hemovac");
		putMap("HIC", "Catheter, Hickman");
		putMap("HYDC", "Fluid, Hydrocele");
		putMap("IBITE", "Bite, Insect");
		putMap("ICYST", "Cyst, Inclusion");
		putMap("IDC", "Catheter Tip, Indwelling");
		putMap("IHG", "Gas, inhaled");
		putMap("ILEO", "Drainage, Ileostomy");
		putMap("ILLEG", "Source of Specimen Is Illegible");
		putMap("IMP", "Implant");
		putMap("INCI", "Site, Incision/Surgical");
		putMap("INFIL", "Infiltrate");
		putMap("INS", "Insect");
		putMap("INTRD", "Catheter Tip, Introducer");
		putMap("IT", "Intubation tube");
		putMap("IUD", "Intrauterine Device");
		putMap("IVCAT", "Catheter Tip, IV");
		putMap("IVFLD", "Fluid, IV");
		putMap("IVTIP", "Tubing Tip, IV");
		putMap("JEJU", "Drainage, Jejunal");
		putMap("JNTFLD", "Fluid, Joint");
		putMap("JP", "Drainage, Jackson Pratt");
		putMap("KELOI", "Lavage");
		putMap("KIDFLD", "Fluid, Kidney");
		putMap("LAVG", "Lavage, Bronhial");
		putMap("LAVGG", "Lavage, Gastric");
		putMap("LAVGP", "Lavage, Peritoneal");
		putMap("LAVPG", "Lavage, Pre-Bronch");
		putMap("LENS1", "Contact Lens");
		putMap("LENS2", "Contact Lens Case");
		putMap("LESN", "Lesion");
		putMap("LIQ", "Liquid, Unspecified");
		putMap("LIQO", "Liquid, Other");
		putMap("LSAC", "Fluid, Lumbar Sac");
		putMap("MAHUR", "Catheter Tip, Makurkour");
		putMap("MASS", "Mass");
		putMap("MBLD", "Blood, Menstrual");
		putMap("MUCOS", "Mucosa");
		putMap("MUCUS", "Mucus");
		putMap("NASDR", "Drainage, Nasal");
		putMap("NEDL", "Needle");
		putMap("NEPH", "Site, Nephrostomy");
		putMap("NGASP", "Aspirate, Nasogastric");
		putMap("NGAST", "Drainage, Nasogastric");
		putMap("NGS", "Site, Naso/Gastric");
		putMap("NODUL", "Nodule(s)");
		putMap("NSECR", "Secretion, Nasal");
		putMap("ORH", "Other");
		putMap("ORL", "Lesion, Oral");
		putMap("OTH", "Source, Other");
		putMap("PACEM", "Pacemaker");
		putMap("PCFL", "Fluid, Pericardial");
		putMap("PDSIT", "Site, Peritoneal Dialysis");
		putMap("PDTS", "Site, Peritoneal Dialysis Tunnel");
		putMap("PELVA", "Abscess, Pelvic");
		putMap("PENIL", "Lesion, Penile");
		putMap("PERIA", "Abscess, Perianal");
		putMap("PILOC", "Cyst, Pilonidal");
		putMap("PINS", "Site, Pin");
		putMap("PIS", "Site, Pacemaker Insetion");
		putMap("PLAN", "Plant Material");
		putMap("PLAS", "Plasma");
		putMap("PLB", "Plasma bag");
		putMap("PLEVS", "Serum, Peak Level");
		putMap("PND", "Drainage, Penile");
		putMap("POL", "Polyps");
		putMap("POPGS", "Graft Site, Popliteal");
		putMap("POPLG", "Graft, Popliteal");
		putMap("POPLV", "Site, Popliteal Vein");
		putMap("PORTA", "Catheter, Porta");
		putMap("PPP", "Plasma, Platelet poor");
		putMap("PROST", "Prosthetic Device");
		putMap("PRP", "Plasma, Platelet rich");
		putMap("PSC", "Pseudocyst");
		putMap("PUNCT", "Wound, Puncture");
		putMap("PUSFR", "Pustule");
		putMap("PUST", "Pus");
		putMap("QC3", "Quality Control");
		putMap("RANDU", "Urine, Random");
		putMap("RBITE", "Bite, Reptile");
		putMap("RECT", "Drainage, Rectal");
		putMap("RECTA", "Abscess, Rectal");
		putMap("RENALC", "Cyst, Renal");
		putMap("RENC", "Fluid, Renal Cyst");
		putMap("RES", "Respiratory");
		putMap("SAL", "Saliva");
		putMap("SCAR", "Tissue, Keloid (Scar)");
		putMap("SCLV", "Catheter Tip, Subclavian");
		putMap("SCROA", "Abscess, Scrotal");
		putMap("SECRE", "Secretion(s)");
		putMap("SER", "Serum");
		putMap("SHU", "Site, Shunt");
		putMap("SHUNF", "Fluid, Shunt");
		putMap("SHUNT", "Shunt");
		putMap("SITE", "Site");
		putMap("SKBP", "Biopsy, Skin");
		putMap("SKN", "Skin");
		putMap("SMM", "Mass, Sub-Mandibular");
		putMap("SNV", "Fluid, synovial (Joint fluid)");
		putMap("SPRM", "Spermatozoa");
		putMap("SPRP", "Catheter Tip, Suprapubic");
		putMap("SPRPB", "Cathether Tip, Suprapubic");
		putMap("SPS", "Environmental, Spore Strip");
		putMap("SPT", "Sputum");
		putMap("SPTC", "Sputum - coughed");
		putMap("SPTT", "Sputum - tracheal aspirate");
		putMap("SPUT1", "Sputum, Simulated");
		putMap("SPUTIN", "Sputum, Inducted");
		putMap("SPUTSP", "Sputum, Spontaneous");
		putMap("STER", "Environmental, Sterrad");
		putMap("STL", "Stool - Fecal");
		putMap("STONE", "Stone, Kidney");
		putMap("SUBMA", "Abscess, Submandibular");
		putMap("SUBMX", "Abscess, Submaxillary");
		putMap("SUMP", "Drainage, Sump");
		putMap("SUP", "Suprapubic Tap");
		putMap("SUTUR", "Suture");
		putMap("SWGZ", "Catheter Tip, Swan Gantz");
		putMap("TASP", "Aspirate, Tracheal");
		putMap("TISS", "Tissue");
		putMap("TISU", "Tissue ulcer");
		putMap("TLC", "Cathether Tip, Triple Lumen");
		putMap("TRAC", "Site, Tracheostomy");
		putMap("TRANS", "Transudate");
		putMap("TSERU", "Serum, Trough");
		putMap("TSTES", "Abscess, Testicular");
		putMap("TTRA", "Aspirate, Transtracheal");
		putMap("TUBES", "Tubes");
		putMap("TUMOR", "Tumor");
		putMap("TZANC", "Smear, Tzanck");
		putMap("UDENT", "Source, Unidentified");
		putMap("UR", "Urine");
		putMap("URC", "Urine clean catch");
		putMap("URINB", "Urine, Bladder Washings");
		putMap("URINC", "Urine, Catheterized");
		putMap("URINM", "Urine, Midstream");
		putMap("URINN", "Urine, Nephrostomy");
		putMap("URINP", "Urine, Pedibag");
		putMap("URT", "Urine catheter");
		putMap("USCOP", "Urine, Cystoscopy");
		putMap("USPEC", "Source, Unspecified");
		putMap("VASTIP", "Catheter Tip, Vas");
		putMap("VENT", "Catheter Tip, Ventricular");
		putMap("VITF", "Vitreous Fluid");
		putMap("WASH", "Wash");
		putMap("WASI", "Washing, e.g. bronchial washing");
		putMap("WAT", "Water");
		putMap("WB", "Blood, Whole");
		putMap("WEN", "Wen");
		putMap("WICK", "Wick");
		putMap("WND", "Wound");
		putMap("WNDA", "Wound abscess");
		putMap("WNDD", "Wound drainage");
		putMap("WNDE", "Wound exudate");
		putMap("WORM", "Worm");
		putMap("WRT", "Wart");
		putMap("WWA", "Environmental, Water");
		putMap("WWO", "Environmental, Water (Ocean)");
		putMap("WWT", "Environmental, Water  (Tap)");

	}

}
