package hl7.model.V2_5.table;

import hl7.bean.table.Table;

public class Table0550 extends Table{
	private static final String VERSION = "2.5";
	public static Table getInstance(){
		if(table==null) new Table0550();
		return table;
	}

	public static final String ACET = "ACET";
	public static final String ACHIL = "ACHIL";
	public static final String ADB = "ADB";
	public static final String ADE = "ADE";
	public static final String ADR = "ADR";
	public static final String AMN = "AMN";
	public static final String AMS = "AMS";
	public static final String ANAL = "ANAL";
	public static final String ANKL = "ANKL";
	public static final String ANTEC = "ANTEC";
	public static final String ANTECF = "ANTECF";
	public static final String ANTR = "ANTR";
	public static final String ANUS = "ANUS";
	public static final String AORTA = "AORTA";
	public static final String APDX = "APDX";
	public static final String AR = "AR";
	public static final String AREO = "AREO";
	public static final String ARM = "ARM";
	public static final String ARTE = "ARTE";
	public static final String ASCIT = "ASCIT";
	public static final String ASCT = "ASCT";
	public static final String ATR = "ATR";
	public static final String AURI = "AURI";
	public static final String AV = "AV";
	public static final String AXI = "AXI";
	public static final String BACK = "BACK";
	public static final String BARTD = "BARTD";
	public static final String BARTG = "BARTG";
	public static final String BCYS = "BCYS";
	public static final String BDY = "BDY";
	public static final String BID = "BID";
	public static final String BIFL = "BIFL";
	public static final String BLAD = "BLAD";
	public static final String BLD = "BLD";
	public static final String BLDA = "BLDA";
	public static final String BLDC = "BLDC";
	public static final String BLDV = "BLDV";
	public static final String BLOOD = "BLOOD";
	public static final String BMAR = "BMAR";
	public static final String BON = "BON";
	public static final String BOWEL = "BOWEL";
	public static final String BOWLA = "BOWLA";
	public static final String BOWSM = "BOWSM";
	public static final String BPH = "BPH";
	public static final String BRA = "BRA";
	public static final String BRAIN = "BRAIN";
	public static final String BRO = "BRO";
	public static final String BROCH = "BROCH";
	public static final String BRONC = "BRONC";
	public static final String BROW = "BROW";
	public static final String BRST = "BRST";
	public static final String BRSTFL = "BRSTFL";
	public static final String BRTGF = "BRTGF";
	public static final String BRV = "BRV";
	public static final String BUCCA = "BUCCA";
	public static final String BURSA = "BURSA";
	public static final String BURSF = "BURSF";
	public static final String BUTT = "BUTT";
	public static final String CALF = "CALF";
	public static final String CANAL = "CANAL";
	public static final String CANLI = "CANLI";
	public static final String CANTH = "CANTH";
	public static final String CARO = "CARO";
	public static final String CARP = "CARP";
	public static final String CAVIT = "CAVIT";
	public static final String CBLD = "CBLD";
	public static final String CDM = "CDM";
	public static final String CDUCT = "CDUCT";
	public static final String CECUM = "CECUM";
	public static final String CERVUT = "CERVUT";
	public static final String CHE = "CHE";
	public static final String CHEEK = "CHEEK";
	public static final String CHES = "CHES";
	public static final String CHEST = "CHEST?";
	public static final String CHIN = "CHIN";
	public static final String CIRCU = "CIRCU";
	public static final String CLAVI = "CLAVI";
	public static final String CLIT = "CLIT";
	public static final String CLITO = "CLITO";
	public static final String CNL = "CNL";
	public static final String COCCG = "COCCG";
	public static final String COCCY = "COCCY";
	public static final String COLON = "COLON";
	public static final String COLOS = "COLOS";
	public static final String CONJ = "CONJ";
	public static final String COR = "COR";
	public static final String CORAL = "CORAL";
	public static final String CORD = "CORD";
	public static final String CORN = "CORN";
	public static final String COS = "COS";
	public static final String CRANE = "CRANE";
	public static final String CRANF = "CRANF";
	public static final String CRANO = "CRANO";
	public static final String CRANP = "CRANP";
	public static final String CRANS = "CRANS";
	public static final String CRANT = "CRANT";
	public static final String CSF = "CSF";
	public static final String CUBIT = "CUBIT";
	public static final String CUFF = "CUFF";
	public static final String CULD = "CULD";
	public static final String CULDO = "CULDO";
	public static final String CVX = "CVX";
	public static final String DELT = "DELT";
	public static final String DEN = "DEN";
	public static final String DENTA = "DENTA";
	public static final String DIAF = "DIAF";
	public static final String DIGIT = "DIGIT";
	public static final String DISC = "DISC";
	public static final String DORS = "DORS";
	public static final String DPH = "DPH";
	public static final String DUFL = "DUFL";
	public static final String DUODE = "DUODE";
	public static final String DUR = "DUR";
	public static final String EAR = "EAR";
	public static final String EARBI = "EARBI";
	public static final String EARBM = "EARBM";
	public static final String EARBS = "EARBS";
	public static final String EARLO = "EARLO";
	public static final String EC = "EC";
	public static final String ELBOW = "ELBOW";
	public static final String ELBOWJ = "ELBOWJ";
	public static final String ENDC = "ENDC";
	public static final String ENDM = "ENDM";
	public static final String EOLPH = "EOLPH";
	public static final String EOS = "EOS";
	public static final String EPD = "EPD";
	public static final String EPICA = "EPICA";
	public static final String EPICM = "EPICM";
	public static final String EPIDU = "EPIDU";
	public static final String EPIGL = "EPIGL";
	public static final String ESO = "ESO";
	public static final String ESOPG = "ESOPG";
	public static final String ET = "ET";
	public static final String ETHMO = "ETHMO";
	public static final String EUR = "EUR";
	public static final String EYE = "EYE";
	public static final String EYELI = "EYELI";
	public static final String FACE = "FACE";
	public static final String FALLT = "FALLT";
	public static final String FBINC = "FBINC";
	public static final String FBLAC = "FBLAC";
	public static final String FBMAX = "FBMAX";
	public static final String FBNAS = "FBNAS";
	public static final String FBPAL = "FBPAL";
	public static final String FBVOM = "FBVOM";
	public static final String FBZYG = "FBZYG";
	public static final String FEMOR = "FEMOR";
	public static final String FEMUR = "FEMUR";
	public static final String FET = "FET";
	public static final String FIBU = "FIBU";
	public static final String FING = "FING";
	public static final String FINGN = "FINGN";
	public static final String FMH = "FMH";
	public static final String FOL = "FOL";
	public static final String FOOT = "FOOT";
	public static final String FOREA = "FOREA";
	public static final String FOREH = "FOREH";
	public static final String FORES = "FORES";
	public static final String FOURC = "FOURC";
	public static final String GB = "GB";
	public static final String GEN = "GEN";
	public static final String GENC = "GENC";
	public static final String GENL = "GENL";
	public static final String GL = "GL";
	public static final String GLAND = "GLAND";
	public static final String GLANS = "GLANS";
	public static final String GLUT = "GLUT";
	public static final String GLUTE = "GLUTE";
	public static final String GLUTM = "GLUTM";
	public static final String GROIN = "GROIN";
	public static final String GUM = "GUM";
	public static final String GVU = "GVU";
	public static final String HAL = "HAL";
	public static final String HAND = "HAND";
	public static final String HAR = "HAR";
	public static final String HART = "HART";
	public static final String HEAD = "HEAD";
	public static final String HEEL = "HEEL";
	public static final String HEM = "HEM";
	public static final String HIP = "HIP";
	public static final String HIPJ = "HIPJ";
	public static final String HUMER = "HUMER";
	public static final String HV = "HV";
	public static final String HVB = "HVB";
	public static final String HVT = "HVT";
	public static final String HYMEN = "HYMEN";
	public static final String ICX = "ICX";
	public static final String ILC = "ILC";
	public static final String ILCON = "ILCON";
	public static final String ILCR = "ILCR";
	public static final String ILE = "ILE";
	public static final String ILEOS = "ILEOS";
	public static final String ILEUM = "ILEUM";
	public static final String ILIAC = "ILIAC";
	public static final String INASA = "INASA";
	public static final String INGUI = "INGUI";
	public static final String INSTL = "INSTL";
	public static final String INSTS = "INSTS";
	public static final String INT = "INT";
	public static final String INTRO = "INTRO";
	public static final String INTRU = "INTRU";
	public static final String ISCHI = "ISCHI";
	public static final String ISH = "ISH";
	public static final String JAW = "JAW";
	public static final String JUGI = "JUGI";
	public static final String KIDN = "KIDN?";
	public static final String KNEE = "KNEE";
	public static final String KNEEF = "KNEEF";
	public static final String KNEEJ = "KNEEJ";
	public static final String LABIA = "LABIA";
	public static final String LABMA = "LABMA";
	public static final String LABMI = "LABMI";
	public static final String LACRI = "LACRI";
	public static final String LAM = "LAM";
	public static final String LARYN = "LARYN";
	public static final String LEG = "LEG";
	public static final String LENS = "LENS";
	public static final String LING = "LING";
	public static final String LINGU = "LINGU";
	public static final String LIP = "LIP";
	public static final String LIVER = "LIVER";
	public static final String LMN = "LMN";
	public static final String LN = "LN";
	public static final String LNG = "LNG";
	public static final String LOBE = "LOBE";
	public static final String LOCH = "LOCH";
	public static final String LUMBA = "LUMBA";
	public static final String LUNG = "LUNG";
	public static final String LYM = "LYM";
	public static final String MAC = "MAC";
	public static final String MALLE = "MALLE";
	public static final String MANDI = "MANDI";
	public static final String MAR = "MAR";
	public static final String MAST = "MAST";
	public static final String MAXIL = "MAXIL";
	public static final String MAXS = "MAXS";
	public static final String MEATU = "MEATU";
	public static final String MEC = "MEC";
	public static final String MEDST = "MEDST";
	public static final String MEDU = "MEDU";
	public static final String METAC = "METAC";
	public static final String METAT = "METAT";
	public static final String MILK = "MILK";
	public static final String MITRL = "MITRL";
	public static final String MOLAR = "MOLAR";
	public static final String MONSU = "MONSU";
	public static final String MONSV = "MONSV";
	public static final String MOU = "MOU";
	public static final String MOUTH = "MOUTH";
	public static final String MP = "MP";
	public static final String MPB = "MPB";
	public static final String MRSA2 = "MRSA2";
	public static final String MYO = "MYO";
	public static final String NAIL = "NAIL";
	public static final String NAILB = "NAILB";
	public static final String NAILF = "NAILF";
	public static final String NAILT = "NAILT";
	public static final String NARES = "NARES";
	public static final String NASL = "NASL";
	public static final String NAVEL = "NAVEL";
	public static final String NECK = "NECK";
	public static final String NERVE = "NERVE";
	public static final String NIPPL = "NIPPL";
	public static final String NLACR = "NLACR";
	public static final String NOS = "NOS";
	public static final String NOSE = "NOSE";
	public static final String NOSTR = "NOSTR";
	public static final String NP = "NP";
	public static final String NSS = "NSS";
	public static final String NTRAC = "NTRAC";
	public static final String OCCIP = "OCCIP";
	public static final String OLECR = "OLECR";
	public static final String OMEN = "OMEN";
	public static final String ORBIT = "ORBIT";
	public static final String ORO = "ORO";
	public static final String OSCOX = "OSCOX";
	public static final String OVARY = "OVARY";
	public static final String PAFL = "PAFL";
	public static final String PALAT = "PALAT";
	public static final String PALM = "PALM";
	public static final String PANAL = "PANAL";
	public static final String PANCR = "PANCR";
	public static final String PARAT = "PARAT";
	public static final String PARIE = "PARIE";
	public static final String PARON = "PARON";
	public static final String PAROT = "PAROT";
	public static final String PAS = "PAS";
	public static final String PATEL = "PATEL";
	public static final String PCARD = "PCARD";
	public static final String PCLIT = "PCLIT";
	public static final String PELV = "PELV";
	public static final String PENIS = "PENIS";
	public static final String PENSH = "PENSH";
	public static final String PER = "PER";
	public static final String PERI = "PERI";
	public static final String PERIH = "PERIH";
	public static final String PERIN = "PERIN";
	public static final String PERIS = "PERIS";
	public static final String PERIT = "PERIT";
	public static final String PERIU = "PERIU";
	public static final String PERIV = "PERIV";
	public static final String PERRA = "PERRA";
	public static final String PERT = "PERT";
	public static final String PHALA = "PHALA";
	public static final String PILO = "PILO";
	public static final String PINNA = "PINNA";
	public static final String PLACF = "PLACF";
	public static final String PLACM = "PLACM";
	public static final String PLANT = "PLANT";
	public static final String PLATH = "PLATH";
	public static final String PLATS = "PLATS";
	public static final String PLC = "PLC";
	public static final String PLEU = "PLEU";
	public static final String PLEUR = "PLEUR";
	public static final String PLR = "PLR";
	public static final String PNEAL = "PNEAL";
	public static final String PNEPH = "PNEPH";
	public static final String PNM = "PNM";
	public static final String POPLI = "POPLI";
	public static final String PORBI = "PORBI";
	public static final String PREAU = "PREAU";
	public static final String PRERE = "PRERE";
	public static final String PROS = "PROS";
	public static final String PRST = "PRST";
	public static final String PTONS = "PTONS";
	public static final String PUBIC = "PUBIC";
	public static final String PUL = "PUL";
	public static final String RADI = "RADI";
	public static final String RADIUS = "RADIUS";
	public static final String RBC = "RBC";
	public static final String RECTL = "RECTL";
	public static final String RECTU = "RECTU";
	public static final String RENL = "RENL";
	public static final String RIB = "RIB";
	public static final String RNP = "RNP";
	public static final String RPERI = "RPERI";
	public static final String SAC = "SAC";
	public static final String SACIL = "SACIL";
	public static final String SACRA = "SACRA";
	public static final String SACRO = "SACRO";
	public static final String SACRU = "SACRU";
	public static final String SALGL = "SALGL";
	public static final String SCALP = "SCALP";
	public static final String SCAPU = "SCAPU";
	public static final String SCLAV = "SCLAV";
	public static final String SCLER = "SCLER";
	public static final String SCLV = "SCLV";
	public static final String SCROT = "SCROT";
	public static final String SDP = "SDP";
	public static final String SEM = "SEM";
	public static final String SEMN = "SEMN";
	public static final String SEPTU = "SEPTU";
	public static final String SEROM = "SEROM";
	public static final String SGF = "SGF";
	public static final String SHIN = "SHIN";
	public static final String SHOL = "SHOL";
	public static final String SHOLJ = "SHOLJ";
	public static final String SIGMO = "SIGMO";
	public static final String SINUS = "SINUS";
	public static final String SKENE = "SKENE";
	public static final String SKM = "SKM";
	public static final String SKULL = "SKULL";
	public static final String SOLE = "SOLE";
	public static final String SPCOR = "SPCOR";
	public static final String SPHEN = "SPHEN";
	public static final String SPLN = "SPLN";
	public static final String SPRM = "SPRM";
	public static final String SPX = "SPX";
	public static final String STER = "STER";
	public static final String STOM = "STOM";
	public static final String STOMA = "STOMA";
	public static final String STOOLL = "STOOLL";
	public static final String STUMP = "STUMP";
	public static final String SUB = "SUB";
	public static final String SUBD = "SUBD";
	public static final String SUBM = "SUBM";
	public static final String SUBME = "SUBME";
	public static final String SUBPH = "SUBPH";
	public static final String SUBX = "SUBX";
	public static final String SUPB = "SUPB";
	public static final String SUPRA = "SUPRA";
	public static final String SWT = "SWT";
	public static final String SWTG = "SWTG";
	public static final String SYN = "SYN";
	public static final String SYNOL = "SYNOL";
	public static final String SYNOV = "SYNOV";
	public static final String TARS = "TARS";
	public static final String TBRON = "TBRON";
	public static final String TCN = "TCN";
	public static final String TDUCT = "TDUCT";
	public static final String TEAR = "TEAR";
	public static final String TEMPL = "TEMPL";
	public static final String TEMPO = "TEMPO";
	public static final String TESTI = "TESTI";
	public static final String THIGH = "THIGH";
	public static final String THM = "THM";
	public static final String THORA = "THORA";
	public static final String THRB = "THRB";
	public static final String THUMB = "THUMB";
	public static final String THYRD = "THYRD";
	public static final String TIBIA = "TIBIA";
	public static final String TML = "TML";
	public static final String TNL = "TNL";
	public static final String TOE = "TOE";
	public static final String TOEN = "TOEN";
	public static final String TONG = "TONG";
	public static final String TONS = "TONS";
	public static final String TOOTH = "TOOTH";
	public static final String TRCHE = "TRCHE";
	public static final String TSK = "TSK";
	public static final String ULNA = "ULNA";
	public static final String UMB = "UMB";
	public static final String UMBL = "UMBL";
	public static final String URET = "URET";
	public static final String URTH = "URTH";
	public static final String USTOM = "USTOM";
	public static final String UTER = "UTER";
	public static final String UTERI = "UTERI";
	public static final String VAGIN = "VAGIN";
	public static final String VAL = "VAL";
	public static final String VAS = "VAS";
	public static final String VASTL = "VASTL";
	public static final String VAULT = "VAULT";
	public static final String VCSF = "VCSF";
	public static final String VCUFF = "VCUFF";
	public static final String VEIN = "VEIN";
	public static final String VENTG = "VENTG";
	public static final String VERMI = "VERMI";
	public static final String VERTC = "VERTC";
	public static final String VERTL = "VERTL";
	public static final String VERTT = "VERTT";
	public static final String VESCL = "VESCL";
	public static final String VESFLD = "VESFLD";
	public static final String VESI = "VESI";
	public static final String VESTI = "VESTI";
	public static final String VGV = "VGV";
	public static final String VITR = "VITR";
	public static final String VOC = "VOC";
	public static final String VULVA = "VULVA";
	public static final String WBC = "WBC";
	public static final String WRIST = "WRIST";

	private Table0550(){
		setTableName("Body Parts");
		setOID("2.16.840.1.113883.12.550");

		putMap("ACET", "Acetabulum");
		putMap("ACHIL", "Achilles");
		putMap("ADB", "Abdomen");
		putMap("ADE", "Adenoids");
		putMap("ADR", "Adrenal");
		putMap("AMN", "Amniotic fluid");
		putMap("AMS", "Amniotic Sac");
		putMap("ANAL", "Anal");
		putMap("ANKL", "Ankle");
		putMap("ANTEC", "Antecubital");
		putMap("ANTECF", "Antecubital Fossa");
		putMap("ANTR", "Antrum");
		putMap("ANUS", "Anus");
		putMap("AORTA", "Aorta");
		putMap("APDX", "Appendix");
		putMap("AR", "Aortic Rim");
		putMap("AREO", "Areola");
		putMap("ARM", "Arm");
		putMap("ARTE", "Artery");
		putMap("ASCIT", "Ascites");
		putMap("ASCT", "Ascitic Fluid");
		putMap("ATR", "Atrium");
		putMap("AURI", "Auricular");
		putMap("AV", "Aortic Valve");
		putMap("AXI", "Axilla");
		putMap("BACK", "Back");
		putMap("BARTD", "Bartholin Duct");
		putMap("BARTG", "Bartholin Gland");
		putMap("BCYS", "Brain Cyst Fluid");
		putMap("BDY", "Body, Whole");
		putMap("BID", "Bile Duct");
		putMap("BIFL", "Bile fluid");
		putMap("BLAD", "Bladder");
		putMap("BLD", "Blood, Whole");
		putMap("BLDA", "Blood,  Arterial");
		putMap("BLDC", "Blood,  Capillary");
		putMap("BLDV", "Blood,  Venous");
		putMap("BLOOD", "Blood");
		putMap("BMAR", "Bone marrow");
		putMap("BON", "Bone");
		putMap("BOWEL", "Bowel");
		putMap("BOWLA", "Bowel, Large");
		putMap("BOWSM", "Bowel, Small");
		putMap("BPH", "Basophils");
		putMap("BRA", "Brachial");
		putMap("BRAIN", "Brain");
		putMap("BRO", "Bronchial");
		putMap("BROCH", "Bronchiole/Bronchiolar");
		putMap("BRONC", "Bronchus/Bronchial");
		putMap("BROW", "Eyebrow");
		putMap("BRST", "Breast");
		putMap("BRSTFL", "Breast fluid");
		putMap("BRTGF", "Bartholin Gland Fluid");
		putMap("BRV", "Broviac");
		putMap("BUCCA", "Buccal");
		putMap("BURSA", "Bursa");
		putMap("BURSF", "Bursa Fluid");
		putMap("BUTT", "Buttocks");
		putMap("CALF", "Calf");
		putMap("CANAL", "Canal");
		putMap("CANLI", "Canaliculis");
		putMap("CANTH", "Canthus");
		putMap("CARO", "Carotid");
		putMap("CARP", "Carpal");
		putMap("CAVIT", "Cavity");
		putMap("CBLD", "Blood, Cord");
		putMap("CDM", "Cardiac Muscle");
		putMap("CDUCT", "Common Duct");
		putMap("CECUM", "Cecum/Cecal");
		putMap("CERVUT", "Cervix/Uterus");
		putMap("CHE", "Cavity, Chest");
		putMap("CHEEK", "Cheek");
		putMap("CHES", "Chest");
		putMap("CHEST?", "Chest Tube");
		putMap("CHIN", "Chin");
		putMap("CIRCU", "Circumcision Site");
		putMap("CLAVI", "Clavicle/Clavicular");
		putMap("CLIT", "Clitoris");
		putMap("CLITO", "Clitoral");
		putMap("CNL", "Cannula");
		putMap("COCCG", "Coccygeal");
		putMap("COCCY", "Coccyx");
		putMap("COLON", "Colon");
		putMap("COLOS", "Colostomy");
		putMap("CONJ", "Conjunctiva");
		putMap("COR", "Cord");
		putMap("CORAL", "Coral");
		putMap("CORD", "Cord Blood");
		putMap("CORN", "Cornea");
		putMap("COS", "Colostomy Stoma");
		putMap("CRANE", "Cranium, ethmoid");
		putMap("CRANF", "Cranium, frontal");
		putMap("CRANO", "Cranium, occipital");
		putMap("CRANP", "Cranium, parietal");
		putMap("CRANS", "Cranium, sphenoid");
		putMap("CRANT", "Cranium, temporal");
		putMap("CSF", "Cerebral Spinal Fluid");
		putMap("CUBIT", "Cubitus");
		putMap("CUFF", "Cuff");
		putMap("CULD", "Cul De Sac");
		putMap("CULDO", "Culdocentesis");
		putMap("CVX", "Cervix");
		putMap("DELT", "Deltoid");
		putMap("DEN", "Dental Gingiva");
		putMap("DENTA", "Dental");
		putMap("DIAF", "Dialysis Fluid");
		putMap("DIGIT", "Digit");
		putMap("DISC", "Disc");
		putMap("DORS", "Dorsum/Dorsal");
		putMap("DPH", "Diaphragm");
		putMap("DUFL", "Duodenal Fluid");
		putMap("DUODE", "Duodenum/Duodenal");
		putMap("DUR", "Dura");
		putMap("EAR", "Ear");
		putMap("EARBI", "Ear bone, incus");
		putMap("EARBM", "Ear bone, malleus");
		putMap("EARBS", "Ear bone,stapes");
		putMap("EARLO", "Ear Lobe");
		putMap("EC", "Endocervical");
		putMap("ELBOW", "Elbow");
		putMap("ELBOWJ", "Elbow Joint");
		putMap("ENDC", "Endocardium");
		putMap("ENDM", "Endometrium");
		putMap("EOLPH", "endolpthamitis");
		putMap("EOS", "Eosinophils");
		putMap("EPD", "Epididymis");
		putMap("EPICA", "Epicardial");
		putMap("EPICM", "Epicardium");
		putMap("EPIDU", "Epidural");
		putMap("EPIGL", "Epiglottis");
		putMap("ESO", "Esophagus");
		putMap("ESOPG", "Esophageal");
		putMap("ET", "Endotracheal");
		putMap("ETHMO", "Ethmoid");
		putMap("EUR", "Endourethral");
		putMap("EYE", "Eye");
		putMap("EYELI", "Eyelid");
		putMap("FACE", "Face");
		putMap("FALLT", "Fallopian Tube");
		putMap("FBINC", "Facial bone, inferior nasal concha");
		putMap("FBLAC", "Facial bone, lacrimal");
		putMap("FBMAX", "Facial bone, maxilla");
		putMap("FBNAS", "Facial bone, nasal");
		putMap("FBPAL", "Facial bone, palatine");
		putMap("FBVOM", "Facial bone, vomer");
		putMap("FBZYG", "Facial bone, zygomatic");
		putMap("FEMOR", "Femoral");
		putMap("FEMUR", "Femur");
		putMap("FET", "Fetus");
		putMap("FIBU", "Fibula");
		putMap("FING", "Finger");
		putMap("FINGN", "Finger Nail");
		putMap("FMH", "Femoral Head");
		putMap("FOL", "Follicle");
		putMap("FOOT", "Foot");
		putMap("FOREA", "Forearm");
		putMap("FOREH", "Forehead");
		putMap("FORES", "Foreskin");
		putMap("FOURC", "Fourchette");
		putMap("GB", "Gall Bladder");
		putMap("GEN", "Genital");
		putMap("GENC", "Genital Cervix");
		putMap("GENL", "Genital Lochia");
		putMap("GL", "Genital Lesion");
		putMap("GLAND", "Gland");
		putMap("GLANS", "Glans");
		putMap("GLUT", "Gluteus");
		putMap("GLUTE", "Gluteal");
		putMap("GLUTM", "Gluteus Medius");
		putMap("GROIN", "Groin");
		putMap("GUM", "Gum");
		putMap("GVU", "Genital - Vulva");
		putMap("HAL", "Hallux");
		putMap("HAND", "Hand");
		putMap("HAR", "Hair");
		putMap("HART", "Heart");
		putMap("HEAD", "Head");
		putMap("HEEL", "Heel");
		putMap("HEM", "Hemorrhoid");
		putMap("HIP", "Hip");
		putMap("HIPJ", "Hip Joint");
		putMap("HUMER", "Humerus");
		putMap("HV", "Heart Valve");
		putMap("HVB", "Heart Valve, Bicuspid");
		putMap("HVT", "Heart Valve, Tricuspid");
		putMap("HYMEN", "Hymen");
		putMap("ICX", "Intracervical");
		putMap("ILC", "Ileal Conduit");
		putMap("ILCON", "Ilical Conduit");
		putMap("ILCR", "Iliac Crest");
		putMap("ILE", "Ileal Loop");
		putMap("ILEOS", "Ileostomy");
		putMap("ILEUM", "Ileum");
		putMap("ILIAC", "Iliac");
		putMap("INASA", "Intranasal");
		putMap("INGUI", "Inguinal");
		putMap("INSTL", "Intestine, Large");
		putMap("INSTS", "Intestine, Small");
		putMap("INT", "Intestine");
		putMap("INTRO", "Introitus");
		putMap("INTRU", "Intrauterine");
		putMap("ISCHI", "Ischium");
		putMap("ISH", "Loop, Ishial");
		putMap("JAW", "Jaw");
		putMap("JUGI", "Jugular, Internal");
		putMap("KIDN?", "Kidney");
		putMap("KNEE", "Knee");
		putMap("KNEEF", "Knee Fluid");
		putMap("KNEEJ", "Knee Joint");
		putMap("LABIA", "Labia");
		putMap("LABMA", "Labia Majora");
		putMap("LABMI", "Labia Minora");
		putMap("LACRI", "Lacrimal");
		putMap("LAM", "Lamella");
		putMap("LARYN", "Larynx");
		putMap("LEG", "Leg");
		putMap("LENS", "Lens");
		putMap("LING", "Lingual");
		putMap("LINGU", "Lingula");
		putMap("LIP", "Lip");
		putMap("LIVER", "Liver");
		putMap("LMN", "Lumen");
		putMap("LN", "Lymph Node");
		putMap("LNG", "Lymph Node, Groin");
		putMap("LOBE", "Lobe");
		putMap("LOCH", "Lochia");
		putMap("LUMBA", "Lumbar");
		putMap("LUNG", "Lung");
		putMap("LYM", "Lymphocytes");
		putMap("MAC", "Macrophages");
		putMap("MALLE", "Malleolus");
		putMap("MANDI", "Mandible/Mandibular");
		putMap("MAR", "Marrow");
		putMap("MAST", "Mastoid");
		putMap("MAXIL", "Maxilla/Maxillary");
		putMap("MAXS", "Maxillary Sinus");
		putMap("MEATU", "Meatus");
		putMap("MEC", "Meconium");
		putMap("MEDST", "Mediastinum");
		putMap("MEDU", "Medullary");
		putMap("METAC", "Metacarpal");
		putMap("METAT", "Metatarsal");
		putMap("MILK", "Milk, Breast");
		putMap("MITRL", "Mitral Valve");
		putMap("MOLAR", "Molar");
		putMap("MONSU", "Mons Ureteris");
		putMap("MONSV", "Mons Veneris(Mons Pubis)");
		putMap("MOU", "Membrane");
		putMap("MOUTH", "Mouth");
		putMap("MP", "Mons Pubis");
		putMap("MPB", "Meninges");
		putMap("MRSA2", "Mrsa:");
		putMap("MYO", "Myocardium");
		putMap("NAIL", "Nail");
		putMap("NAILB", "Nail Bed");
		putMap("NAILF", "Nail, Finger");
		putMap("NAILT", "Nail, Toe");
		putMap("NARES", "Nares");
		putMap("NASL", "Nasal");
		putMap("NAVEL", "Navel");
		putMap("NECK", "Neck");
		putMap("NERVE", "Nerve");
		putMap("NIPPL", "Nipple");
		putMap("NLACR", "Nasolacrimal");
		putMap("NOS", "Nose (Nasal Passage)");
		putMap("NOSE", "Nose");
		putMap("NOSTR", "Nostril");
		putMap("NP", "Nasopharyngeal");
		putMap("NSS", "Nasal Septum");
		putMap("NTRAC", "Nasotracheal");
		putMap("OCCIP", "Occipital");
		putMap("OLECR", "Olecranon");
		putMap("OMEN", "Omentum");
		putMap("ORBIT", "Orbit/Orbital");
		putMap("ORO", "Oropharynx");
		putMap("OSCOX", "Os coxa (pelvic girdle)");
		putMap("OVARY", "Ovary");
		putMap("PAFL", "Pancreatic Fluid");
		putMap("PALAT", "Palate");
		putMap("PALM", "Palm");
		putMap("PANAL", "Perianal/Perirectal");
		putMap("PANCR", "Pancreas");
		putMap("PARAT", "Paratracheal");
		putMap("PARIE", "Parietal");
		putMap("PARON", "Paronychia");
		putMap("PAROT", "Parotid");
		putMap("PAS", "Parasternal");
		putMap("PATEL", "Patella");
		putMap("PCARD", "Pericardium");
		putMap("PCLIT", "Periclitoral");
		putMap("PELV", "Pelvis");
		putMap("PENIS", "Penis");
		putMap("PENSH", "Penile Shaft");
		putMap("PER", "Peritoneal");
		putMap("PERI", "Pericardial Fluid");
		putMap("PERIH", "Perihepatic");
		putMap("PERIN", "Perineal Abscess");
		putMap("PERIS", "Perisplenic");
		putMap("PERIT", "Peritoneum");
		putMap("PERIU", "Periurethal");
		putMap("PERIV", "Perivesicular");
		putMap("PERRA", "Perirectal");
		putMap("PERT", "Peritoneal Fluid");
		putMap("PHALA", "Phalanyx");
		putMap("PILO", "Pilonidal");
		putMap("PINNA", "Pinna");
		putMap("PLACF", "Placenta (Fetal Side)");
		putMap("PLACM", "Placenta (Maternal Side)");
		putMap("PLANT", "Plantar");
		putMap("PLATH", "Palate, Hard");
		putMap("PLATS", "Palate, Soft");
		putMap("PLC", "Placenta");
		putMap("PLEU", "Pleural Fluid");
		putMap("PLEUR", "Pleura");
		putMap("PLR", "Pleural Fluid (Thoracentesis Fld)");
		putMap("PNEAL", "Perineal");
		putMap("PNEPH", "Perinephric");
		putMap("PNM", "Perineum");
		putMap("POPLI", "Popliteal");
		putMap("PORBI", "Periorbital");
		putMap("PREAU", "Preauricular");
		putMap("PRERE", "Prerenal");
		putMap("PROS", "Prostatic Fluid");
		putMap("PRST", "Prostate Gland");
		putMap("PTONS", "Peritonsillar");
		putMap("PUBIC", "Pubic");
		putMap("PUL", "Pulmonary Artery");
		putMap("RADI", "Radial");
		putMap("RADIUS", "Radius");
		putMap("RBC", "Red Blood Cells");
		putMap("RECTL", "Rectal");
		putMap("RECTU", "Rectum");
		putMap("RENL", "Renal");
		putMap("RIB", "Rib");
		putMap("RNP", "Renal Pelvis");
		putMap("RPERI", "Retroperitoneal");
		putMap("SAC", "Uterine Cul/De/Sac");
		putMap("SACIL", "Sacroiliac");
		putMap("SACRA", "Sacral");
		putMap("SACRO", "Sacrococcygeal");
		putMap("SACRU", "Sacrum");
		putMap("SALGL", "Salivary Gland");
		putMap("SCALP", "Scalp");
		putMap("SCAPU", "Scapula/Scapular");
		putMap("SCLAV", "Supraclavicle/Supraclavicular");
		putMap("SCLER", "Sclera");
		putMap("SCLV", "Sub Clavian");
		putMap("SCROT", "Scrotum/Scrotal");
		putMap("SDP", "Subdiaphramatic");
		putMap("SEM", "Seminal Fluid");
		putMap("SEMN", "Semen");
		putMap("SEPTU", "Septum/Septal");
		putMap("SEROM", "Seroma");
		putMap("SGF", "Subgaleal Fluid");
		putMap("SHIN", "Shin");
		putMap("SHOL", "Shoulder");
		putMap("SHOLJ", "Sholder Joint");
		putMap("SIGMO", "Sigmoid");
		putMap("SINUS", "Sinus");
		putMap("SKENE", "Skene's Gland");
		putMap("SKM", "Skeletal Muscle");
		putMap("SKULL", "Skull");
		putMap("SOLE", "Sole");
		putMap("SPCOR", "Spinal Cord");
		putMap("SPHEN", "Sphenoid");
		putMap("SPLN", "Spleen");
		putMap("SPRM", "Spermatozoa");
		putMap("SPX", "Supra Cervical");
		putMap("STER", "Sternum/Sternal");
		putMap("STOM", "Stoma");
		putMap("STOMA", "Stomach");
		putMap("STOOLL", "Liquid Stool");
		putMap("STUMP", "Stump");
		putMap("SUB", "Subdural");
		putMap("SUBD", "Subdural Fluid");
		putMap("SUBM", "Submandibular");
		putMap("SUBME", "Submental");
		putMap("SUBPH", "Subphrenic");
		putMap("SUBX", "Submaxillary");
		putMap("SUPB", "Suprapubic Specimen");
		putMap("SUPRA", "Suprapubic");
		putMap("SWT", "Sweat");
		putMap("SWTG", "Sweat Gland");
		putMap("SYN", "Synovial Fluid");
		putMap("SYNOL", "Synovial");
		putMap("SYNOV", "Synovium");
		putMap("TARS", "Tarsal");
		putMap("TBRON", "Transbronchial");
		putMap("TCN", "Transcarina Asp");
		putMap("TDUCT", "Tear Duct");
		putMap("TEAR", "Tears");
		putMap("TEMPL", "Temple");
		putMap("TEMPO", "Temporal");
		putMap("TESTI", "Testicle(Testis)");
		putMap("THIGH", "Thigh");
		putMap("THM", "Thymus");
		putMap("THORA", "Thoracentesis");
		putMap("THRB", "Throat");
		putMap("THUMB", "Thumb");
		putMap("THYRD", "Thyroid");
		putMap("TIBIA", "Tibia");
		putMap("TML", "Temporal Lobe");
		putMap("TNL", "Thumbnail");
		putMap("TOE", "Toe");
		putMap("TOEN", "Toe Nail");
		putMap("TONG", "Tongue");
		putMap("TONS", "Tonsil");
		putMap("TOOTH", "Tooth");
		putMap("TRCHE", "Trachea/Tracheal");
		putMap("TSK", "Tooth Socket");
		putMap("ULNA", "Ulna/Ulnar");
		putMap("UMB", "Umbilical Blood");
		putMap("UMBL", "Umbilicus");
		putMap("URET", "Ureter");
		putMap("URTH", "Urethra");
		putMap("USTOM", "Stoma, Urinary");
		putMap("UTER", "Uterus");
		putMap("UTERI", "Uterine");
		putMap("VAGIN", "Vagina/Vaginal");
		putMap("VAL", "Valve");
		putMap("VAS", "Vas Deferens");
		putMap("VASTL", "Vastus Lateralis");
		putMap("VAULT", "Vault");
		putMap("VCSF", "Ventricular CSF");
		putMap("VCUFF", "Vaginal Cuff");
		putMap("VEIN", "Vein");
		putMap("VENTG", "Ventragluteal");
		putMap("VERMI", "Vermis Cerebelli");
		putMap("VERTC", "Vertebra, cervical");
		putMap("VERTL", "Vertebra, lumbar");
		putMap("VERTT", "Vertebra, thoracic");
		putMap("VESCL", "Vesicular");
		putMap("VESFLD", "Vesicular Fluid");
		putMap("VESI", "Vesicle");
		putMap("VESTI", "Vestibule(Genital)");
		putMap("VGV", "Vaginal Vault");
		putMap("VITR", "Vitreous Fluid");
		putMap("VOC", "Vocal Cord");
		putMap("VULVA", "Vulva");
		putMap("WBC", "Leukocytes");
		putMap("WRIST", "Wrist");

	}

}
