package hl7.model.V2_5.table;

import hl7.bean.table.Table;

public class Table0003 extends Table{
	private static final String VERSION = "2.5";
	public static Table getInstance(){
		if(table==null) new Table0003();
		return table;
	}

	public static final String A01 = "A01";
	public static final String A02 = "A02";
	public static final String A03 = "A03";
	public static final String A04 = "A04";
	public static final String A05 = "A05";
	public static final String A06 = "A06";
	public static final String A07 = "A07";
	public static final String A08 = "A08";
	public static final String A09 = "A09";
	public static final String A10 = "A10";
	public static final String A11 = "A11";
	public static final String A12 = "A12";
	public static final String A13 = "A13";
	public static final String A14 = "A14";
	public static final String A15 = "A15";
	public static final String A16 = "A16";
	public static final String A17 = "A17";
	public static final String A18 = "A18";
	public static final String A19 = "A19";
	public static final String A20 = "A20";
	public static final String A21 = "A21";
	public static final String A22 = "A22";
	public static final String A23 = "A23";
	public static final String A24 = "A24";
	public static final String A25 = "A25";
	public static final String A26 = "A26";
	public static final String A27 = "A27";
	public static final String A28 = "A28";
	public static final String A29 = "A29";
	public static final String A30 = "A30";
	public static final String A31 = "A31";
	public static final String A32 = "A32";
	public static final String A33 = "A33";
	public static final String A34 = "A34";
	public static final String A35 = "A35";
	public static final String A36 = "A36";
	public static final String A37 = "A37";
	public static final String A38 = "A38";
	public static final String A39 = "A39";
	public static final String A40 = "A40";
	public static final String A41 = "A41";
	public static final String A42 = "A42";
	public static final String A43 = "A43";
	public static final String A44 = "A44";
	public static final String A45 = "A45";
	public static final String A46 = "A46";
	public static final String A47 = "A47";
	public static final String A48 = "A48";
	public static final String A49 = "A49";
	public static final String A50 = "A50";
	public static final String A51 = "A51";
	public static final String A52 = "A52";
	public static final String A53 = "A53";
	public static final String A54 = "A54";
	public static final String A55 = "A55";
	public static final String A60 = "A60";
	public static final String A61 = "A61";
	public static final String A62 = "A62";
	public static final String B01 = "B01";
	public static final String B02 = "B02";
	public static final String B03 = "B03";
	public static final String B04 = "B04";
	public static final String B05 = "B05";
	public static final String B06 = "B06";
	public static final String B07 = "B07";
	public static final String B08 = "B08";
	public static final String C01 = "C01";
	public static final String C02 = "C02";
	public static final String C03 = "C03";
	public static final String C04 = "C04";
	public static final String C05 = "C05";
	public static final String C06 = "C06";
	public static final String C07 = "C07";
	public static final String C08 = "C08";
	public static final String C09 = "C09";
	public static final String C10 = "C10";
	public static final String C11 = "C11";
	public static final String C12 = "C12";
	public static final String CNQ = "CNQ";
	public static final String I01 = "I01";
	public static final String I02 = "I02";
	public static final String I03 = "I03";
	public static final String I04 = "I04";
	public static final String I05 = "I05";
	public static final String I06 = "I06";
	public static final String I07 = "I07";
	public static final String I08 = "I08";
	public static final String I09 = "I09";
	public static final String I10 = "I10";
	public static final String I11 = "I11";
	public static final String I12 = "I12";
	public static final String I13 = "I13";
	public static final String I14 = "I14";
	public static final String I15 = "I15";
	public static final String J01 = "J01";
	public static final String J02 = "J02";
	public static final String K11 = "K11";
	public static final String K13 = "K13";
	public static final String K15 = "K15";
	public static final String K21 = "K21";
	public static final String K22 = "K22";
	public static final String K23 = "K23";
	public static final String K24 = "K24";
	public static final String K25 = "K25";
	public static final String M01 = "M01";
	public static final String M02 = "M02";
	public static final String M03 = "M03";
	public static final String M04 = "M04";
	public static final String M05 = "M05";
	public static final String M06 = "M06";
	public static final String M07 = "M07";
	public static final String M08 = "M08";
	public static final String M09 = "M09";
	public static final String M10 = "M10";
	public static final String M11 = "M11";
	public static final String M12 = "M12";
	public static final String M13 = "M13";
	public static final String M14 = "M14";
	public static final String M15 = "M15";
	public static final String N01 = "N01";
	public static final String N02 = "N02";
	public static final String O01 = "O01";
	public static final String O02 = "O02";
	public static final String O03 = "O03";
	public static final String O04 = "O04";
	public static final String O05 = "O05";
	public static final String O06 = "O06";
	public static final String O07 = "O07";
	public static final String O08 = "O08";
	public static final String O09 = "O09";
	public static final String O10 = "O10";
	public static final String O11 = "O11";
	public static final String O12 = "O12";
	public static final String O13 = "O13";
	public static final String O14 = "O14";
	public static final String O15 = "O15";
	public static final String O16 = "O16";
	public static final String O17 = "O17";
	public static final String O18 = "O18";
	public static final String O19 = "O19";
	public static final String O20 = "O20";
	public static final String O21 = "O21";
	public static final String O22 = "O22";
	public static final String O23 = "O23";
	public static final String O24 = "O24";
	public static final String O25 = "O25";
	public static final String O26 = "O26";
	public static final String O27 = "O27";
	public static final String O28 = "O28";
	public static final String O29 = "O29";
	public static final String O30 = "O30";
	public static final String O31 = "O31";
	public static final String O32 = "O32";
	public static final String O33 = "O33";
	public static final String O34 = "O34";
	public static final String O35 = "O35";
	public static final String O36 = "O36";
	public static final String P01 = "P01";
	public static final String P02 = "P02";
	public static final String P03 = "P03";
	public static final String P04 = "P04";
	public static final String P05 = "P05";
	public static final String P06 = "P06";
	public static final String P07 = "P07";
	public static final String P08 = "P08";
	public static final String P09 = "P09";
	public static final String P10 = "P10";
	public static final String P11 = "P11";
	public static final String P12 = "P12";
	public static final String PC1 = "PC1";
	public static final String PC2 = "PC2";
	public static final String PC3 = "PC3";
	public static final String PC4 = "PC4";
	public static final String PC5 = "PC5";
	public static final String PC6 = "PC6";
	public static final String PC7 = "PC7";
	public static final String PC8 = "PC8";
	public static final String PC9 = "PC9";
	public static final String PCA = "PCA";
	public static final String PCB = "PCB";
	public static final String PCC = "PCC";
	public static final String PCD = "PCD";
	public static final String PCE = "PCE";
	public static final String PCF = "PCF";
	public static final String PCG = "PCG";
	public static final String PCH = "PCH";
	public static final String PCJ = "PCJ";
	public static final String PCK = "PCK";
	public static final String PCL = "PCL";
	public static final String Q01 = "Q01";
	public static final String Q02 = "Q02";
	public static final String Q03 = "Q03";
	public static final String Q04 = "Q04";
	public static final String Q05 = "Q05";
	public static final String Q06 = "Q06";
	public static final String Q07 = "Q07";
	public static final String Q08 = "Q08";
	public static final String Q09 = "Q09";
	public static final String Q11 = "Q11";
	public static final String Q13 = "Q13";
	public static final String Q15 = "Q15";
	public static final String Q16 = "Q16";
	public static final String Q17 = "Q17";
	public static final String Q21 = "Q21";
	public static final String Q22 = "Q22";
	public static final String Q23 = "Q23";
	public static final String Q24 = "Q24";
	public static final String Q25 = "Q25";
	public static final String Q26 = "Q26";
	public static final String Q27 = "Q27";
	public static final String Q28 = "Q28";
	public static final String Q29 = "Q29";
	public static final String Q30 = "Q30";
	public static final String R01 = "R01";
	public static final String R02 = "R02";
	public static final String R03 = "R03";
	public static final String R04 = "R04";
	public static final String R07 = "R07";
	public static final String R08 = "R08";
	public static final String R09 = "R09";
	public static final String R21 = "R21";
	public static final String R22 = "R22";
	public static final String R23 = "R23";
	public static final String R24 = "R24";
	public static final String R30 = "R30";
	public static final String R31 = "R31";
	public static final String R32 = "R32";
	public static final String ROR = "ROR";
	public static final String S01 = "S01";
	public static final String S02 = "S02";
	public static final String S03 = "S03";
	public static final String S04 = "S04";
	public static final String S05 = "S05";
	public static final String S06 = "S06";
	public static final String S07 = "S07";
	public static final String S08 = "S08";
	public static final String S09 = "S09";
	public static final String S10 = "S10";
	public static final String S11 = "S11";
	public static final String S12 = "S12";
	public static final String S13 = "S13";
	public static final String S14 = "S14";
	public static final String S15 = "S15";
	public static final String S16 = "S16";
	public static final String S17 = "S17";
	public static final String S18 = "S18";
	public static final String S19 = "S19";
	public static final String S20 = "S20";
	public static final String S21 = "S21";
	public static final String S22 = "S22";
	public static final String S23 = "S23";
	public static final String S24 = "S24";
	public static final String S25 = "S25";
	public static final String S26 = "S26";
	public static final String T01 = "T01";
	public static final String T02 = "T02";
	public static final String T03 = "T03";
	public static final String T04 = "T04";
	public static final String T05 = "T05";
	public static final String T06 = "T06";
	public static final String T07 = "T07";
	public static final String T08 = "T08";
	public static final String T09 = "T09";
	public static final String T10 = "T10";
	public static final String T11 = "T11";
	public static final String T12 = "T12";
	public static final String U01 = "U01";
	public static final String U02 = "U02";
	public static final String U03 = "U03";
	public static final String U04 = "U04";
	public static final String U05 = "U05";
	public static final String U06 = "U06";
	public static final String U07 = "U07";
	public static final String U08 = "U08";
	public static final String U09 = "U09";
	public static final String U10 = "U10";
	public static final String U11 = "U11";
	public static final String U12 = "U12";
	public static final String U13 = "U13";
	public static final String V01 = "V01";
	public static final String V02 = "V02";
	public static final String V03 = "V03";
	public static final String V04 = "V04";
	public static final String Varies = "Varies";
	public static final String W01 = "W01";
	public static final String W02 = "W02";

	private Table0003(){
		setTableName("Event type");
		setOID("2.16.840.1.113883.12.3");

		putMap("A01", "ADT/ACK - Admit/visit notification");
		putMap("A02", "ADT/ACK - Transfer a patient");
		putMap("A03", "ADT/ACK -  Discharge/end visit");
		putMap("A04", "ADT/ACK -  Register a patient");
		putMap("A05", "ADT/ACK -  Pre-admit a patient");
		putMap("A06", "ADT/ACK -  Change an outpatient to an inpatient");
		putMap("A07", "ADT/ACK -  Change an inpatient to an outpatient");
		putMap("A08", "ADT/ACK -  Update patient information");
		putMap("A09", "ADT/ACK -  Patient departing - tracking");
		putMap("A10", "ADT/ACK -  Patient arriving - tracking");
		putMap("A11", "ADT/ACK -  Cancel admit/visit notification");
		putMap("A12", "ADT/ACK -  Cancel transfer");
		putMap("A13", "ADT/ACK -  Cancel discharge/end visit");
		putMap("A14", "ADT/ACK -  Pending admit");
		putMap("A15", "ADT/ACK -  Pending transfer");
		putMap("A16", "ADT/ACK -  Pending discharge");
		putMap("A17", "ADT/ACK -  Swap patients");
		putMap("A18", "ADT/ACK -  Merge patient information (for backward compatibility only)");
		putMap("A19", "QRY/ADR -  Patient query");
		putMap("A20", "ADT/ACK -  Bed status update");
		putMap("A21", "ADT/ACK -  Patient goes on a 'leave of absence'");
		putMap("A22", "ADT/ACK -  Patient returns from a 'leave of absence'");
		putMap("A23", "ADT/ACK -  Delete a patient record");
		putMap("A24", "ADT/ACK -  Link patient information");
		putMap("A25", "ADT/ACK -  Cancel pending discharge");
		putMap("A26", "ADT/ACK -  Cancel pending transfer");
		putMap("A27", "ADT/ACK -  Cancel pending admit");
		putMap("A28", "ADT/ACK -  Add person information");
		putMap("A29", "ADT/ACK -  Delete person information");
		putMap("A30", "ADT/ACK -  Merge person information (for backward compatibility only)");
		putMap("A31", "ADT/ACK -  Update person information");
		putMap("A32", "ADT/ACK -  Cancel patient arriving - tracking");
		putMap("A33", "ADT/ACK -  Cancel patient departing - tracking");
		putMap("A34", "ADT/ACK -  Merge patient information - patient ID only (for backward compatibility only)");
		putMap("A35", "ADT/ACK -  Merge patient information - account number only (for backward compatibility only)");
		putMap("A36", "ADT/ACK -  Merge patient information - patient ID and account number (for backward compatibility only)");
		putMap("A37", "ADT/ACK -  Unlink patient information");
		putMap("A38", "ADT/ACK - Cancel pre-admit");
		putMap("A39", "ADT/ACK - Merge person - patient ID (for backward compatibility only)");
		putMap("A40", "ADT/ACK - Merge patient - patient identifier list");
		putMap("A41", "ADT/ACK - Merge account - patient account number");
		putMap("A42", "ADT/ACK - Merge visit - visit number");
		putMap("A43", "ADT/ACK - Move patient information - patient identifier list");
		putMap("A44", "ADT/ACK - Move account information - patient account number");
		putMap("A45", "ADT/ACK - Move visit information - visit number");
		putMap("A46", "ADT/ACK - Change patient ID (for backward compatibility only)");
		putMap("A47", "ADT/ACK - Change patient identifier list");
		putMap("A48", "ADT/ACK - Change alternate patient ID (for backward compatibility only)");
		putMap("A49", "ADT/ACK - Change patient account number");
		putMap("A50", "ADT/ACK - Change visit number");
		putMap("A51", "ADT/ACK - Change alternate visit ID");
		putMap("A52", "ADT/ACK - Cancel leave of absence for a patient");
		putMap("A53", "ADT/ACK - Cancel patient returns from a leave of absence");
		putMap("A54", "ADT/ACK - Change attending doctor");
		putMap("A55", "ADT/ACK - Cancel change attending doctor");
		putMap("A60", "ADT/ACK - Update allergy information");
		putMap("A61", "ADT/ACK - Change consulting doctor");
		putMap("A62", "ADT/ACK - Cancel change consulting doctor");
		putMap("B01", "PMU/ACK - Add personnel record");
		putMap("B02", "PMU/ACK - Update personnel record");
		putMap("B03", "PMU/ACK - Delete personnel re cord");
		putMap("B04", "PMU/ACK - Active practicing person");
		putMap("B05", "PMU/ACK - Deactivate practicing person");
		putMap("B06", "PMU/ACK - Terminate practicing person");
		putMap("B07", "PMU/ACK - Grant Certificate/Permission");
		putMap("B08", "PMU/ACK - Revoke Certificate/Permission");
		putMap("C01", "CRM - Register a patient on a clinical trial");
		putMap("C02", "CRM - Cancel a patient registration on clinical trial (for clerical mistakes only)");
		putMap("C03", "CRM - Correct/update registration information");
		putMap("C04", "CRM - Patient has gone off a clinical trial");
		putMap("C05", "CRM - Patient enters phase of clinical trial");
		putMap("C06", "CRM - Cancel patient entering a phase (clerical mistake)");
		putMap("C07", "CRM - Correct/update phase information");
		putMap("C08", "CRM - Patient has gone off phase of clinical trial");
		putMap("C09", "CSU - Automated time intervals for reporting, like monthly");
		putMap("C10", "CSU - Patient completes the clinical trial");
		putMap("C11", "CSU - Patient completes a phase of the clinical trial");
		putMap("C12", "CSU - Update/correction of patient order/result information");
		putMap("CNQ", "Cancel Query");
		putMap("I01", "RQI/RPI - Request for insurance information");
		putMap("I02", "RQI/RPL - Request/receipt of patient selection display list");
		putMap("I03", "RQI/RPR - Request/receipt of patient selection list");
		putMap("I04", "RQD/RPI - Request for patient demographic data");
		putMap("I05", "RQC/RCI - Request for patient clinical information");
		putMap("I06", "RQC/RCL - Request/receipt of clinical data listing");
		putMap("I07", "PIN/ACK - Unsolicited insurance information");
		putMap("I08", "RQA/RPA - Request for treatment authorization information");
		putMap("I09", "RQA/RPA - Request for modification to an authorization");
		putMap("I10", "RQA/RPA - Request for resubmission of an authorization");
		putMap("I11", "RQA/RPA - Request for cancellation of an authorization");
		putMap("I12", "REF/RRI - Patient referral");
		putMap("I13", "REF/RRI - Modify patient referral");
		putMap("I14", "REF/RRI - Cancel patient referral");
		putMap("I15", "REF/RRI - Request patient referral status");
		putMap("J01", "QCN/ACK - Cancel query/acknowledge message");
		putMap("J02", "QSX/ACK - Cancel subscription/acknowledge message");
		putMap("K11", "RSP - Segment pattern response in response to QBP^Q11");
		putMap("K13", "RTB - Tabular response in response to QBP^Q13");
		putMap("K15", "RDY - Display response in response to QBP^Q15");
		putMap("K21", "RSP - Get person demographics response");
		putMap("K22", "RSP - Find candidates response");
		putMap("K23", "RSP - Get corresponding identifiers response");
		putMap("K24", "RSP - Allocate identifiers response");
		putMap("K25", "RSP - Personnel Information by Segment Response");
		putMap("M01", "MFN/MFK - Master file not otherwise specified (for backward compatibility only)");
		putMap("M02", "MFN/MFK - Master file - staff practitioner");
		putMap("M03", "MFN/MFK - Master file - test/observation (for backward compatibility only)");
		putMap("M04", "MFN/MFK - Master files charge description");
		putMap("M05", "MFN/MFK - Patient location master file");
		putMap("M06", "MFN/MFK - Clinical study with phases and schedules master file");
		putMap("M07", "MFN/MFK - Clinical study without phases but with schedules master file");
		putMap("M08", "MFN/MFK - Test/observation (numeric) master file");
		putMap("M09", "MFN/MFK - Test/observation (categorical) master file");
		putMap("M10", "MFN/MFK - Test /observation batteries master file");
		putMap("M11", "MFN/MFK - Test/calculated observations master file");
		putMap("M12", "MFN/MFK - Master file notification message");
		putMap("M13", "MFN/MFK - Master file notification - general");
		putMap("M14", "MFN/MFK - Master file notification - site defined");
		putMap("M15", "MFN/MFK - Inventory item master file notification");
		putMap("N01", "NMQ/NMR - Application management query message");
		putMap("N02", "NMD/ACK - Application management data message (unsolicited)");
		putMap("O01", "ORM - Order message (also RDE, RDS, RGV, RAS)");
		putMap("O02", "ORR - Order response (also RRE, RRD, RRG, RRA)");
		putMap("O03", "OMD - Diet order");
		putMap("O04", "ORD - Diet order acknowledgment");
		putMap("O05", "OMS - Stock requisition order");
		putMap("O06", "ORS - Stock requisition acknowledgment");
		putMap("O07", "OMN - Non-stock requisition order");
		putMap("O08", "ORN - Non-stock requisition acknowledgment");
		putMap("O09", "OMP - Pharmacy/treatment order");
		putMap("O10", "ORP - Pharmacy/treatment order acknowledgment");
		putMap("O11", "RDE - Pharmacy/treatment encoded order");
		putMap("O12", "RRE - Pharmacy/treatment encoded order acknowledgment");
		putMap("O13", "RDS - Pharmacy/treatment dispense");
		putMap("O14", "RRD - Pharmacy/treatment dispense acknowledgment");
		putMap("O15", "RGV - Pharmacy/treatment give");
		putMap("O16", "RRG - Pharmacy/treatment give acknowledgment");
		putMap("O17", "RAS - Pharmacy/treatment administration");
		putMap("O18", "RRA - Pharmacy/treatment administration acknowledgment");
		putMap("O19", "OMG - General clinical order");
		putMap("O20", "ORG/ORL - General clinical order response");
		putMap("O21", "OML - Laboratory order");
		putMap("O22", "ORL - General laboratory order response message to any OML");
		putMap("O23", "OMI - Imaging order");
		putMap("O24", "ORI - Imaging order response message to any OMI");
		putMap("O25", "RDE - Pharmacy/treatment refill authorization request");
		putMap("O26", "RRE - Pharmacy/Treatment Refill Authorization Acknowledgement");
		putMap("O27", "OMB - Blood product order");
		putMap("O28", "ORB - Blood product order acknowledgment");
		putMap("O29", "BPS - Blood product dispense status");
		putMap("O30", "BRP - Blood product dispense status acknowledgment");
		putMap("O31", "BTS - Blood product transfusion/disposition");
		putMap("O32", "BRT - Blood product transfusion/disposition acknowledgment");
		putMap("O33", "OML - Laboratory order for multiple orders related to a single specimen");
		putMap("O34", "ORL - Laboratory order response message to a multiple order related to single specimen OML");
		putMap("O35", "OML - Laboratory order for multiple orders related to a single container of a specimen");
		putMap("O36", "ORL - Laboratory order response message to a single container of a specimen OML");
		putMap("P01", "BAR/ACK - Add patient accounts");
		putMap("P02", "BAR/ACK - Purge patient accounts");
		putMap("P03", "DFT/ACK - Post detail financial transaction");
		putMap("P04", "QRY/DSP - Generate bill and A/R statements");
		putMap("P05", "BAR/ACK - Update account");
		putMap("P06", "BAR/ACK - End account");
		putMap("P07", "PEX - Unsolicited initial individual product experience report");
		putMap("P08", "PEX - Unsolicited update individual product experience report");
		putMap("P09", "SUR - Summary product experience report");
		putMap("P10", "BAR/ACK - Transmit Ambulatory Payment  Classification(APC)");
		putMap("P11", "DFT/ACK - Post Detail Financial Transactions - New");
		putMap("P12", "BAR/ACK - Update Diagnosis/Procedure");
		putMap("PC1", "PPR - PC/ problem add");
		putMap("PC2", "PPR - PC/ problem update");
		putMap("PC3", "PPR - PC/ problem delete");
		putMap("PC4", "QRY - PC/ problem query");
		putMap("PC5", "PRR - PC/ problem response");
		putMap("PC6", "PGL - PC/ goal add");
		putMap("PC7", "PGL - PC/ goal update");
		putMap("PC8", "PGL - PC/ goal delete");
		putMap("PC9", "QRY - PC/ goal query");
		putMap("PCA", "PPV - PC/ goal response");
		putMap("PCB", "PPP - PC/ pathway (problem-oriented) add");
		putMap("PCC", "PPP - PC/ pathway (problem-oriented) update");
		putMap("PCD", "PPP - PC/ pathway (problem-oriented) delete");
		putMap("PCE", "QRY - PC/ pathway (problem-oriented) query");
		putMap("PCF", "PTR - PC/ pathway (problem-oriented) query response");
		putMap("PCG", "PPG - PC/ pathway (goal-oriented) add");
		putMap("PCH", "PPG - PC/ pathway (goal-oriented) update");
		putMap("PCJ", "PPG - PC/ pathway (goal-oriented) delete");
		putMap("PCK", "QRY - PC/ pathway (goal-oriented) query");
		putMap("PCL", "PPT - PC/ pathway (goal-oriented) query response");
		putMap("Q01", "QRY/DSR - Query sent for immediate response");
		putMap("Q02", "QRY/QCK - Query sent for deferred response");
		putMap("Q03", "DSR/ACK - Deferred response to a query");
		putMap("Q04", "EQQ - Embedded query language query");
		putMap("Q05", "UDM/ACK - Unsolicited display update message");
		putMap("Q06", "OSQ/OSR - Query for order status");
		putMap("Q07", "VQQ - Virtual table query");
		putMap("Q08", "SPQ - Stored procedure request");
		putMap("Q09", "RQQ - event replay query");
		putMap("Q11", "QBP - Query by parameter requesting an RSP segment pattern response");
		putMap("Q13", "QBP - Query by parameter requesting an  RTB - tabular response");
		putMap("Q15", "QBP - Query by parameter requesting an RDY display response");
		putMap("Q16", "QSB - Create subscription");
		putMap("Q17", "QVR - Query for previous events");
		putMap("Q21", "QBP - Get person demographics");
		putMap("Q22", "QBP - Find candidates");
		putMap("Q23", "QBP - Get corresponding identifiers");
		putMap("Q24", "QBP - Allocate identifiers");
		putMap("Q25", "QBP - Personnel Information by Segment Query");
		putMap("Q26", "ROR - Pharmacy/treatment order response");
		putMap("Q27", "RAR - Pharmacy/treatment administration information");
		putMap("Q28", "RDR - Pharmacy/treatment dispense information");
		putMap("Q29", "RER - Pharmacy/treatment encoded order information");
		putMap("Q30", "RGR - Pharmacy/treatment dose information");
		putMap("R01", "ORU/ACK - Unsolicited transmission of an observation message");
		putMap("R02", "QRY - Query for results of observation");
		putMap("R03", "QRY/DSR Display-oriented results, query/unsol. update (for backward compatibility only) (Replaced by Q05)");
		putMap("R04", "ORF - Response to query; transmission of requested observation");
		putMap("R07", "EDR - Enhanced Display Response");
		putMap("R08", "TBR - Tabular Data Response");
		putMap("R09", "ERP - Event Replay Response");
		putMap("R21", "OUL - Unsolicited laboratory observation");
		putMap("R22", "OUL - Unsolicited Specimen Oriented Observation Message");
		putMap("R23", "OUL - Unsolicited Specimen Container Oriented Observation Message");
		putMap("R24", "OUL - Unsolicited Order Oriented Observation Message");
		putMap("R30", "ORU - Unsolicited Point-Of-Care Observation Message Without Existing Order - Place An Order");
		putMap("R31", "ORU - Unsolicited New Point-Of-Care Observation Message - Search For An Order");
		putMap("R32", "ORU - Unsolicited Pre-Ordered Point-Of-Care Observation");
		putMap("ROR", "ROR - Pharmacy prescription order query response");
		putMap("S01", "SRM/SRR - Request new appointment booking");
		putMap("S02", "SRM/SRR - Request appointment rescheduling");
		putMap("S03", "SRM/SRR - Request appointment modification");
		putMap("S04", "SRM/SRR - Request appointment cancellation");
		putMap("S05", "SRM/SRR - Request appointment discontinuation");
		putMap("S06", "SRM/SRR - Request appointment deletion");
		putMap("S07", "SRM/SRR - Request addition of service/resource on appointment");
		putMap("S08", "SRM/SRR - Request modification of service/resource on appointment");
		putMap("S09", "SRM/SRR - Request cancellation of service/resource on appointment");
		putMap("S10", "SRM/SRR - Request discontinuation of service/resource on appointment");
		putMap("S11", "SRM/SRR - Request deletion of service/resource on appointment");
		putMap("S12", "SIU/ACK - Notification of new appointment booking");
		putMap("S13", "SIU/ACK - Notification of appointment rescheduling");
		putMap("S14", "SIU/ACK - Notification of appointment modification");
		putMap("S15", "SIU/ACK - Notification of appointment cancellation");
		putMap("S16", "SIU/ACK - Notification of appointment discontinuation");
		putMap("S17", "SIU/ACK - Notification of appointment deletion");
		putMap("S18", "SIU/ACK - Notification of addition of service/resource on appointment");
		putMap("S19", "SIU/ACK - Notification of modification of service/resource on appointment");
		putMap("S20", "SIU/ACK - Notification of cancellation of service/resource on appointment");
		putMap("S21", "SIU/ACK - Notification of discontinuation of service/resource on appointment");
		putMap("S22", "SIU/ACK - Notification of deletion of service/resource on appointment");
		putMap("S23", "SIU/ACK - Notification of blocked schedule time slot(s)");
		putMap("S24", "SIU/ACK - Notification of opened (unblocked) schedule time slot(s)");
		putMap("S25", "SQM/SQR - Schedule query message and response");
		putMap("S26", "SIU/ACK Notification that patient did not show up for schedule appointment");
		putMap("T01", "MDM/ACK - Original document notification");
		putMap("T02", "MDM/ACK - Original document notification and content");
		putMap("T03", "MDM/ACK - Document status change notification");
		putMap("T04", "MDM/ACK - Document status change notification and content");
		putMap("T05", "MDM/ACK - Document addendum notification");
		putMap("T06", "MDM/ACK - Document addendum notification and content");
		putMap("T07", "MDM/ACK - Document edit notification");
		putMap("T08", "MDM/ACK - Document edit notification and content");
		putMap("T09", "MDM/ACK - Document replacement notification");
		putMap("T10", "MDM/ACK - Document replacement notification and content");
		putMap("T11", "MDM/ACK - Document cancel notification");
		putMap("T12", "QRY/DOC - Document query");
		putMap("U01", "ESU/ACK - Automated equipment status update");
		putMap("U02", "ESR/ACK - Automated equipment status request");
		putMap("U03", "SSU/ACK - Specimen status update");
		putMap("U04", "SSR/ACK - specimen status request");
		putMap("U05", "INU/ACK  - Automated equipment inventory update");
		putMap("U06", "INR/ACK - Automated equipment inventory request");
		putMap("U07", "EAC/ACK - Automated equipment command");
		putMap("U08", "EAR/ACK - Automated equipment response");
		putMap("U09", "EAN/ACK - Automated equipment notification");
		putMap("U10", "TCU/ACK - Automated equipment test code settings update");
		putMap("U11", "TCR/ACK - Automated equipment test code settings request");
		putMap("U12", "LSU/ACK - Automated equipment log/service update");
		putMap("U13", "LSR/ACK - Automated equipment log/service request");
		putMap("V01", "VXQ - Query for vaccination record");
		putMap("V02", "VXX - Response to vaccination query returning multiple PID matches");
		putMap("V03", "VXR - Vaccination record response");
		putMap("V04", "VXU - Unsolicited vaccination record update");
		putMap("Varies", "MFQ/MFR - Master files query (use event same as asking for e.g., M05 - location)");
		putMap("W01", "ORU - Waveform result, unsolicited transmission of requested information");
		putMap("W02", "QRF - Waveform result, response to query");

	}

}
