package hl7.model.V2_3.message;

import hl7.bean.Structure;
import hl7.bean.group.Group;
import hl7.bean.message.MessageStructure;
import hl7.bean.segment.Segment;

public class ACK extends hl7.model.V2_2.message.ACK{
	public static final String VERSION = "2.3";

	public static int SIZE = 293;
	public Structure[][] components = new Structure[SIZE][];
	public static Structure[] standard = new Structure[SIZE];
	public static boolean[] optional = new boolean[SIZE];
	public static boolean[] repeatable = new boolean[SIZE];
	
	static{
		standard[0]=hl7.pseudo.segment.MSH.CLASS;
		standard[1]=hl7.pseudo.segment.MSH.CLASS;
		standard[2]=hl7.pseudo.segment.MSA.CLASS;
		standard[3]=hl7.pseudo.segment.MSA.CLASS;
		standard[4]=hl7.pseudo.segment.MSH.CLASS;
		standard[5]=hl7.pseudo.segment.MSA.CLASS;
		standard[6]=hl7.pseudo.segment.ERR.CLASS;
		standard[7]=hl7.pseudo.segment.MSH.CLASS;
		standard[8]=hl7.pseudo.segment.MSA.CLASS;
		standard[9]=hl7.pseudo.segment.ERR.CLASS;
		standard[10]=hl7.pseudo.segment.MSH.CLASS;
		standard[11]=hl7.pseudo.segment.MSA.CLASS;
		standard[12]=hl7.pseudo.segment.ERR.CLASS;
		standard[13]=hl7.pseudo.segment.MSH.CLASS;
		standard[14]=hl7.pseudo.segment.MSA.CLASS;
		standard[15]=hl7.pseudo.segment.ERR.CLASS;
		standard[16]=hl7.pseudo.segment.MSH.CLASS;
		standard[17]=hl7.pseudo.segment.MSA.CLASS;
		standard[18]=hl7.pseudo.segment.ERR.CLASS;
		standard[19]=hl7.pseudo.segment.MSH.CLASS;
		standard[20]=hl7.pseudo.segment.MSA.CLASS;
		standard[21]=hl7.pseudo.segment.ERR.CLASS;
		standard[22]=hl7.pseudo.segment.MSH.CLASS;
		standard[23]=hl7.pseudo.segment.MSA.CLASS;
		standard[24]=hl7.pseudo.segment.ERR.CLASS;
		standard[25]=hl7.pseudo.segment.MSH.CLASS;
		standard[26]=hl7.pseudo.segment.MSA.CLASS;
		standard[27]=hl7.pseudo.segment.ERR.CLASS;
		standard[28]=hl7.pseudo.segment.MSH.CLASS;
		standard[29]=hl7.pseudo.segment.MSA.CLASS;
		standard[30]=hl7.pseudo.segment.ERR.CLASS;
		standard[31]=hl7.pseudo.segment.MSH.CLASS;
		standard[32]=hl7.pseudo.segment.MSA.CLASS;
		standard[33]=hl7.pseudo.segment.ERR.CLASS;
		standard[34]=hl7.pseudo.segment.MSH.CLASS;
		standard[35]=hl7.pseudo.segment.MSA.CLASS;
		standard[36]=hl7.pseudo.segment.ERR.CLASS;
		standard[37]=hl7.pseudo.segment.MSH.CLASS;
		standard[38]=hl7.pseudo.segment.MSA.CLASS;
		standard[39]=hl7.pseudo.segment.ERR.CLASS;
		standard[40]=hl7.pseudo.segment.MSH.CLASS;
		standard[41]=hl7.pseudo.segment.MSA.CLASS;
		standard[42]=hl7.pseudo.segment.ERR.CLASS;
		standard[43]=hl7.pseudo.segment.MSH.CLASS;
		standard[44]=hl7.pseudo.segment.MSA.CLASS;
		standard[45]=hl7.pseudo.segment.ERR.CLASS;
		standard[46]=hl7.pseudo.segment.MSH.CLASS;
		standard[47]=hl7.pseudo.segment.MSA.CLASS;
		standard[48]=hl7.pseudo.segment.ERR.CLASS;
		standard[49]=hl7.pseudo.segment.MSH.CLASS;
		standard[50]=hl7.pseudo.segment.MSA.CLASS;
		standard[51]=hl7.pseudo.segment.ERR.CLASS;
		standard[52]=hl7.pseudo.segment.MSH.CLASS;
		standard[53]=hl7.pseudo.segment.MSA.CLASS;
		standard[54]=hl7.pseudo.segment.ERR.CLASS;
		standard[55]=hl7.pseudo.segment.MSH.CLASS;
		standard[56]=hl7.pseudo.segment.MSA.CLASS;
		standard[57]=hl7.pseudo.segment.ERR.CLASS;
		standard[58]=hl7.pseudo.segment.MSH.CLASS;
		standard[59]=hl7.pseudo.segment.MSA.CLASS;
		standard[60]=hl7.pseudo.segment.ERR.CLASS;
		standard[61]=hl7.pseudo.segment.MSH.CLASS;
		standard[62]=hl7.pseudo.segment.MSA.CLASS;
		standard[63]=hl7.pseudo.segment.ERR.CLASS;
		standard[64]=hl7.pseudo.segment.MSH.CLASS;
		standard[65]=hl7.pseudo.segment.MSA.CLASS;
		standard[66]=hl7.pseudo.segment.ERR.CLASS;
		standard[67]=hl7.pseudo.segment.MSH.CLASS;
		standard[68]=hl7.pseudo.segment.MSA.CLASS;
		standard[69]=hl7.pseudo.segment.ERR.CLASS;
		standard[70]=hl7.pseudo.segment.MSH.CLASS;
		standard[71]=hl7.pseudo.segment.MSA.CLASS;
		standard[72]=hl7.pseudo.segment.ERR.CLASS;
		standard[73]=hl7.pseudo.segment.MSH.CLASS;
		standard[74]=hl7.pseudo.segment.MSA.CLASS;
		standard[75]=hl7.pseudo.segment.ERR.CLASS;
		standard[76]=hl7.pseudo.segment.MSH.CLASS;
		standard[77]=hl7.pseudo.segment.MSA.CLASS;
		standard[78]=hl7.pseudo.segment.ERR.CLASS;
		standard[79]=hl7.pseudo.segment.MSH.CLASS;
		standard[80]=hl7.pseudo.segment.MSA.CLASS;
		standard[81]=hl7.pseudo.segment.ERR.CLASS;
		standard[82]=hl7.pseudo.segment.MSH.CLASS;
		standard[83]=hl7.pseudo.segment.MSA.CLASS;
		standard[84]=hl7.pseudo.segment.ERR.CLASS;
		standard[85]=hl7.pseudo.segment.MSH.CLASS;
		standard[86]=hl7.pseudo.segment.MSA.CLASS;
		standard[87]=hl7.pseudo.segment.ERR.CLASS;
		standard[88]=hl7.pseudo.segment.MSH.CLASS;
		standard[89]=hl7.pseudo.segment.MSA.CLASS;
		standard[90]=hl7.pseudo.segment.ERR.CLASS;
		standard[91]=hl7.pseudo.segment.MSH.CLASS;
		standard[92]=hl7.pseudo.segment.MSA.CLASS;
		standard[93]=hl7.pseudo.segment.ERR.CLASS;
		standard[94]=hl7.pseudo.segment.MSH.CLASS;
		standard[95]=hl7.pseudo.segment.MSA.CLASS;
		standard[96]=hl7.pseudo.segment.ERR.CLASS;
		standard[97]=hl7.pseudo.segment.MSH.CLASS;
		standard[98]=hl7.pseudo.segment.MSA.CLASS;
		standard[99]=hl7.pseudo.segment.ERR.CLASS;
		standard[100]=hl7.pseudo.segment.MSH.CLASS;
		standard[101]=hl7.pseudo.segment.MSA.CLASS;
		standard[102]=hl7.pseudo.segment.ERR.CLASS;
		standard[103]=hl7.pseudo.segment.MSH.CLASS;
		standard[104]=hl7.pseudo.segment.MSA.CLASS;
		standard[105]=hl7.pseudo.segment.ERR.CLASS;
		standard[106]=hl7.pseudo.segment.MSH.CLASS;
		standard[107]=hl7.pseudo.segment.MSA.CLASS;
		standard[108]=hl7.pseudo.segment.ERR.CLASS;
		standard[109]=hl7.pseudo.segment.MSH.CLASS;
		standard[110]=hl7.pseudo.segment.MSA.CLASS;
		standard[111]=hl7.pseudo.segment.ERR.CLASS;
		standard[112]=hl7.pseudo.segment.MSH.CLASS;
		standard[113]=hl7.pseudo.segment.MSA.CLASS;
		standard[114]=hl7.pseudo.segment.ERR.CLASS;
		standard[115]=hl7.pseudo.segment.MSH.CLASS;
		standard[116]=hl7.pseudo.segment.MSA.CLASS;
		standard[117]=hl7.pseudo.segment.ERR.CLASS;
		standard[118]=hl7.pseudo.segment.MSH.CLASS;
		standard[119]=hl7.pseudo.segment.MSA.CLASS;
		standard[120]=hl7.pseudo.segment.ERR.CLASS;
		standard[121]=hl7.pseudo.segment.MSH.CLASS;
		standard[122]=hl7.pseudo.segment.MSA.CLASS;
		standard[123]=hl7.pseudo.segment.ERR.CLASS;
		standard[124]=hl7.pseudo.segment.MSH.CLASS;
		standard[125]=hl7.pseudo.segment.MSA.CLASS;
		standard[126]=hl7.pseudo.segment.ERR.CLASS;
		standard[127]=hl7.pseudo.segment.MSH.CLASS;
		standard[128]=hl7.pseudo.segment.MSA.CLASS;
		standard[129]=hl7.pseudo.segment.ERR.CLASS;
		standard[130]=hl7.pseudo.segment.MSH.CLASS;
		standard[131]=hl7.pseudo.segment.MSA.CLASS;
		standard[132]=hl7.pseudo.segment.ERR.CLASS;
		standard[133]=hl7.pseudo.segment.MSH.CLASS;
		standard[134]=hl7.pseudo.segment.MSA.CLASS;
		standard[135]=hl7.pseudo.segment.ERR.CLASS;
		standard[136]=hl7.pseudo.segment.MSH.CLASS;
		standard[137]=hl7.pseudo.segment.MSA.CLASS;
		standard[138]=hl7.pseudo.segment.ERR.CLASS;
		standard[139]=hl7.pseudo.segment.MSH.CLASS;
		standard[140]=hl7.pseudo.segment.MSA.CLASS;
		standard[141]=hl7.pseudo.segment.ERR.CLASS;
		standard[142]=hl7.pseudo.segment.MSH.CLASS;
		standard[143]=hl7.pseudo.segment.MSA.CLASS;
		standard[144]=hl7.pseudo.segment.ERR.CLASS;
		standard[145]=hl7.pseudo.segment.MSH.CLASS;
		standard[146]=hl7.pseudo.segment.MSA.CLASS;
		standard[147]=hl7.pseudo.segment.ERR.CLASS;
		standard[148]=hl7.pseudo.segment.MSH.CLASS;
		standard[149]=hl7.pseudo.segment.MSA.CLASS;
		standard[150]=hl7.pseudo.segment.ERR.CLASS;
		standard[151]=hl7.pseudo.segment.MSH.CLASS;
		standard[152]=hl7.pseudo.segment.MSA.CLASS;
		standard[153]=hl7.pseudo.segment.ERR.CLASS;
		standard[154]=hl7.pseudo.segment.MSH.CLASS;
		standard[155]=hl7.pseudo.segment.MSA.CLASS;
		standard[156]=hl7.pseudo.segment.ERR.CLASS;
		standard[157]=hl7.pseudo.segment.MSH.CLASS;
		standard[158]=hl7.pseudo.segment.MSA.CLASS;
		standard[159]=hl7.pseudo.segment.ERR.CLASS;
		standard[160]=hl7.pseudo.segment.MSH.CLASS;
		standard[161]=hl7.pseudo.segment.MSA.CLASS;
		standard[162]=hl7.pseudo.segment.ERR.CLASS;
		standard[163]=hl7.pseudo.segment.MSH.CLASS;
		standard[164]=hl7.pseudo.segment.MSA.CLASS;
		standard[165]=hl7.pseudo.segment.ERR.CLASS;
		standard[166]=hl7.pseudo.segment.MSH.CLASS;
		standard[167]=hl7.pseudo.segment.MSA.CLASS;
		standard[168]=hl7.pseudo.segment.ERR.CLASS;
		standard[169]=hl7.pseudo.segment.MSH.CLASS;
		standard[170]=hl7.pseudo.segment.MSA.CLASS;
		standard[171]=hl7.pseudo.segment.ERR.CLASS;
		standard[172]=hl7.pseudo.segment.MSH.CLASS;
		standard[173]=hl7.pseudo.segment.MSA.CLASS;
		standard[174]=hl7.pseudo.segment.ERR.CLASS;
		standard[175]=hl7.pseudo.segment.MSH.CLASS;
		standard[176]=hl7.pseudo.segment.MSA.CLASS;
		standard[177]=hl7.pseudo.segment.ERR.CLASS;
		standard[178]=hl7.pseudo.segment.MSH.CLASS;
		standard[179]=hl7.pseudo.segment.MSA.CLASS;
		standard[180]=hl7.pseudo.segment.ERR.CLASS;
		standard[181]=hl7.pseudo.segment.MSH.CLASS;
		standard[182]=hl7.pseudo.segment.MSA.CLASS;
		standard[183]=hl7.pseudo.segment.ERR.CLASS;
		standard[184]=hl7.pseudo.segment.MSH.CLASS;
		standard[185]=hl7.pseudo.segment.MSA.CLASS;
		standard[186]=hl7.pseudo.segment.ERR.CLASS;
		standard[187]=hl7.pseudo.segment.MSH.CLASS;
		standard[188]=hl7.pseudo.segment.MSA.CLASS;
		standard[189]=hl7.pseudo.segment.ERR.CLASS;
		standard[190]=hl7.pseudo.segment.MSH.CLASS;
		standard[191]=hl7.pseudo.segment.MSA.CLASS;
		standard[192]=hl7.pseudo.segment.ERR.CLASS;
		standard[193]=hl7.pseudo.segment.MSH.CLASS;
		standard[194]=hl7.pseudo.segment.MSA.CLASS;
		standard[195]=hl7.pseudo.segment.ERR.CLASS;
		standard[196]=hl7.pseudo.segment.MSH.CLASS;
		standard[197]=hl7.pseudo.segment.MSA.CLASS;
		standard[198]=hl7.pseudo.segment.ERR.CLASS;
		standard[199]=hl7.pseudo.segment.MSH.CLASS;
		standard[200]=hl7.pseudo.segment.MSA.CLASS;
		standard[201]=hl7.pseudo.segment.ERR.CLASS;
		standard[202]=hl7.pseudo.segment.MSH.CLASS;
		standard[203]=hl7.pseudo.segment.MSA.CLASS;
		standard[204]=hl7.pseudo.segment.ERR.CLASS;
		standard[205]=hl7.pseudo.segment.MSH.CLASS;
		standard[206]=hl7.pseudo.segment.MSA.CLASS;
		standard[207]=hl7.pseudo.segment.ERR.CLASS;
		standard[208]=hl7.pseudo.segment.MSH.CLASS;
		standard[209]=hl7.pseudo.segment.MSA.CLASS;
		standard[210]=hl7.pseudo.segment.ERR.CLASS;
		standard[211]=hl7.pseudo.segment.MSH.CLASS;
		standard[212]=hl7.pseudo.segment.MSA.CLASS;
		standard[213]=hl7.pseudo.segment.ERR.CLASS;
		standard[214]=hl7.pseudo.segment.MSH.CLASS;
		standard[215]=hl7.pseudo.segment.MSA.CLASS;
		standard[216]=hl7.pseudo.segment.MSH.CLASS;
		standard[217]=hl7.pseudo.segment.MSA.CLASS;
		standard[218]=hl7.pseudo.segment.ERR.CLASS;
		standard[219]=hl7.pseudo.segment.MSH.CLASS;
		standard[220]=hl7.pseudo.segment.MSA.CLASS;
		standard[221]=hl7.pseudo.segment.ERR.CLASS;
		standard[222]=hl7.pseudo.segment.MSH.CLASS;
		standard[223]=hl7.pseudo.segment.MSA.CLASS;
		standard[224]=hl7.pseudo.segment.ERR.CLASS;
		standard[225]=hl7.pseudo.segment.MSH.CLASS;
		standard[226]=hl7.pseudo.segment.MSA.CLASS;
		standard[227]=hl7.pseudo.segment.ERR.CLASS;
		standard[228]=hl7.pseudo.segment.MSH.CLASS;
		standard[229]=hl7.pseudo.segment.MSA.CLASS;
		standard[230]=hl7.pseudo.segment.ERR.CLASS;
		standard[231]=hl7.pseudo.segment.MSH.CLASS;
		standard[232]=hl7.pseudo.segment.MSA.CLASS;
		standard[233]=hl7.pseudo.segment.ERR.CLASS;
		standard[234]=hl7.pseudo.segment.MSH.CLASS;
		standard[235]=hl7.pseudo.segment.MSA.CLASS;
		standard[236]=hl7.pseudo.segment.ERR.CLASS;
		standard[237]=hl7.pseudo.segment.MSH.CLASS;
		standard[238]=hl7.pseudo.segment.MSA.CLASS;
		standard[239]=hl7.pseudo.segment.ERR.CLASS;
		standard[240]=hl7.pseudo.segment.MSH.CLASS;
		standard[241]=hl7.pseudo.segment.MSA.CLASS;
		standard[242]=hl7.pseudo.segment.ERR.CLASS;
		standard[243]=hl7.pseudo.segment.MSH.CLASS;
		standard[244]=hl7.pseudo.segment.MSA.CLASS;
		standard[245]=hl7.pseudo.segment.ERR.CLASS;
		standard[246]=hl7.pseudo.segment.MSH.CLASS;
		standard[247]=hl7.pseudo.segment.MSA.CLASS;
		standard[248]=hl7.pseudo.segment.ERR.CLASS;
		standard[249]=hl7.pseudo.segment.MSH.CLASS;
		standard[250]=hl7.pseudo.segment.MSA.CLASS;
		standard[251]=hl7.pseudo.segment.ERR.CLASS;
		standard[252]=hl7.pseudo.segment.MSH.CLASS;
		standard[253]=hl7.pseudo.segment.MSA.CLASS;
		standard[254]=hl7.pseudo.segment.ERR.CLASS;
		standard[255]=hl7.pseudo.segment.MSH.CLASS;
		standard[256]=hl7.pseudo.segment.MSA.CLASS;
		standard[257]=hl7.pseudo.segment.ERR.CLASS;
		standard[258]=hl7.pseudo.segment.MSH.CLASS;
		standard[259]=hl7.pseudo.segment.MSA.CLASS;
		standard[260]=hl7.pseudo.segment.ERR.CLASS;
		standard[261]=hl7.pseudo.segment.MSH.CLASS;
		standard[262]=hl7.pseudo.segment.MSA.CLASS;
		standard[263]=hl7.pseudo.segment.ERR.CLASS;
		standard[264]=hl7.pseudo.segment.MSH.CLASS;
		standard[265]=hl7.pseudo.segment.MSA.CLASS;
		standard[266]=hl7.pseudo.segment.ERR.CLASS;
		standard[267]=hl7.pseudo.segment.MSH.CLASS;
		standard[268]=hl7.pseudo.segment.MSA.CLASS;
		standard[269]=hl7.pseudo.segment.ERR.CLASS;
		standard[270]=hl7.pseudo.segment.MSH.CLASS;
		standard[271]=hl7.pseudo.segment.MSA.CLASS;
		standard[272]=hl7.pseudo.segment.ERR.CLASS;
		standard[273]=hl7.pseudo.segment.MSH.CLASS;
		standard[274]=hl7.pseudo.segment.MSA.CLASS;
		standard[275]=hl7.pseudo.segment.ERR.CLASS;
		standard[276]=hl7.pseudo.segment.MSH.CLASS;
		standard[277]=hl7.pseudo.segment.MSA.CLASS;
		standard[278]=hl7.pseudo.segment.ERR.CLASS;
		standard[279]=hl7.pseudo.segment.MSH.CLASS;
		standard[280]=hl7.pseudo.segment.MSA.CLASS;
		standard[281]=hl7.pseudo.segment.ERR.CLASS;
		standard[282]=hl7.pseudo.segment.MSH.CLASS;
		standard[283]=hl7.pseudo.segment.MSA.CLASS;
		standard[284]=hl7.pseudo.segment.ERR.CLASS;
		standard[285]=hl7.pseudo.segment.MSH.CLASS;
		standard[286]=hl7.pseudo.segment.MSA.CLASS;
		standard[287]=hl7.pseudo.segment.ERR.CLASS;
		standard[288]=hl7.pseudo.segment.MSH.CLASS;
		standard[289]=hl7.pseudo.segment.MSA.CLASS;
		standard[290]=hl7.pseudo.segment.ERR.CLASS;
		standard[291]=hl7.pseudo.segment.ERR.CLASS;
		standard[292]=hl7.pseudo.segment.ERR.CLASS;
	
		optional[0]=false;
		optional[1]=false;
		optional[2]=false;
		optional[3]=false;
		optional[4]=false;
		optional[5]=false;
		optional[6]=false;
		optional[7]=false;
		optional[8]=false;
		optional[9]=false;
		optional[10]=false;
		optional[11]=false;
		optional[12]=false;
		optional[13]=false;
		optional[14]=false;
		optional[15]=false;
		optional[16]=false;
		optional[17]=false;
		optional[18]=false;
		optional[19]=false;
		optional[20]=false;
		optional[21]=false;
		optional[22]=false;
		optional[23]=false;
		optional[24]=false;
		optional[25]=false;
		optional[26]=false;
		optional[27]=false;
		optional[28]=false;
		optional[29]=false;
		optional[30]=false;
		optional[31]=false;
		optional[32]=false;
		optional[33]=false;
		optional[34]=false;
		optional[35]=false;
		optional[36]=false;
		optional[37]=false;
		optional[38]=false;
		optional[39]=false;
		optional[40]=false;
		optional[41]=false;
		optional[42]=false;
		optional[43]=false;
		optional[44]=false;
		optional[45]=false;
		optional[46]=false;
		optional[47]=false;
		optional[48]=false;
		optional[49]=false;
		optional[50]=false;
		optional[51]=false;
		optional[52]=false;
		optional[53]=false;
		optional[54]=false;
		optional[55]=false;
		optional[56]=false;
		optional[57]=false;
		optional[58]=false;
		optional[59]=false;
		optional[60]=false;
		optional[61]=false;
		optional[62]=false;
		optional[63]=false;
		optional[64]=false;
		optional[65]=false;
		optional[66]=false;
		optional[67]=false;
		optional[68]=false;
		optional[69]=false;
		optional[70]=false;
		optional[71]=false;
		optional[72]=false;
		optional[73]=false;
		optional[74]=false;
		optional[75]=false;
		optional[76]=false;
		optional[77]=false;
		optional[78]=false;
		optional[79]=false;
		optional[80]=false;
		optional[81]=false;
		optional[82]=false;
		optional[83]=false;
		optional[84]=false;
		optional[85]=false;
		optional[86]=false;
		optional[87]=false;
		optional[88]=false;
		optional[89]=false;
		optional[90]=false;
		optional[91]=false;
		optional[92]=false;
		optional[93]=false;
		optional[94]=false;
		optional[95]=false;
		optional[96]=false;
		optional[97]=false;
		optional[98]=false;
		optional[99]=false;
		optional[100]=false;
		optional[101]=false;
		optional[102]=false;
		optional[103]=false;
		optional[104]=false;
		optional[105]=false;
		optional[106]=false;
		optional[107]=false;
		optional[108]=false;
		optional[109]=false;
		optional[110]=false;
		optional[111]=false;
		optional[112]=false;
		optional[113]=false;
		optional[114]=false;
		optional[115]=false;
		optional[116]=false;
		optional[117]=false;
		optional[118]=false;
		optional[119]=false;
		optional[120]=false;
		optional[121]=false;
		optional[122]=false;
		optional[123]=false;
		optional[124]=false;
		optional[125]=false;
		optional[126]=false;
		optional[127]=false;
		optional[128]=false;
		optional[129]=false;
		optional[130]=false;
		optional[131]=false;
		optional[132]=false;
		optional[133]=false;
		optional[134]=false;
		optional[135]=false;
		optional[136]=false;
		optional[137]=false;
		optional[138]=false;
		optional[139]=false;
		optional[140]=false;
		optional[141]=false;
		optional[142]=false;
		optional[143]=false;
		optional[144]=false;
		optional[145]=false;
		optional[146]=false;
		optional[147]=false;
		optional[148]=false;
		optional[149]=false;
		optional[150]=false;
		optional[151]=false;
		optional[152]=false;
		optional[153]=false;
		optional[154]=false;
		optional[155]=false;
		optional[156]=false;
		optional[157]=false;
		optional[158]=false;
		optional[159]=false;
		optional[160]=false;
		optional[161]=false;
		optional[162]=false;
		optional[163]=false;
		optional[164]=false;
		optional[165]=false;
		optional[166]=false;
		optional[167]=false;
		optional[168]=false;
		optional[169]=false;
		optional[170]=false;
		optional[171]=false;
		optional[172]=false;
		optional[173]=false;
		optional[174]=false;
		optional[175]=false;
		optional[176]=false;
		optional[177]=false;
		optional[178]=false;
		optional[179]=false;
		optional[180]=false;
		optional[181]=false;
		optional[182]=false;
		optional[183]=false;
		optional[184]=false;
		optional[185]=false;
		optional[186]=false;
		optional[187]=false;
		optional[188]=false;
		optional[189]=false;
		optional[190]=false;
		optional[191]=false;
		optional[192]=false;
		optional[193]=false;
		optional[194]=false;
		optional[195]=false;
		optional[196]=false;
		optional[197]=false;
		optional[198]=false;
		optional[199]=false;
		optional[200]=false;
		optional[201]=false;
		optional[202]=false;
		optional[203]=false;
		optional[204]=false;
		optional[205]=false;
		optional[206]=false;
		optional[207]=false;
		optional[208]=false;
		optional[209]=false;
		optional[210]=false;
		optional[211]=false;
		optional[212]=false;
		optional[213]=false;
		optional[214]=false;
		optional[215]=false;
		optional[216]=false;
		optional[217]=false;
		optional[218]=false;
		optional[219]=false;
		optional[220]=false;
		optional[221]=false;
		optional[222]=false;
		optional[223]=false;
		optional[224]=false;
		optional[225]=false;
		optional[226]=false;
		optional[227]=false;
		optional[228]=false;
		optional[229]=false;
		optional[230]=false;
		optional[231]=false;
		optional[232]=false;
		optional[233]=false;
		optional[234]=false;
		optional[235]=false;
		optional[236]=false;
		optional[237]=false;
		optional[238]=false;
		optional[239]=false;
		optional[240]=false;
		optional[241]=false;
		optional[242]=false;
		optional[243]=false;
		optional[244]=false;
		optional[245]=false;
		optional[246]=false;
		optional[247]=false;
		optional[248]=false;
		optional[249]=false;
		optional[250]=false;
		optional[251]=false;
		optional[252]=false;
		optional[253]=false;
		optional[254]=false;
		optional[255]=false;
		optional[256]=false;
		optional[257]=false;
		optional[258]=false;
		optional[259]=false;
		optional[260]=false;
		optional[261]=false;
		optional[262]=false;
		optional[263]=false;
		optional[264]=false;
		optional[265]=false;
		optional[266]=false;
		optional[267]=false;
		optional[268]=false;
		optional[269]=false;
		optional[270]=false;
		optional[271]=false;
		optional[272]=false;
		optional[273]=false;
		optional[274]=false;
		optional[275]=false;
		optional[276]=false;
		optional[277]=false;
		optional[278]=false;
		optional[279]=false;
		optional[280]=false;
		optional[281]=false;
		optional[282]=false;
		optional[283]=false;
		optional[284]=false;
		optional[285]=false;
		optional[286]=false;
		optional[287]=false;
		optional[288]=false;
		optional[289]=false;
		optional[290]=false;
		optional[291]=false;
		optional[292]=false;
		
		repeatable [0]=false;
		repeatable [1]=false;
		repeatable [2]=false;
		repeatable [3]=false;
		repeatable [4]=false;
		repeatable [5]=false;
		repeatable [6]=false;
		repeatable [7]=false;
		repeatable [8]=false;
		repeatable [9]=false;
		repeatable [10]=false;
		repeatable [11]=false;
		repeatable [12]=false;
		repeatable [13]=false;
		repeatable [14]=false;
		repeatable [15]=false;
		repeatable [16]=false;
		repeatable [17]=false;
		repeatable [18]=false;
		repeatable [19]=false;
		repeatable [20]=false;
		repeatable [21]=false;
		repeatable [22]=false;
		repeatable [23]=false;
		repeatable [24]=false;
		repeatable [25]=false;
		repeatable [26]=false;
		repeatable [27]=false;
		repeatable [28]=false;
		repeatable [29]=false;
		repeatable [30]=false;
		repeatable [31]=false;
		repeatable [32]=false;
		repeatable [33]=false;
		repeatable [34]=false;
		repeatable [35]=false;
		repeatable [36]=false;
		repeatable [37]=false;
		repeatable [38]=false;
		repeatable [39]=false;
		repeatable [40]=false;
		repeatable [41]=false;
		repeatable [42]=false;
		repeatable [43]=false;
		repeatable [44]=false;
		repeatable [45]=false;
		repeatable [46]=false;
		repeatable [47]=false;
		repeatable [48]=false;
		repeatable [49]=false;
		repeatable [50]=false;
		repeatable [51]=false;
		repeatable [52]=false;
		repeatable [53]=false;
		repeatable [54]=false;
		repeatable [55]=false;
		repeatable [56]=false;
		repeatable [57]=false;
		repeatable [58]=false;
		repeatable [59]=false;
		repeatable [60]=false;
		repeatable [61]=false;
		repeatable [62]=false;
		repeatable [63]=false;
		repeatable [64]=false;
		repeatable [65]=false;
		repeatable [66]=false;
		repeatable [67]=false;
		repeatable [68]=false;
		repeatable [69]=false;
		repeatable [70]=false;
		repeatable [71]=false;
		repeatable [72]=false;
		repeatable [73]=false;
		repeatable [74]=false;
		repeatable [75]=false;
		repeatable [76]=false;
		repeatable [77]=false;
		repeatable [78]=false;
		repeatable [79]=false;
		repeatable [80]=false;
		repeatable [81]=false;
		repeatable [82]=false;
		repeatable [83]=false;
		repeatable [84]=false;
		repeatable [85]=false;
		repeatable [86]=false;
		repeatable [87]=false;
		repeatable [88]=false;
		repeatable [89]=false;
		repeatable [90]=false;
		repeatable [91]=false;
		repeatable [92]=false;
		repeatable [93]=false;
		repeatable [94]=false;
		repeatable [95]=false;
		repeatable [96]=false;
		repeatable [97]=false;
		repeatable [98]=false;
		repeatable [99]=false;
		repeatable [100]=false;
		repeatable [101]=false;
		repeatable [102]=false;
		repeatable [103]=false;
		repeatable [104]=false;
		repeatable [105]=false;
		repeatable [106]=false;
		repeatable [107]=false;
		repeatable [108]=false;
		repeatable [109]=false;
		repeatable [110]=false;
		repeatable [111]=false;
		repeatable [112]=false;
		repeatable [113]=false;
		repeatable [114]=false;
		repeatable [115]=false;
		repeatable [116]=false;
		repeatable [117]=false;
		repeatable [118]=false;
		repeatable [119]=false;
		repeatable [120]=false;
		repeatable [121]=false;
		repeatable [122]=false;
		repeatable [123]=false;
		repeatable [124]=false;
		repeatable [125]=false;
		repeatable [126]=false;
		repeatable [127]=false;
		repeatable [128]=false;
		repeatable [129]=false;
		repeatable [130]=false;
		repeatable [131]=false;
		repeatable [132]=false;
		repeatable [133]=false;
		repeatable [134]=false;
		repeatable [135]=false;
		repeatable [136]=false;
		repeatable [137]=false;
		repeatable [138]=false;
		repeatable [139]=false;
		repeatable [140]=false;
		repeatable [141]=false;
		repeatable [142]=false;
		repeatable [143]=false;
		repeatable [144]=false;
		repeatable [145]=false;
		repeatable [146]=false;
		repeatable [147]=false;
		repeatable [148]=false;
		repeatable [149]=false;
		repeatable [150]=false;
		repeatable [151]=false;
		repeatable [152]=false;
		repeatable [153]=false;
		repeatable [154]=false;
		repeatable [155]=false;
		repeatable [156]=false;
		repeatable [157]=false;
		repeatable [158]=false;
		repeatable [159]=false;
		repeatable [160]=false;
		repeatable [161]=false;
		repeatable [162]=false;
		repeatable [163]=false;
		repeatable [164]=false;
		repeatable [165]=false;
		repeatable [166]=false;
		repeatable [167]=false;
		repeatable [168]=false;
		repeatable [169]=false;
		repeatable [170]=false;
		repeatable [171]=false;
		repeatable [172]=false;
		repeatable [173]=false;
		repeatable [174]=false;
		repeatable [175]=false;
		repeatable [176]=false;
		repeatable [177]=false;
		repeatable [178]=false;
		repeatable [179]=false;
		repeatable [180]=false;
		repeatable [181]=false;
		repeatable [182]=false;
		repeatable [183]=false;
		repeatable [184]=false;
		repeatable [185]=false;
		repeatable [186]=false;
		repeatable [187]=false;
		repeatable [188]=false;
		repeatable [189]=false;
		repeatable [190]=false;
		repeatable [191]=false;
		repeatable [192]=false;
		repeatable [193]=false;
		repeatable [194]=false;
		repeatable [195]=false;
		repeatable [196]=false;
		repeatable [197]=false;
		repeatable [198]=false;
		repeatable [199]=false;
		repeatable [200]=false;
		repeatable [201]=false;
		repeatable [202]=false;
		repeatable [203]=false;
		repeatable [204]=false;
		repeatable [205]=false;
		repeatable [206]=false;
		repeatable [207]=false;
		repeatable [208]=false;
		repeatable [209]=false;
		repeatable [210]=false;
		repeatable [211]=false;
		repeatable [212]=false;
		repeatable [213]=false;
		repeatable [214]=false;
		repeatable [215]=false;
		repeatable [216]=false;
		repeatable [217]=false;
		repeatable [218]=false;
		repeatable [219]=false;
		repeatable [220]=false;
		repeatable [221]=false;
		repeatable [222]=false;
		repeatable [223]=false;
		repeatable [224]=false;
		repeatable [225]=false;
		repeatable [226]=false;
		repeatable [227]=false;
		repeatable [228]=false;
		repeatable [229]=false;
		repeatable [230]=false;
		repeatable [231]=false;
		repeatable [232]=false;
		repeatable [233]=false;
		repeatable [234]=false;
		repeatable [235]=false;
		repeatable [236]=false;
		repeatable [237]=false;
		repeatable [238]=false;
		repeatable [239]=false;
		repeatable [240]=false;
		repeatable [241]=false;
		repeatable [242]=false;
		repeatable [243]=false;
		repeatable [244]=false;
		repeatable [245]=false;
		repeatable [246]=false;
		repeatable [247]=false;
		repeatable [248]=false;
		repeatable [249]=false;
		repeatable [250]=false;
		repeatable [251]=false;
		repeatable [252]=false;
		repeatable [253]=false;
		repeatable [254]=false;
		repeatable [255]=false;
		repeatable [256]=false;
		repeatable [257]=false;
		repeatable [258]=false;
		repeatable [259]=false;
		repeatable [260]=false;
		repeatable [261]=false;
		repeatable [262]=false;
		repeatable [263]=false;
		repeatable [264]=false;
		repeatable [265]=false;
		repeatable [266]=false;
		repeatable [267]=false;
		repeatable [268]=false;
		repeatable [269]=false;
		repeatable [270]=false;
		repeatable [271]=false;
		repeatable [272]=false;
		repeatable [273]=false;
		repeatable [274]=false;
		repeatable [275]=false;
		repeatable [276]=false;
		repeatable [277]=false;
		repeatable [278]=false;
		repeatable [279]=false;
		repeatable [280]=false;
		repeatable [281]=false;
		repeatable [282]=false;
		repeatable [283]=false;
		repeatable [284]=false;
		repeatable [285]=false;
		repeatable [286]=false;
		repeatable [287]=false;
		repeatable [288]=false;
		repeatable [289]=false;
		repeatable [290]=false;
		repeatable [291]=false;
		repeatable [292]=false;
	}
	
	public void setVersion(String setVersion) {
		super.setVersion(setVersion);
		this.setVersion = setVersion; 
		for(int i=0; i<components.length; i++){
			Structure[] structures = components[i];
			for(int c=0; structures!=null&&c<structures.length; c++){
				Structure structure = components[i][c];
				structure.setVersion(setVersion);
			}
		}
	}

	public void originalVersion(String originalVersion) {
		super.originalVersion(originalVersion);
		this.originalVersion = originalVersion; 
		for(int i=0; i<components.length; i++){
			Structure[] structures = components[i];
			for(int c=0; structures!=null&&c<structures.length; c++){
				Structure structure = components[i][c];
				structure.originalVersion(originalVersion);
			}
		}
	}
	public Structure[][] getComponents(){
		if(setVersion.equals(VERSION)){
			return components;
		}else{
			return super.getComponents();
		}
	}
	
	private boolean compiled = false;	//최초 컴파일 여부 확인
	public void decode(String message) throws Exception {
		if(MessageStructure.getVersionCode(originalVersion)<MessageStructure.getVersionCode(VERSION)){
			super.decode(message);
			
		}else{
			compiled = true;	//최초 컴파일 여부 확인
			
			char separator = MessageStructure.SEGMENT_TERMINATOR;
			String[] comps = divide(message, separator);
			if(comps==null) return;

			int[] index = new int[2];
			while(index[0]<comps.length && index[1]<SIZE){
				decode(components, originalVersion, setVersion, VERSION, index, comps);
			}
		}
	}
	
	private void decode(Structure[][] components, String originalVersion, String setVersion, String VERSION, int[] index, String[] comps) throws Exception{
		Structure structure = standard[index[1]];
		String comp = comps[index[0]];
		String segmentType = comp.substring(0, 3);
		if(structure instanceof Segment){	//Segment일 때
			String standardType = structure.getType();
			if(segmentType.equals(standardType)){		//표준과 Type이 동일한가?
				Segment segment = ((Segment)structure).cloneClass(originalVersion, setVersion);
				segment.originalVersion(originalVersion);
				segment.decode(comp);
				addStructure(components, segment, index[1]);
				index[0]++;	//다음 comp 처리
			}else{
				index[1]++;	//다음 Segment와 비교
			}
		}else if(structure instanceof Group){
			Group group = (Group)structure;
			int stdIndex = group.indexStandard(segmentType);
			if(stdIndex<0){
				index[1]++;
			}else{
				int groupIndex = index[1];
				
				boolean needsNewGroup = group.needsNewGroup(segmentType, components[index[1]]); 
				if(needsNewGroup){
					Group newGroup = group.cloneClass(originalVersion, setVersion);
					newGroup.originalVersion(originalVersion);
					newGroup.decode(originalVersion, setVersion, VERSION, index, index[1], comps);
					addStructure(components, newGroup, index[1]);
				}else{
					group.decode(originalVersion, setVersion, VERSION, index, index[1], comps);
				}
				
				index[1] = groupIndex;
			}
		}
	}
	
	public static void addStructure(Structure[][] components, Structure structure, int index){
		if(components.length<=index) return;
		Structure[] comps = components[index];
		Structure[] newComps;
		newComps = (comps==null)?new Structure[1]:new Structure[comps.length+1];
		for(int i=0; i<newComps.length-1; i++) newComps[i]=comps[i];
		newComps[newComps.length-1] = structure;
		components[index] = newComps;
	}
	
	
	/* -----------------------------------------------------------------
	 * 이전 버전으로 매핑 components:구버전, subComponents:신버전
	 * 신버전 메시지-->구버전 파서(상위호환)
	 * -----------------------------------------------------------------
	 */
	public static void backward(Structure[][] components, Structure[][] subComponents, String originalVersion, String setVersion) throws Exception{
		components[0] = subComponents[0];
		components[1] = subComponents[1];
		components[2] = subComponents[2];
		components[3] = subComponents[3];
		components[4] = subComponents[4];
		components[5] = subComponents[5];
		components[6] = subComponents[6];
		components[7] = subComponents[7];
		components[8] = subComponents[8];
		components[9] = subComponents[9];
		components[10] = subComponents[10];
		components[11] = subComponents[11];
		components[12] = subComponents[12];
		components[13] = subComponents[13];
		components[14] = subComponents[14];
		components[15] = subComponents[15];
		components[16] = subComponents[16];
		components[17] = subComponents[17];
		components[18] = subComponents[18];
		components[19] = subComponents[19];
		components[20] = subComponents[20];
		components[21] = subComponents[21];
		components[22] = subComponents[22];
		components[23] = subComponents[23];
		components[24] = subComponents[24];
		components[25] = subComponents[25];
		components[26] = subComponents[26];
		components[27] = subComponents[27];
		components[28] = subComponents[28];
		components[29] = subComponents[29];
		components[30] = subComponents[30];
		components[31] = subComponents[31];
		components[32] = subComponents[32];
		components[33] = subComponents[33];
		components[34] = subComponents[34];
		components[35] = subComponents[35];
		components[36] = subComponents[36];
		components[37] = subComponents[37];
		components[38] = subComponents[38];
		components[39] = subComponents[39];
		components[40] = subComponents[40];
		components[41] = subComponents[41];
		components[42] = subComponents[42];
		components[43] = subComponents[43];
		components[44] = subComponents[44];
		components[45] = subComponents[45];
		components[46] = subComponents[46];
		components[47] = subComponents[47];
		components[48] = subComponents[48];
		components[49] = subComponents[49];
		components[50] = subComponents[50];
		components[51] = subComponents[51];
		components[52] = subComponents[52];
		components[53] = subComponents[53];
		components[54] = subComponents[54];
		components[55] = subComponents[55];
		components[56] = subComponents[56];
		components[57] = subComponents[57];
		components[58] = subComponents[58];
		components[59] = subComponents[59];
		components[60] = subComponents[60];
		components[61] = subComponents[61];
		components[62] = subComponents[62];
		components[63] = subComponents[63];
		components[64] = subComponents[64];
		components[65] = subComponents[65];
		components[66] = subComponents[66];
		components[67] = subComponents[67];
		components[68] = subComponents[68];
		components[69] = subComponents[69];
		components[70] = subComponents[70];
		components[71] = subComponents[71];
		components[72] = subComponents[72];
		components[73] = subComponents[73];
		components[74] = subComponents[74];
		components[75] = subComponents[75];
		components[76] = subComponents[76];
		components[77] = subComponents[77];
		components[78] = subComponents[78];
		components[79] = subComponents[79];
		components[80] = subComponents[80];
		components[81] = subComponents[81];
		components[82] = subComponents[82];
		components[83] = subComponents[83];
		components[84] = subComponents[84];
		components[85] = subComponents[85];
		components[86] = subComponents[86];
		components[87] = subComponents[87];
		components[88] = subComponents[88];
		components[89] = subComponents[89];
		components[90] = subComponents[90];
		components[91] = subComponents[91];
		components[92] = subComponents[92];
		components[93] = subComponents[93];
		components[94] = subComponents[94];
		components[95] = subComponents[95];
		components[96] = subComponents[96];
		components[97] = subComponents[97];
		components[98] = subComponents[98];
		components[99] = subComponents[99];
		components[100] = subComponents[100];
		components[101] = subComponents[101];
		components[102] = subComponents[102];
		components[103] = subComponents[103];
		components[104] = subComponents[104];
		components[105] = subComponents[105];
		components[106] = subComponents[106];
		components[107] = subComponents[107];
		components[108] = subComponents[108];
		components[109] = subComponents[109];
		components[110] = subComponents[110];
		components[111] = subComponents[111];
		components[112] = subComponents[112];
		components[113] = subComponents[113];
		components[114] = subComponents[114];
		components[115] = subComponents[115];
		components[116] = subComponents[116];
		components[117] = subComponents[117];
		components[118] = subComponents[118];
		components[119] = subComponents[119];
		components[120] = subComponents[120];
		components[121] = subComponents[121];
		components[122] = subComponents[122];
		components[123] = subComponents[123];
		components[124] = subComponents[124];
		components[125] = subComponents[125];
		components[126] = subComponents[126];
		components[127] = subComponents[127];
		components[128] = subComponents[128];
		components[129] = subComponents[129];
		components[130] = subComponents[130];
		components[131] = subComponents[131];
		components[132] = subComponents[132];
		components[133] = subComponents[133];
		components[134] = subComponents[134];
		components[135] = subComponents[135];
		components[136] = subComponents[136];
		components[137] = subComponents[137];
		components[138] = subComponents[138];
		components[139] = subComponents[139];
		components[140] = subComponents[140];
		components[141] = subComponents[141];
		components[142] = subComponents[142];
		components[143] = subComponents[143];
		components[144] = subComponents[144];
		components[145] = subComponents[145];
		components[146] = subComponents[146];
		components[147] = subComponents[147];
		components[148] = subComponents[148];
		components[149] = subComponents[149];
		components[150] = subComponents[150];
		components[151] = subComponents[151];
		components[152] = subComponents[152];
		components[153] = subComponents[153];
		components[154] = subComponents[154];
		components[155] = subComponents[155];
		components[156] = subComponents[156];
		components[157] = subComponents[157];
		components[158] = subComponents[158];
		components[159] = subComponents[159];
		components[160] = subComponents[160];
		components[161] = subComponents[161];
		components[162] = subComponents[162];
		components[163] = subComponents[163];
		components[164] = subComponents[164];
		components[165] = subComponents[165];
		components[166] = subComponents[166];
		components[167] = subComponents[167];
		components[168] = subComponents[168];
		components[169] = subComponents[169];
		components[170] = subComponents[170];
		components[171] = subComponents[171];
		components[172] = subComponents[172];
		components[173] = subComponents[173];
		components[174] = subComponents[176];
		components[175] = subComponents[177];
		components[176] = subComponents[178];
		components[177] = subComponents[179];
		components[178] = subComponents[180];
		components[179] = subComponents[181];
		components[180] = subComponents[182];
		components[181] = subComponents[183];
		components[182] = subComponents[184];
		components[183] = subComponents[185];
		components[184] = subComponents[186];
		components[185] = subComponents[187];
		components[186] = subComponents[188];
		components[187] = subComponents[189];
		components[188] = subComponents[190];
		components[189] = subComponents[191];
		components[190] = subComponents[192];
		components[191] = subComponents[193];
		components[192] = subComponents[194];
		components[193] = subComponents[195];
		components[194] = subComponents[196];
		components[195] = subComponents[197];
		components[196] = subComponents[198];
		components[197] = subComponents[199];
		components[198] = subComponents[200];
		components[199] = subComponents[201];
		components[200] = subComponents[202];
		components[201] = subComponents[203];
		components[202] = subComponents[204];
		components[203] = subComponents[205];
		components[204] = subComponents[206];
		components[205] = subComponents[207];
		components[206] = subComponents[208];
		components[207] = subComponents[209];
		components[210] = subComponents[210];
		components[213] = subComponents[211];
		components[208] = null;
		components[209] = null;
		components[211] = null;
		components[212] = null;
		components[214] = null;
		components[215] = null;
		components[216] = null;
		components[217] = null;
		components[218] = null;
		components[219] = null;
		components[220] = null;
		components[221] = null;
		components[222] = null;
		components[223] = null;
		components[224] = null;
		components[225] = null;
		components[226] = null;
		components[227] = null;
		components[228] = null;
		components[229] = null;
		components[230] = null;
		components[231] = null;
		components[232] = null;
		components[233] = null;
		components[234] = null;
		components[235] = null;
		components[236] = null;
		components[237] = null;
		components[238] = null;
		components[239] = null;
		components[240] = null;
		components[241] = null;
		components[242] = null;
		components[243] = null;
		components[244] = null;
		components[245] = null;
		components[246] = null;
		components[247] = null;
		components[248] = null;
		components[249] = null;
		components[250] = null;
		components[251] = null;
		components[252] = null;
		components[253] = null;
		components[254] = null;
		components[255] = null;
		components[256] = null;
		components[257] = null;
		components[258] = null;
		components[259] = null;
		components[260] = null;
		components[261] = null;
		components[262] = null;
		components[263] = null;
		components[264] = null;
		components[265] = null;
		components[266] = null;
		components[267] = null;
		components[268] = null;
		components[269] = null;
		components[270] = null;
		components[271] = null;
		components[272] = null;
		components[273] = null;
		components[274] = null;
		components[275] = null;
		components[276] = null;
		components[277] = null;
		components[278] = null;
		components[279] = null;
		components[280] = null;
		components[281] = null;
		components[282] = null;
		components[283] = null;
		components[284] = null;
		components[285] = null;
		components[286] = null;
		components[287] = null;
		components[288] = null;
		components[289] = null;
		components[290] = null;
		components[291] = null;
		components[292] = null;
	}
	
	/* -----------------------------------------------------------------
	 * 이후 버전으로 매핑 components:구버전, subComponents:신버전
	 * 구버전 메시지-->신버전 파서(하위호환)
	 * -----------------------------------------------------------------
	 */
	public static void forward(Structure[][] components, Structure[][] subComponents, String originalVersion, String setVersion) throws Exception{ 
		subComponents[0] = components[0];
		subComponents[1] = components[0];
		subComponents[2] = components[2];
		subComponents[3] = components[2];
		subComponents[4] = components[4];
		subComponents[5] = components[5];
		subComponents[6] = components[6];
		subComponents[7] = components[7];
		subComponents[8] = components[8];
		subComponents[9] = components[9];
		subComponents[10] = components[10];
		subComponents[11] = components[11];
		subComponents[12] = components[12];
		subComponents[13] = components[13];
		subComponents[14] = components[14];
		subComponents[15] = components[15];
		subComponents[16] = components[16];
		subComponents[17] = components[17];
		subComponents[18] = components[18];
		subComponents[19] = components[19];
		subComponents[20] = components[20];
		subComponents[21] = components[21];
		subComponents[22] = components[22];
		subComponents[23] = components[23];
		subComponents[24] = components[24];
		subComponents[25] = components[25];
		subComponents[26] = components[26];
		subComponents[27] = components[27];
		subComponents[28] = components[28];
		subComponents[29] = components[29];
		subComponents[30] = components[30];
		subComponents[31] = components[31];
		subComponents[32] = components[32];
		subComponents[33] = components[33];
		subComponents[34] = components[34];
		subComponents[35] = components[35];
		subComponents[36] = components[36];
		subComponents[37] = components[37];
		subComponents[38] = components[38];
		subComponents[39] = components[39];
		subComponents[40] = components[40];
		subComponents[41] = components[41];
		subComponents[42] = components[42];
		subComponents[43] = components[43];
		subComponents[44] = components[44];
		subComponents[45] = components[45];
		subComponents[46] = components[46];
		subComponents[47] = components[47];
		subComponents[48] = components[48];
		subComponents[49] = components[49];
		subComponents[50] = components[50];
		subComponents[51] = components[51];
		subComponents[52] = components[52];
		subComponents[53] = components[53];
		subComponents[54] = components[54];
		subComponents[55] = components[55];
		subComponents[56] = components[56];
		subComponents[57] = components[57];
		subComponents[58] = components[58];
		subComponents[59] = components[59];
		subComponents[60] = components[60];
		subComponents[61] = components[61];
		subComponents[62] = components[62];
		subComponents[63] = components[63];
		subComponents[64] = components[64];
		subComponents[65] = components[65];
		subComponents[66] = components[66];
		subComponents[67] = components[67];
		subComponents[68] = components[68];
		subComponents[69] = components[69];
		subComponents[70] = components[70];
		subComponents[71] = components[71];
		subComponents[72] = components[72];
		subComponents[73] = components[73];
		subComponents[74] = components[74];
		subComponents[75] = components[75];
		subComponents[76] = components[76];
		subComponents[77] = components[77];
		subComponents[78] = components[78];
		subComponents[79] = components[79];
		subComponents[80] = components[80];
		subComponents[81] = components[81];
		subComponents[82] = components[82];
		subComponents[83] = components[83];
		subComponents[84] = components[84];
		subComponents[85] = components[85];
		subComponents[86] = components[86];
		subComponents[87] = components[87];
		subComponents[88] = components[88];
		subComponents[89] = components[89];
		subComponents[90] = components[90];
		subComponents[91] = components[91];
		subComponents[92] = components[92];
		subComponents[93] = components[93];
		subComponents[94] = components[94];
		subComponents[95] = components[95];
		subComponents[96] = components[96];
		subComponents[97] = components[97];
		subComponents[98] = components[98];
		subComponents[99] = components[99];
		subComponents[100] = components[100];
		subComponents[101] = components[101];
		subComponents[102] = components[102];
		subComponents[103] = components[103];
		subComponents[104] = components[104];
		subComponents[105] = components[105];
		subComponents[106] = components[106];
		subComponents[107] = components[107];
		subComponents[108] = components[108];
		subComponents[109] = components[109];
		subComponents[110] = components[110];
		subComponents[111] = components[111];
		subComponents[112] = components[112];
		subComponents[113] = components[113];
		subComponents[114] = components[114];
		subComponents[115] = components[115];
		subComponents[116] = components[116];
		subComponents[117] = components[119];
		subComponents[118] = components[120];
		subComponents[119] = components[121];
		subComponents[120] = components[122];
		subComponents[121] = components[123];
		subComponents[122] = components[124];
		subComponents[123] = components[125];
		subComponents[124] = components[126];
		subComponents[125] = components[127];
		subComponents[126] = components[128];
		subComponents[127] = components[129];
		subComponents[128] = components[130];
		subComponents[129] = components[131];
		subComponents[130] = components[132];
		subComponents[131] = components[133];
		subComponents[132] = components[134];
		subComponents[133] = components[135];
		subComponents[134] = components[136];
		subComponents[135] = components[137];
		subComponents[136] = components[138];
		subComponents[137] = components[139];
		subComponents[138] = components[148];
		subComponents[141] = components[148];
		subComponents[144] = components[148];
		subComponents[147] = components[148];
		subComponents[150] = components[148];
		subComponents[153] = components[148];
		subComponents[156] = components[148];
		subComponents[159] = components[148];
		subComponents[162] = components[148];
		subComponents[165] = components[148];
		subComponents[168] = components[148];
		subComponents[171] = components[148];
		subComponents[174] = components[148];
		subComponents[177] = components[148];
		subComponents[180] = components[148];
		subComponents[183] = components[148];
		subComponents[186] = components[148];
		subComponents[189] = components[148];
		subComponents[192] = components[148];
		subComponents[195] = components[148];
		subComponents[198] = components[148];
		subComponents[201] = components[148];
		subComponents[204] = components[148];
		subComponents[207] = components[148];
		subComponents[210] = components[148];
		subComponents[213] = components[148];
		subComponents[218] = components[148];
		subComponents[221] = components[148];
		subComponents[224] = components[148];
		subComponents[227] = components[148];
		subComponents[230] = components[148];
		subComponents[233] = components[148];
		subComponents[236] = components[148];
		subComponents[239] = components[148];
		subComponents[242] = components[148];
		subComponents[245] = components[148];
		subComponents[248] = components[148];
		subComponents[251] = components[148];
		subComponents[254] = components[148];
		subComponents[257] = components[148];
		subComponents[260] = components[148];
		subComponents[263] = components[148];
		subComponents[266] = components[148];
		subComponents[269] = components[148];
		subComponents[272] = components[148];
		subComponents[275] = components[148];
		subComponents[278] = components[148];
		subComponents[281] = components[148];
		subComponents[284] = components[148];
		subComponents[287] = components[148];
		subComponents[290] = components[148];
		subComponents[291] = components[148];
		subComponents[292] = components[148];
		subComponents[139] = null;
		subComponents[140] = null;
		subComponents[142] = null;
		subComponents[143] = null;
		subComponents[145] = null;
		subComponents[146] = null;
		subComponents[148] = null;
		subComponents[149] = null;
		subComponents[151] = null;
		subComponents[152] = null;
		subComponents[154] = null;
		subComponents[155] = null;
		subComponents[157] = null;
		subComponents[158] = null;
		subComponents[160] = null;
		subComponents[161] = null;
		subComponents[163] = null;
		subComponents[164] = null;
		subComponents[166] = null;
		subComponents[167] = null;
		subComponents[169] = null;
		subComponents[170] = null;
		subComponents[172] = null;
		subComponents[173] = null;
		subComponents[175] = null;
		subComponents[176] = null;
		subComponents[178] = null;
		subComponents[179] = null;
		subComponents[181] = null;
		subComponents[182] = null;
		subComponents[184] = null;
		subComponents[185] = null;
		subComponents[187] = null;
		subComponents[188] = null;
		subComponents[190] = null;
		subComponents[191] = null;
		subComponents[193] = null;
		subComponents[194] = null;
		subComponents[196] = null;
		subComponents[197] = null;
		subComponents[199] = null;
		subComponents[200] = null;
		subComponents[202] = null;
		subComponents[203] = null;
		subComponents[205] = null;
		subComponents[206] = null;
		subComponents[208] = null;
		subComponents[209] = null;
		subComponents[211] = null;
		subComponents[212] = null;
		subComponents[214] = null;
		subComponents[215] = null;
		subComponents[216] = null;
		subComponents[217] = null;
		subComponents[219] = null;
		subComponents[220] = null;
		subComponents[222] = null;
		subComponents[223] = null;
		subComponents[225] = null;
		subComponents[226] = null;
		subComponents[228] = null;
		subComponents[229] = null;
		subComponents[231] = null;
		subComponents[232] = null;
		subComponents[234] = null;
		subComponents[235] = null;
		subComponents[237] = null;
		subComponents[238] = null;
		subComponents[240] = null;
		subComponents[241] = null;
		subComponents[243] = null;
		subComponents[244] = null;
		subComponents[246] = null;
		subComponents[247] = null;
		subComponents[249] = null;
		subComponents[250] = null;
		subComponents[252] = null;
		subComponents[253] = null;
		subComponents[255] = null;
		subComponents[256] = null;
		subComponents[258] = null;
		subComponents[259] = null;
		subComponents[261] = null;
		subComponents[262] = null;
		subComponents[264] = null;
		subComponents[265] = null;
		subComponents[267] = null;
		subComponents[268] = null;
		subComponents[270] = null;
		subComponents[271] = null;
		subComponents[273] = null;
		subComponents[274] = null;
		subComponents[276] = null;
		subComponents[277] = null;
		subComponents[279] = null;
		subComponents[280] = null;
		subComponents[282] = null;
		subComponents[283] = null;
		subComponents[285] = null;
		subComponents[286] = null;
		subComponents[288] = null;
		subComponents[289] = null;
	}
	
	
	public String encode() throws Exception{
		seekOriginalVersion = true;	//가장 마지막 메소드에서 위치찾기 옵션 설정
		return encode(null);
	}
	
	public String encode(Structure[][] subComponents) throws Exception{
		if(seekOriginalVersion&&MessageStructure.getVersionCode(originalVersion)<MessageStructure.getVersionCode(VERSION)){ //실제 버전의 위치 찾기
			//실제 버전이 현재 위치가 아닐 때
			//실제 버전 위치 찾아가기
			return super.encode(null);
			
		}else{//실제 버전의 위치 찾기
			seekOriginalVersion = false;
			//실제 버전이 현재 위치일 때
			if(setVersion.equals(VERSION)){ //설정 버전의 위치 찾기
				//설정 버전이 현재 위치일 때
				String message = this.makeMessage(components, VERSION);
				return message;
				
			}else{ //설정 버전의 위치 찾기
				//설정 버전이 현재 위치가 아닐 때
				if(MessageStructure.getVersionCode(setVersion)<MessageStructure.getVersionCode(VERSION)){ //버전으로 이동 방향 찾기
					//설정 버전이 현재 버전보다 낮을 때 (backward)
					//if(MessageStructure.getVersionCode(originalVersion)>=MessageStructure.getVersionCode(VERSION)){
						hl7.model.V2_2.message.ACK type = (hl7.model.V2_2.message.ACK)this;
						type.backward(type.components, components, originalVersion, setVersion);
					//}
					//설정 버전의 위치로 찾아가기
					return super.encode(components);
					
				}else{ //버전으로 이동 방향 찾기
					/*-------------------------------------------------------------
					 *설정 버전이 현재 버전보다 높을 때(forward)
					 *이후 버전으로 Casting 후 forward 호출
					 *마지막 버전은 생략 
					 *-----------------------------------------------------------------
					 */
					encodeVersion = VERSION;
					return this.encodeForward(encodeVersion, setVersion);
				}

			}
			
		}
	}

	public String encodeForward(String encodeVersion, String setVersion) throws Exception{
		//하위 버전으로 인코딩 시 해당 위치를 찾아 가도록 (메소드 오버라이딩 때문에 처음부터 다시 찾아가야 함)
		if(encodeVersion.equals(VERSION)){
			hl7.model.V2_31.message.ACK type = (hl7.model.V2_31.message.ACK)this;
			type.forward(this.components, type.components, originalVersion, setVersion);
			encodeVersion = type.VERSION;
			if(encodeVersion.equals(setVersion)) return type.makeMessage(type.components, encodeVersion);
			else return encodeForward(encodeVersion, setVersion);
		}else{
			return super.encodeForward(encodeVersion, setVersion);
		}
	}
	
	public String makeMessage(Structure[][] components, String version) throws Exception{
		if(VERSION.equals(version)){
			setCharacter(components, version);
			String message = "";
			char separator = MessageStructure.SEGMENT_TERMINATOR;
			for(int i=0; i<SIZE; i++){
				if(components[i]==null) continue;
				for(int j=0; j<components[i].length; j++){
					if(!repeatable[i]&&j>0) continue;
					String segment = components[i][j].encode();
					if(segment!=null){
						if(message.length()>0) message += separator;
						message += segment;
					}
				}

			}
			return (message.length()==0)?null:message;
		}else{
			return super.makeMessage(components, version);
		}
	}
}
