package hl7.model.V2_2.table;

import hl7.bean.table.Table;

public class Table0171 extends Table{
	private static final String VERSION = "2.2";
	public static Table getInstance(){
		if(table==null) new Table0171();
		return table;
	}

	public static final String _1 = "_1";
	public static final String _10 = "_10";
	public static final String _11 = "_11";
	public static final String _12 = "_12";
	public static final String _2 = "_2";
	public static final String _3 = "_3";
	public static final String _4 = "_4";
	public static final String _5 = "_5";
	public static final String _6 = "_6";
	public static final String _7 = "_7";
	public static final String _8 = "_8";
	public static final String _9 = "_9";
	public static final String A = "A";
	public static final String ADN = "ADN";
	public static final String AFG = "AFG";
	public static final String AGO = "AGO";
	public static final String AL = "AL";
	public static final String AND = "AND";
	public static final String ANT = "ANT";
	public static final String AUS = "AUS";
	public static final String B = "B";
	public static final String BD = "BD";
	public static final String BDS = "BDS";
	public static final String BG = "BG";
	public static final String BH = "BH";
	public static final String BHT = "BHT";
	public static final String BIO = "BIO";
	public static final String BOL = "BOL";
	public static final String BOS = "BOS";
	public static final String BR = "BR";
	public static final String BRN = "BRN";
	public static final String BRU = "BRU";
	public static final String BS = "BS";
	public static final String BUR = "BUR";
	public static final String BY = "BY";
	public static final String C = "C";
	public static final String CAM = "CAM";
	public static final String CDN = "CDN";
	public static final String CH = "CH";
	public static final String CHD = "CHD";
	public static final String CI = "CI";
	public static final String CL = "CL";
	public static final String CO = "CO";
	public static final String CR = "CR";
	public static final String CV = "CV";
	public static final String CY = "CY";
	public static final String CZ = "CZ";
	public static final String D = "D";
	public static final String DCM = "DCM";
	public static final String DK = "DK";
	public static final String DY = "DY";
	public static final String DZ = "DZ";
	public static final String E = "E";
	public static final String EAK = "EAK";
	public static final String EAT = "EAT";
	public static final String EAU = "EAU";
	public static final String EAZ = "EAZ";
	public static final String EC = "EC";
	public static final String ES = "ES";
	public static final String ET = "ET";
	public static final String ETH = "ETH";
	public static final String EW = "EW";
	public static final String F = "F";
	public static final String FAL = "FAL";
	public static final String FJL = "FJL";
	public static final String FL = "FL";
	public static final String FR = "FR";
	public static final String FRJ = "FRJ";
	public static final String FSM = "FSM";
	public static final String GAB = "GAB";
	public static final String GB = "GB";
	public static final String GBA = "GBA";
	public static final String GBG = "GBG";
	public static final String GBJ = "GBJ";
	public static final String GBM = "GBM";
	public static final String GBZ = "GBZ";
	public static final String GCA = "GCA";
	public static final String GEO = "GEO";
	public static final String GH = "GH";
	public static final String GR = "GR";
	public static final String GUY = "GUY";
	public static final String H = "H";
	public static final String HCA = "HCA";
	public static final String HK = "HK";
	public static final String HR = "HR";
	public static final String HV = "HV";
	public static final String I = "I";
	public static final String IL = "IL";
	public static final String IND = "IND";
	public static final String IR = "IR";
	public static final String IRL = "IRL";
	public static final String IRQ = "IRQ";
	public static final String IS = "IS";
	public static final String J = "J";
	public static final String JA = "JA";
	public static final String JOR = "JOR";
	public static final String K = "K";
	public static final String KAS = "KAS";
	public static final String KIS = "KIS";
	public static final String KWT = "KWT";
	public static final String L = "L";
	public static final String LAO = "LAO";
	public static final String LAR = "LAR";
	public static final String LB = "LB";
	public static final String LS = "LS";
	public static final String LT = "LT";
	public static final String LV = "LV";
	public static final String M = "M";
	public static final String MA = "MA";
	public static final String MAK = "MAK";
	public static final String MAL = "MAL";
	public static final String MAO = "MAO";
	public static final String MC = "MC";
	public static final String MEX = "MEX";
	public static final String MOL = "MOL";
	public static final String MOZ = "MOZ";
	public static final String MS = "MS";
	public static final String MW = "MW";
	public static final String N = "N";
	public static final String NA = "NA";
	public static final String NAU = "NAU";
	public static final String NEP = "NEP";
	public static final String NIC = "NIC";
	public static final String NL = "NL";
	public static final String NZ = "NZ";
	public static final String P = "P";
	public static final String PA = "PA";
	public static final String PAK = "PAK";
	public static final String PE = "PE";
	public static final String PL = "PL";
	public static final String PNG = "PNG";
	public static final String PY = "PY";
	public static final String QAT = "QAT";
	public static final String RA = "RA";
	public static final String RB = "RB";
	public static final String RC = "RC";
	public static final String RCA = "RCA";
	public static final String RCB = "RCB";
	public static final String RCH = "RCH";
	public static final String RG = "RG";
	public static final String RH = "RH";
	public static final String RI = "RI";
	public static final String RIM = "RIM";
	public static final String RL = "RL";
	public static final String RM = "RM";
	public static final String RMM = "RMM";
	public static final String RN = "RN";
	public static final String RO = "RO";
	public static final String ROK = "ROK";
	public static final String ROU = "ROU";
	public static final String RP = "RP";
	public static final String RSM = "RSM";
	public static final String RU = "RU";
	public static final String RUS = "RUS";
	public static final String RWA = "RWA";
	public static final String S = "S";
	public static final String SAU = "SAU";
	public static final String SCN = "SCN";
	public static final String SD = "SD";
	public static final String SF = "SF";
	public static final String SGP = "SGP";
	public static final String SK = "SK";
	public static final String SLO = "SLO";
	public static final String SME = "SME";
	public static final String SN = "SN";
	public static final String SOL = "SOL";
	public static final String SP = "SP";
	public static final String STP = "STP";
	public static final String SUD = "SUD";
	public static final String SWA = "SWA";
	public static final String SY = "SY";
	public static final String SYR = "SYR";
	public static final String T = "T";
	public static final String TAD = "TAD";
	public static final String TG = "TG";
	public static final String TJ = "TJ";
	public static final String TMN = "TMN";
	public static final String TN = "TN";
	public static final String TR = "TR";
	public static final String TT = "TT";
	public static final String UA = "UA";
	public static final String UAE = "UAE";
	public static final String USA = "USA";
	public static final String USB = "USB";
	public static final String V = "V";
	public static final String VN = "VN";
	public static final String WAG = "WAG";
	public static final String WAL = "WAL";
	public static final String WAN = "WAN";
	public static final String WD = "WD";
	public static final String WG = "WG";
	public static final String WL = "WL";
	public static final String WS = "WS";
	public static final String WV = "WV";
	public static final String YV = "YV";
	public static final String Z = "Z";
	public static final String ZA = "ZA";
	public static final String ZRE = "ZRE";
	public static final String ZW = "ZW";

	private Table0171(){
		setTableName("Country Code");
		setOID("2.16.840.1.113883.12.171");

		putMap("_1", "Mongolia");
		putMap("_10", "Comoros");
		putMap("_11", "Equatorial Guinea");
		putMap("_12", "Marshall Islands");
		putMap("_2", "Armenia");
		putMap("_3", "Azerbaijan");
		putMap("_4", "Vanuatu");
		putMap("_5", "Guinea-Bissau");
		putMap("_6", "Tuvalu");
		putMap("_7", "Kiribati");
		putMap("_8", "Tonga");
		putMap("_9", "Djibouti");
		putMap("A", "Austria");
		putMap("ADN", "Yemen");
		putMap("AFG", "Afghanistan");
		putMap("AGO", "Angola");
		putMap("AL", "Albania");
		putMap("AND", "Andorra");
		putMap("ANT", "Antigua and Barbuda");
		putMap("AUS", "Australia");
		putMap("B", "Belgium");
		putMap("BD", "Bangladesh");
		putMap("BDS", "Barbados");
		putMap("BG", "Bulgaria");
		putMap("BH", "Belize");
		putMap("BHT", "Bhutan");
		putMap("BIO", "Maldives");
		putMap("BOL", "Bolivia");
		putMap("BOS", "Bosnia and Herzegovina");
		putMap("BR", "Brazil");
		putMap("BRN", "Bahrain");
		putMap("BRU", "Brunei");
		putMap("BS", "Bahamas");
		putMap("BUR", "Myanmar");
		putMap("BY", "Belarus");
		putMap("C", "Cuba");
		putMap("CAM", "Cameroon");
		putMap("CDN", "Canada");
		putMap("CH", "Switzerland");
		putMap("CHD", "Chad");
		putMap("CI", "Ivory Coast");
		putMap("CL", "Sri Lanka");
		putMap("CO", "Colombia");
		putMap("CR", "Costa Rica");
		putMap("CV", "Cape Verde");
		putMap("CY", "Cyprus");
		putMap("CZ", "Czech Republic");
		putMap("D", "Germany");
		putMap("DCM", "Dominican Republic");
		putMap("DK", "Denmark");
		putMap("DY", "Benin");
		putMap("DZ", "Algeria");
		putMap("E", "Spain");
		putMap("EAK", "Kenya");
		putMap("EAT", "Tanzania");
		putMap("EAU", "Uganda");
		putMap("EAZ", "Zanzibar");
		putMap("EC", "Ecuador");
		putMap("ES", "El Salvador");
		putMap("ET", "Egypt");
		putMap("ETH", "Ethiopia");
		putMap("EW", "Estonia");
		putMap("F", "France");
		putMap("FAL", "Falkland Islands");
		putMap("FJL", "Fiji");
		putMap("FL", "Liechtenstein");
		putMap("FR", "Faeroe Islands");
		putMap("FRJ", "Yugoslavia");
		putMap("FSM", "Micronesia");
		putMap("GAB", "Gabon");
		putMap("GB", "United Kingdom");
		putMap("GBA", "Channel Islands - Alderney");
		putMap("GBG", "Channel Islands - Guernsey");
		putMap("GBJ", "Channel Islands - Jersey");
		putMap("GBM", "Isle of Man");
		putMap("GBZ", "Gibraltar");
		putMap("GCA", "Guatemala");
		putMap("GEO", "Georgia");
		putMap("GH", "Ghana");
		putMap("GR", "Greece");
		putMap("GUY", "Guyana");
		putMap("H", "Hungary");
		putMap("HCA", "Honduras");
		putMap("HK", "Hongkong");
		putMap("HR", "Croatia");
		putMap("HV", "Burkina Faso");
		putMap("I", "Italy");
		putMap("IL", "Israel");
		putMap("IND", "India");
		putMap("IR", "Iran");
		putMap("IRL", "Ireland");
		putMap("IRQ", "Iraq");
		putMap("IS", "Iceland");
		putMap("J", "Japan");
		putMap("JA", "Jamaica");
		putMap("JOR", "Jordan");
		putMap("K", "Cambodia");
		putMap("KAS", "Kazakhstan");
		putMap("KIS", "Kyrgyzstan");
		putMap("KWT", "Kuwait");
		putMap("L", "Luxembourg");
		putMap("LAO", "Laos");
		putMap("LAR", "Libya");
		putMap("LB", "Liberia");
		putMap("LS", "Lesotho");
		putMap("LT", "Lithuania");
		putMap("LV", "Latvia");
		putMap("M", "Malta");
		putMap("MA", "Morocco");
		putMap("MAK", "Macedonia");
		putMap("MAL", "Malaysia");
		putMap("MAO", "Oman");
		putMap("MC", "Monaco");
		putMap("MEX", "Mexico");
		putMap("MOL", "Moldova");
		putMap("MOZ", "Mozambique");
		putMap("MS", "Mauritius");
		putMap("MW", "Malawi");
		putMap("N", "Norway");
		putMap("NA", "Netherlands Antilles");
		putMap("NAU", "Nauru");
		putMap("NEP", "Nepal");
		putMap("NIC", "Nicaragua");
		putMap("NL", "Netherlands");
		putMap("NZ", "New Zealand");
		putMap("P", "Portugal");
		putMap("PA", "Panama");
		putMap("PAK", "Pakistan");
		putMap("PE", "Peru");
		putMap("PL", "Poland");
		putMap("PNG", "Papua New Guinea");
		putMap("PY", "Paraguay");
		putMap("QAT", "Qatar");
		putMap("RA", "Argentina");
		putMap("RB", "Botswana");
		putMap("RC", "Taiwan");
		putMap("RCA", "Central African Republic");
		putMap("RCB", "Congo");
		putMap("RCH", "Chile");
		putMap("RG", "Guinea");
		putMap("RH", "Haiti");
		putMap("RI", "Indonesia");
		putMap("RIM", "Mauritania");
		putMap("RL", "Lebanon");
		putMap("RM", "Madagascar");
		putMap("RMM", "Mali");
		putMap("RN", "Niger");
		putMap("RO", "Romania");
		putMap("ROK", "Korea");
		putMap("ROU", "Uruguay");
		putMap("RP", "Philippines");
		putMap("RSM", "San Marino");
		putMap("RU", "Burundi");
		putMap("RUS", "Russia");
		putMap("RWA", "Rwanda");
		putMap("S", "Sweden");
		putMap("SAU", "Saudi Arabia");
		putMap("SCN", "St. Kitts and Nevis");
		putMap("SD", "Swaziland");
		putMap("SF", "Finland");
		putMap("SGP", "Singapore");
		putMap("SK", "Slovakia");
		putMap("SLO", "Slovenia");
		putMap("SME", "Suriname");
		putMap("SN", "Senegal");
		putMap("SOL", "Solomon Islands");
		putMap("SP", "Somalia");
		putMap("STP", "Sao Tome and Principe");
		putMap("SUD", "Sudan");
		putMap("SWA", "Namibia");
		putMap("SY", "Seychelles");
		putMap("SYR", "Syria");
		putMap("T", "Thailand");
		putMap("TAD", "Tajikistan");
		putMap("TG", "Togo");
		putMap("TJ", "China");
		putMap("TMN", "Turkmenistan");
		putMap("TN", "Tunisia");
		putMap("TR", "Turkey");
		putMap("TT", "Trinidad and Tobago");
		putMap("UA", "Ukraine");
		putMap("UAE", "United Arab Emirates");
		putMap("USA", "United States of America");
		putMap("USB", "Uzbekistan");
		putMap("V", "Vatican City State");
		putMap("VN", "Vietnam");
		putMap("WAG", "Gambia");
		putMap("WAL", "Sierra Leone");
		putMap("WAN", "Nigeria");
		putMap("WD", "Dominica");
		putMap("WG", "Grenada");
		putMap("WL", "St. Lucia");
		putMap("WS", "Western Samoa");
		putMap("WV", "St. Vincent and the Grenadines");
		putMap("YV", "Venezuela");
		putMap("Z", "Zambia");
		putMap("ZA", "South Africa");
		putMap("ZRE", "Zaire");
		putMap("ZW", "Zimbabwe");

	}

}
