package hl7.model.V2_31.table;

import hl7.bean.table.Table;

public class Table0292 extends Table{
	private static final String VERSION = "2.3.1";
	public static Table getInstance(){
		if(table==null) new Table0292();
		return table;
	}

	public static final String _01 = "01";
	public static final String _02 = "02";
	public static final String _03 = "03";
	public static final String _04 = "04";
	public static final String _05 = "05";
	public static final String _06 = "06";
	public static final String _07 = "07";
	public static final String _08 = "08";
	public static final String _09 = "09";
	public static final String _10 = "10";
	public static final String _11 = "11";
	public static final String _12 = "12";
	public static final String _13 = "13";
	public static final String _14 = "14";
	public static final String _15 = "15";
	public static final String _16 = "16";
	public static final String _17 = "17";
	public static final String _18 = "18";
	public static final String _19 = "19";
	public static final String _20 = "20";
	public static final String _21 = "21";
	public static final String _22 = "22";
	public static final String _23 = "23";
	public static final String _24 = "24";
	public static final String _25 = "25";
	public static final String _26 = "26";
	public static final String _27 = "27";
	public static final String _28 = "28";
	public static final String _29 = "29";
	public static final String _30 = "30";
	public static final String _31 = "31";
	public static final String _32 = "32";
	public static final String _33 = "33";
	public static final String _34 = "34";
	public static final String _35 = "35";
	public static final String _36 = "36";
	public static final String _37 = "37";
	public static final String _38 = "38";
	public static final String _39 = "39";
	public static final String _40 = "40";
	public static final String _41 = "41";
	public static final String _42 = "42";
	public static final String _43 = "43";
	public static final String _44 = "44";
	public static final String _45 = "45";
	public static final String _46 = "46";
	public static final String _47 = "47";
	public static final String _48 = "48";
	public static final String _49 = "49";
	public static final String _50 = "50";
	public static final String _51 = "51";
	public static final String _52 = "52";
	public static final String _53 = "53";
	public static final String _54 = "54";
	public static final String _55 = "55";
	public static final String _56 = "56";
	public static final String _57 = "57";
	public static final String _58 = "58";
	public static final String _59 = "59";
	public static final String _60 = "60";
	public static final String _61 = "61";
	public static final String _62 = "62";
	public static final String _63 = "63";
	public static final String _64 = "64";
	public static final String _65 = "65";
	public static final String _66 = "66";
	public static final String _67 = "67";
	public static final String _68 = "68";
	public static final String _69 = "69";
	public static final String _70 = "70";
	public static final String _71 = "71";
	public static final String _72 = "72";
	public static final String _73 = "73";
	public static final String _74 = "74";
	public static final String _75 = "75";
	public static final String _76 = "76";
	public static final String _77 = "77";
	public static final String _78 = "78";
	public static final String _79 = "79";
	public static final String _80 = "80";
	public static final String _81 = "81";
	public static final String _82 = "82";
	public static final String _83 = "83";
	public static final String _84 = "84";
	public static final String _85 = "85";
	public static final String _86 = "86";
	public static final String _87 = "87";
	public static final String _88 = "88";
	public static final String _89 = "89";
	public static final String _90 = "90";
	public static final String _91 = "91";
	public static final String _92 = "92";

	private Table0292(){
		setTableName("Vaccines administered (code = CVX)(parenteral, unless oral is noted)");
		setOID("2.16.840.1.113883.12.292");

		putMap("01", "DTP");
		putMap("02", "OPV");
		putMap("03", "MMR");
		putMap("04", "M/R");
		putMap("05", "Measles");
		putMap("06", "Rubella");
		putMap("07", "Mumps");
		putMap("08", "Hep B, adolescent or pediatric");
		putMap("09", "Td (Adult)");
		putMap("10", "IPV");
		putMap("11", "Pertussis");
		putMap("12", "Diphtheria antitoxin");
		putMap("13", "TIG");
		putMap("14", "IG, NOS");
		putMap("15", "Influenza?split (incl. purified surface antigen)");
		putMap("16", "Influenza?whole");
		putMap("17", "Hib,  NOS");
		putMap("18", "Rabies, intramuscular injection");
		putMap("19", "BCG");
		putMap("20", "DTaP");
		putMap("21", "Varicella");
		putMap("22", "DTP-Hib");
		putMap("23", "Plague");
		putMap("24", "Anthrax");
		putMap("25", "Typhoid?oral");
		putMap("26", "Cholera");
		putMap("27", "Botulinum antitoxin");
		putMap("28", "DT(pediatric)");
		putMap("29", "CMVIG");
		putMap("30", "HBIG");
		putMap("31", "Hep A, pediatric, NOS");
		putMap("32", "Meningococcal");
		putMap("33", "Pneumococcal");
		putMap("34", "RIG");
		putMap("35", "Tetanus toxoid");
		putMap("36", "VZIG");
		putMap("37", "Yellow fever");
		putMap("38", "Rubella/Mumps");
		putMap("39", "Japanese encephalitis");
		putMap("40", "Rabies, intradermal injection");
		putMap("41", "Typhoid?parenteral");
		putMap("42", "Hep B, adolescent/high risk infant");
		putMap("43", "Hep B, adult");
		putMap("44", "Hep B, dialysis");
		putMap("45", "Hep B,  NOS");
		putMap("46", "Hib (PRP-D)");
		putMap("47", "Hib (HbOC)");
		putMap("48", "Hib (PRP-T)");
		putMap("49", "Hib (PRP-OMP)");
		putMap("50", "DtaP-Hib");
		putMap("51", "Hib-Hep B");
		putMap("52", "Hep A - adult");
		putMap("53", "Typhoid, parenteral, AKD (U.S. military)");
		putMap("54", "Adenovirus, type 4");
		putMap("55", "Adenovirus, type 7");
		putMap("56", "Dengue fever");
		putMap("57", "Hantavirus");
		putMap("58", "Hep C");
		putMap("59", "Hep E");
		putMap("60", "Herpes simplex 2");
		putMap("61", "HIV");
		putMap("62", "HPV");
		putMap("63", "Junin virus");
		putMap("64", "Leishmaniasis");
		putMap("65", "Leprosy");
		putMap("66", "Lyme disease");
		putMap("67", "Malaria");
		putMap("68", "Melanoma");
		putMap("69", "Parainfluenza-3");
		putMap("70", "Q fever");
		putMap("71", "RSV-IGIV");
		putMap("72", "Rheumatic fever");
		putMap("73", "Rift Valley fever");
		putMap("74", "Rotavirus");
		putMap("75", "Smallpox");
		putMap("76", "Staphylococcus bacterio lysate");
		putMap("77", "Tick-borne encephalitis");
		putMap("78", "Tularemia vaccine");
		putMap("79", "Vaccinia immune globulin");
		putMap("80", "VEE, live");
		putMap("81", "VEE, inactivated");
		putMap("82", "Adenovirus, NOS");
		putMap("83", "Hep A, ped/adol, 2 dose");
		putMap("84", "Hep A, ped/adol, 3 dose");
		putMap("85", "Hep A, NOS");
		putMap("86", "IG");
		putMap("87", "IGIV");
		putMap("88", "Influenza, NOS");
		putMap("89", "Polio, NOS");
		putMap("90", "Rabies, NOS");
		putMap("91", "Typhoid, NOS");
		putMap("92", "VEE, NOS");

	}

}
