package hl7.model.V2_6.table;

import hl7.bean.table.Table;

public class Table0535 extends Table{
	private static final String VERSION = "2.6";
	public static Table getInstance(){
		if(table==null) new Table0535();
		return table;
	}

	public static final String C = "C";
	public static final String M = "M";
	public static final String P = "P";
	public static final String S = "S";

	private Table0535(){
		setTableName("Signature Code");
		setOID("2.16.840.1.113883.12.535");

		putMap("C", "Signed CMS-1500 claim form on file, e.g., authorization for release of any medical or other information necessary to process this claim and assignment of benefits.");
		putMap("M", "Signed authorization for assignment of benefits on file.");
		putMap("P", "Signature generated by provider because the patient was not physically present for services.");
		putMap("S", "Signed authorization for release of any medical or other information necessary to process this claim on file.");

	}

}
