package hl7.model.V2_6.table;

import hl7.bean.table.Table;

public class Table0070 extends Table{
	private static final String VERSION = "2.6";
	public static Table getInstance(){
		if(table==null) new Table0070();
		return table;
	}

	public static final String ABS = "ABS";
	public static final String AMN = "AMN";
	public static final String ASP = "ASP";
	public static final String BBL = "BBL";
	public static final String BDY = "BDY";
	public static final String BIFL = "BIFL";
	public static final String BLD = "BLD";
	public static final String BLDA = "BLDA";
	public static final String BLDC = "BLDC";
	public static final String BLDCO = "BLDCO";
	public static final String BLDV = "BLDV";
	public static final String BON = "BON";
	public static final String BPH = "BPH";
	public static final String BPU = "BPU";
	public static final String BRN = "BRN";
	public static final String BRO = "BRO";
	public static final String BRTH = "BRTH";
	public static final String CALC = "CALC";
	public static final String CDM = "CDM";
	public static final String CNJT = "CNJT";
	public static final String CNL = "CNL";
	public static final String COL = "COL";
	public static final String CSF = "CSF";
	public static final String CTP = "CTP";
	public static final String CUR = "CUR";
	public static final String CVM = "CVM";
	public static final String CVX = "CVX";
	public static final String CYST = "CYST";
	public static final String DIAF = "DIAF";
	public static final String DOSE = "DOSE";
	public static final String DRN = "DRN";
	public static final String DUFL = "DUFL";
	public static final String EAR = "EAR";
	public static final String EARW = "EARW";
	public static final String ELT = "ELT";
	public static final String ENDC = "ENDC";
	public static final String ENDM = "ENDM";
	public static final String EOS = "EOS";
	public static final String EXG = "EXG";
	public static final String EYE = "EYE";
	public static final String FIB = "FIB";
	public static final String FIST = "FIST";
	public static final String FLT = "FLT";
	public static final String FLU = "FLU";
	public static final String GAS = "GAS";
	public static final String GAST = "GAST";
	public static final String GEN = "GEN";
	public static final String GENC = "GENC";
	public static final String GENL = "GENL";
	public static final String GENV = "GENV";
	public static final String HAR = "HAR";
	public static final String IHG = "IHG";
	public static final String ISLT = "ISLT";
	public static final String IT = "IT";
	public static final String LAM = "LAM";
	public static final String LIQ = "LIQ";
	public static final String LN = "LN";
	public static final String LNA = "LNA";
	public static final String LNV = "LNV";
	public static final String LYM = "LYM";
	public static final String MAC = "MAC";
	public static final String MAR = "MAR";
	public static final String MBLD = "MBLD";
	public static final String MEC = "MEC";
	public static final String MILK = "MILK";
	public static final String MLK = "MLK";
	public static final String NAIL = "NAIL";
	public static final String NOS = "NOS";
	public static final String ORH = "ORH";
	public static final String PAFL = "PAFL";
	public static final String PAT = "PAT";
	public static final String PLAS = "PLAS";
	public static final String PLB = "PLB";
	public static final String PLC = "PLC";
	public static final String PLR = "PLR";
	public static final String PMN = "PMN";
	public static final String PPP = "PPP";
	public static final String PRP = "PRP";
	public static final String PRT = "PRT";
	public static final String PUS = "PUS";
	public static final String RBC = "RBC";
	public static final String RT = "RT";
	public static final String SAL = "SAL";
	public static final String SER = "SER";
	public static final String SKM = "SKM";
	public static final String SKN = "SKN";
	public static final String SMN = "SMN";
	public static final String SNV = "SNV";
	public static final String SPRM = "SPRM";
	public static final String SPT = "SPT";
	public static final String SPTC = "SPTC";
	public static final String SPTT = "SPTT";
	public static final String STL = "STL";
	public static final String STON = "STON";
	public static final String SWT = "SWT";
	public static final String TEAR = "TEAR";
	public static final String THRB = "THRB";
	public static final String THRT = "THRT";
	public static final String TISG = "TISG";
	public static final String TISPL = "TISPL";
	public static final String TISS = "TISS";
	public static final String TISU = "TISU";
	public static final String TLGI = "TLGI";
	public static final String TLNG = "TLNG";
	public static final String TSMI = "TSMI";
	public static final String TUB = "TUB";
	public static final String ULC = "ULC";
	public static final String UMB = "UMB";
	public static final String UMED = "UMED";
	public static final String UR = "UR";
	public static final String URC = "URC";
	public static final String URNS = "URNS";
	public static final String URT = "URT";
	public static final String URTH = "URTH";
	public static final String USUB = "USUB";
	public static final String VITF = "VITF";
	public static final String VOM = "VOM";
	public static final String WAT = "WAT";
	public static final String WBC = "WBC";
	public static final String WICK = "WICK";
	public static final String WND = "WND";
	public static final String WNDA = "WNDA";
	public static final String WNDD = "WNDD";
	public static final String WNDE = "WNDE";
	public static final String XXX = "XXX";

	private Table0070(){
		setTableName("Specimen Source Codes");
		setOID("2.16.840.1.113883.12.70");

		putMap("ABS", "Abscess");
		putMap("AMN", "Amniotic fluid");
		putMap("ASP", "Aspirate");
		putMap("BBL", "Blood bag");
		putMap("BDY", "Whole body");
		putMap("BIFL", "Bile fluid");
		putMap("BLD", "Whole blood");
		putMap("BLDA", "Blood  arterial");
		putMap("BLDC", "Blood  capillary");
		putMap("BLDCO", "Cord blood");
		putMap("BLDV", "Blood  venous");
		putMap("BON", "Bone");
		putMap("BPH", "Basophils");
		putMap("BPU", "Blood product unit");
		putMap("BRN", "Burn");
		putMap("BRO", "Bronchial");
		putMap("BRTH", "Breath (use EXHLD)");
		putMap("CALC", "Calculus (=Stone)");
		putMap("CDM", "Cardiac muscle");
		putMap("CNJT", "Conjunctiva");
		putMap("CNL", "Cannula");
		putMap("COL", "Colostrum");
		putMap("CSF", "Cerebral spinal fluid");
		putMap("CTP", "Catheter tip");
		putMap("CUR", "Curettage");
		putMap("CVM", "Cervical mucus");
		putMap("CVX", "Cervix");
		putMap("CYST", "Cyst");
		putMap("DIAF", "Dialysis fluid");
		putMap("DOSE", "Dose med or substance");
		putMap("DRN", "Drain");
		putMap("DUFL", "Duodenal fluid");
		putMap("EAR", "Ear");
		putMap("EARW", "Ear wax (cerumen)");
		putMap("ELT", "Electrode");
		putMap("ENDC", "Endocardium");
		putMap("ENDM", "Endometrium");
		putMap("EOS", "Eosinophils");
		putMap("EXG", "Exhaled gas (=breath)");
		putMap("EYE", "Eye");
		putMap("FIB", "Fibroblasts");
		putMap("FIST", "Fistula");
		putMap("FLT", "Filter");
		putMap("FLU", "Body fluid, unsp");
		putMap("GAS", "Gas");
		putMap("GAST", "Gastric fluid/contents");
		putMap("GEN", "Genital");
		putMap("GENC", "Genital cervix");
		putMap("GENL", "Genital lochia");
		putMap("GENV", "Genital vaginal");
		putMap("HAR", "Hair");
		putMap("IHG", "Inhaled Gas");
		putMap("ISLT", "Isolate");
		putMap("IT", "Intubation tube");
		putMap("LAM", "Lamella");
		putMap("LIQ", "Liquid NOS");
		putMap("LN", "Line");
		putMap("LNA", "Line arterial");
		putMap("LNV", "Line venous");
		putMap("LYM", "Lymphocytes");
		putMap("MAC", "Macrophages");
		putMap("MAR", "Marrow");
		putMap("MBLD", "Menstrual blood");
		putMap("MEC", "Meconium");
		putMap("MILK", "Breast milk");
		putMap("MLK", "Milk");
		putMap("NAIL", "Nail");
		putMap("NOS", "Nose (nasal passage)");
		putMap("ORH", "Other");
		putMap("PAFL", "Pancreatic fluid");
		putMap("PAT", "Patient");
		putMap("PLAS", "Plasma");
		putMap("PLB", "Plasma bag");
		putMap("PLC", "Placenta");
		putMap("PLR", "Pleural fluid (thoracentesis fld)");
		putMap("PMN", "Polymorphonuclear neutrophils");
		putMap("PPP", "Platelet poor plasma");
		putMap("PRP", "Platelet rich plasma");
		putMap("PRT", "Peritoneal fluid /ascites");
		putMap("PUS", "Pus");
		putMap("RBC", "Erythrocytes");
		putMap("RT", "Route of medicine");
		putMap("SAL", "Saliva");
		putMap("SER", "Serum");
		putMap("SKM", "Skeletal muscle");
		putMap("SKN", "Skin");
		putMap("SMN", "Seminal fluid");
		putMap("SNV", "Synovial fluid (Joint fluid)");
		putMap("SPRM", "Spermatozoa");
		putMap("SPT", "Sputum");
		putMap("SPTC", "Sputum - coughed");
		putMap("SPTT", "Sputum - tracheal aspirate");
		putMap("STL", "Stool = Fecal");
		putMap("STON", "Stone (use CALC)");
		putMap("SWT", "Sweat");
		putMap("TEAR", "Tears");
		putMap("THRB", "Thrombocyte (platelet)");
		putMap("THRT", "Throat");
		putMap("TISG", "Tissue gall bladder");
		putMap("TISPL", "Tissue placenta");
		putMap("TISS", "Tissue");
		putMap("TISU", "Tissue ulcer");
		putMap("TLGI", "Tissue large intestine");
		putMap("TLNG", "Tissue lung");
		putMap("TSMI", "Tissue small intestine");
		putMap("TUB", "Tube NOS");
		putMap("ULC", "Ulcer");
		putMap("UMB", "Umbilical blood");
		putMap("UMED", "Unknown medicine");
		putMap("UR", "Urine");
		putMap("URC", "Urine clean catch");
		putMap("URNS", "Urine sediment");
		putMap("URT", "Urine catheter");
		putMap("URTH", "Urethra");
		putMap("USUB", "Unknown substance");
		putMap("VITF", "Vitreous Fluid");
		putMap("VOM", "Vomitus");
		putMap("WAT", "Water");
		putMap("WBC", "Leukocytes");
		putMap("WICK", "Wick");
		putMap("WND", "Wound");
		putMap("WNDA", "Wound abscess");
		putMap("WNDD", "Wound drainage");
		putMap("WNDE", "Wound exudate");
		putMap("XXX", "To be specified in another part of the message");

	}

}
