package hl7.model.V2_4.table;

import hl7.bean.table.Table;

public class Table0290 extends Table{
	private static final String VERSION = "2.4";
	public static Table getInstance(){
		if(table==null) new Table0290();
		return table;
	}

	public static final String PAD = "(pad)";
	public static final String _0 = "0";
	public static final String _1 = "1";
	public static final String _10 = "10";
	public static final String _11 = "11";
	public static final String _12 = "12";
	public static final String _13 = "13";
	public static final String _14 = "14";
	public static final String _15 = "15";
	public static final String _16 = "16";
	public static final String _17 = "17";
	public static final String _18 = "18";
	public static final String _19 = "19";
	public static final String _2 = "2";
	public static final String _20 = "20";
	public static final String _21 = "21";
	public static final String _22 = "22";
	public static final String _23 = "23";
	public static final String _24 = "24";
	public static final String _25 = "25";
	public static final String _26 = "26";
	public static final String _27 = "27";
	public static final String _28 = "28";
	public static final String _29 = "29";
	public static final String _3 = "3";
	public static final String _30 = "30";
	public static final String _31 = "31";
	public static final String _32 = "32";
	public static final String _33 = "33";
	public static final String _34 = "34";
	public static final String _35 = "35";
	public static final String _36 = "36";
	public static final String _37 = "37";
	public static final String _38 = "38";
	public static final String _39 = "39";
	public static final String _4 = "4";
	public static final String _40 = "40";
	public static final String _41 = "41";
	public static final String _42 = "42";
	public static final String _43 = "43";
	public static final String _44 = "44";
	public static final String _45 = "45";
	public static final String _46 = "46";
	public static final String _47 = "47";
	public static final String _48 = "48";
	public static final String _49 = "49";
	public static final String _5 = "5";
	public static final String _50 = "50";
	public static final String _51 = "51";
	public static final String _52 = "52";
	public static final String _53 = "53";
	public static final String _54 = "54";
	public static final String _55 = "55";
	public static final String _56 = "56";
	public static final String _57 = "57";
	public static final String _58 = "58";
	public static final String _59 = "59";
	public static final String _6 = "6";
	public static final String _60 = "60";
	public static final String _61 = "61";
	public static final String _62 = "62";
	public static final String _63 = "63";
	public static final String _7 = "7";
	public static final String _8 = "8";
	public static final String _9 = "9";

	private Table0290(){
		setTableName("MIME base64 encoding characters");
		setOID("2.16.840.1.113883.12.290");

		putMap("(pad)", "=");
		putMap("0", "A");
		putMap("1", "B");
		putMap("10", "K");
		putMap("11", "L");
		putMap("12", "M");
		putMap("13", "N");
		putMap("14", "O");
		putMap("15", "P");
		putMap("16", "Q");
		putMap("17", "R");
		putMap("18", "S");
		putMap("19", "T");
		putMap("2", "C");
		putMap("20", "U");
		putMap("21", "V");
		putMap("22", "W");
		putMap("23", "X");
		putMap("24", "Y");
		putMap("25", "Z");
		putMap("26", "a");
		putMap("27", "b");
		putMap("28", "c");
		putMap("29", "d");
		putMap("3", "D");
		putMap("30", "e");
		putMap("31", "f");
		putMap("32", "g");
		putMap("33", "h");
		putMap("34", "I");
		putMap("35", "j");
		putMap("36", "k");
		putMap("37", "l");
		putMap("38", "m");
		putMap("39", "n");
		putMap("4", "E");
		putMap("40", "o");
		putMap("41", "p");
		putMap("42", "q");
		putMap("43", "r");
		putMap("44", "s");
		putMap("45", "t");
		putMap("46", "u");
		putMap("47", "v");
		putMap("48", "w");
		putMap("49", "x");
		putMap("5", "F");
		putMap("50", "y");
		putMap("51", "z");
		putMap("52", "0");
		putMap("53", "1");
		putMap("54", "2");
		putMap("55", "3");
		putMap("56", "4");
		putMap("57", "5");
		putMap("58", "6");
		putMap("59", "7");
		putMap("6", "G");
		putMap("60", "8");
		putMap("61", "9");
		putMap("62", "+");
		putMap("63", "/");
		putMap("7", "H");
		putMap("8", "I");
		putMap("9", "J");

	}

}
