package hl7.model.V2_3.table;

import hl7.bean.table.Table;

public class Table0003 extends Table{
	private static final String VERSION = "2.3";
	public static Table getInstance(){
		if(table==null) new Table0003();
		return table;
	}

	public static final String A01 = "A01";
	public static final String A02 = "A02";
	public static final String A03 = "A03";
	public static final String A04 = "A04";
	public static final String A05 = "A05";
	public static final String A06 = "A06";
	public static final String A07 = "A07";
	public static final String A08 = "A08";
	public static final String A09 = "A09";
	public static final String A10 = "A10";
	public static final String A11 = "A11";
	public static final String A12 = "A12";
	public static final String A13 = "A13";
	public static final String A14 = "A14";
	public static final String A15 = "A15";
	public static final String A16 = "A16";
	public static final String A17 = "A17";
	public static final String A18 = "A18";
	public static final String A19 = "A19";
	public static final String A20 = "A20";
	public static final String A21 = "A21";
	public static final String A22 = "A22";
	public static final String A23 = "A23";
	public static final String A24 = "A24";
	public static final String A25 = "A25";
	public static final String A26 = "A26";
	public static final String A27 = "A27";
	public static final String A28 = "A28";
	public static final String A29 = "A29";
	public static final String A30 = "A30";
	public static final String A31 = "A31";
	public static final String A32 = "A32";
	public static final String A33 = "A33";
	public static final String A34 = "A34";
	public static final String A35 = "A35";
	public static final String A36 = "A36";
	public static final String A37 = "A37";
	public static final String A38 = "A38";
	public static final String A39 = "A39";
	public static final String A40 = "A40";
	public static final String A41 = "A41";
	public static final String A42 = "A42";
	public static final String A43 = "A43";
	public static final String A44 = "A44";
	public static final String A45 = "A45";
	public static final String A46 = "A46";
	public static final String A47 = "A47";
	public static final String A48 = "A48";
	public static final String A49 = "A49";
	public static final String A50 = "A50";
	public static final String A51 = "A51";
	public static final String C01 = "C01";
	public static final String C02 = "C02";
	public static final String C03 = "C03";
	public static final String C04 = "C04";
	public static final String C05 = "C05";
	public static final String C06 = "C06";
	public static final String C07 = "C07";
	public static final String C08 = "C08";
	public static final String C09 = "C09";
	public static final String C10 = "C10";
	public static final String C11 = "C11";
	public static final String C12 = "C12";
	public static final String CNQ = "CNQ";
	public static final String I01 = "I01";
	public static final String I02 = "I02";
	public static final String I03 = "I03";
	public static final String I04 = "I04";
	public static final String I05 = "I05";
	public static final String I06 = "I06";
	public static final String I07 = "I07";
	public static final String I08 = "I08";
	public static final String I09 = "I09";
	public static final String I10 = "I10";
	public static final String I11 = "I11";
	public static final String I12 = "I12";
	public static final String I13 = "I13";
	public static final String I14 = "I14";
	public static final String I15 = "I15";
	public static final String M01 = "M01";
	public static final String M02 = "M02";
	public static final String M03 = "M03";
	public static final String M04 = "M04";
	public static final String M05 = "M05";
	public static final String M06 = "M06";
	public static final String M07 = "M07";
	public static final String M08 = "M08";
	public static final String M09 = "M09";
	public static final String M10 = "M10";
	public static final String M11 = "M11";
	public static final String O01 = "O01";
	public static final String O02 = "O02";
	public static final String P01 = "P01";
	public static final String P02 = "P02";
	public static final String P03 = "P03";
	public static final String P04 = "P04";
	public static final String P05 = "P05";
	public static final String P06 = "P06";
	public static final String P07 = "P07";
	public static final String P08 = "P08";
	public static final String P09 = "P09";
	public static final String PC1 = "PC1";
	public static final String PC2 = "PC2";
	public static final String PC3 = "PC3";
	public static final String PC4 = "PC4";
	public static final String PC5 = "PC5";
	public static final String PC6 = "PC6";
	public static final String PC7 = "PC7";
	public static final String PC8 = "PC8";
	public static final String PC9 = "PC9";
	public static final String PCA = "PCA";
	public static final String PCB = "PCB";
	public static final String PCC = "PCC";
	public static final String PCD = "PCD";
	public static final String PCE = "PCE";
	public static final String PCF = "PCF";
	public static final String PCG = "PCG";
	public static final String PCH = "PCH";
	public static final String PCJ = "PCJ";
	public static final String PCK = "PCK";
	public static final String PCL = "PCL";
	public static final String Q01 = "Q01";
	public static final String Q02 = "Q02";
	public static final String Q03 = "Q03";
	public static final String Q05 = "Q05";
	public static final String Q06 = "Q06";
	public static final String R01 = "R01";
	public static final String R02 = "R02";
	public static final String R03 = "R03";
	public static final String R04 = "R04";
	public static final String R05 = "R05";
	public static final String R06 = "R06";
	public static final String RAR = "RAR";
	public static final String RDR = "RDR";
	public static final String RER = "RER";
	public static final String RGR = "RGR";
	public static final String ROR = "ROR";
	public static final String S01 = "S01";
	public static final String S02 = "S02";
	public static final String S03 = "S03";
	public static final String S04 = "S04";
	public static final String S05 = "S05";
	public static final String S06 = "S06";
	public static final String S07 = "S07";
	public static final String S08 = "S08";
	public static final String S09 = "S09";
	public static final String S10 = "S10";
	public static final String S11 = "S11";
	public static final String S12 = "S12";
	public static final String S13 = "S13";
	public static final String S14 = "S14";
	public static final String S15 = "S15";
	public static final String S16 = "S16";
	public static final String S17 = "S17";
	public static final String S18 = "S18";
	public static final String S19 = "S19";
	public static final String S20 = "S20";
	public static final String S21 = "S21";
	public static final String S22 = "S22";
	public static final String S23 = "S23";
	public static final String S24 = "S24";
	public static final String S25 = "S25";
	public static final String S26 = "S26";
	public static final String T01 = "T01";
	public static final String T02 = "T02";
	public static final String T03 = "T03";
	public static final String T04 = "T04";
	public static final String T05 = "T05";
	public static final String T06 = "T06";
	public static final String T07 = "T07";
	public static final String T08 = "T08";
	public static final String T09 = "T09";
	public static final String T10 = "T10";
	public static final String T11 = "T11";
	public static final String T12 = "T12";
	public static final String V01 = "V01";
	public static final String V02 = "V02";
	public static final String V03 = "V03";
	public static final String V04 = "V04";
	public static final String varies = "varies";
	public static final String W01 = "W01";
	public static final String W02 = "W02";
	public static final String X01 = "X01";

	private Table0003(){
		setTableName("Event Type");
		setOID("2.16.840.1.113883.12.3");

		putMap("A01", "ADT/ACK - Admit a patient");
		putMap("A02", "ADT/ACK -  Transfer a patient");
		putMap("A03", "ADT/ACK -  Discharge a patient");
		putMap("A04", "ADT/ACK -  Register a patient");
		putMap("A05", "ADT/ACK -  Preadmit a patient");
		putMap("A06", "ADT/ACK -  Transfer an outpatient to inpatient");
		putMap("A07", "ADT/ACK -  Transfer an inpatient to outpatient");
		putMap("A08", "ADT/ACK -  Update patient information");
		putMap("A09", "ADT/ACK -  Patient departing");
		putMap("A10", "ADT/ACK -  Patient arriving");
		putMap("A11", "ADT/ACK -  Cancel admit");
		putMap("A12", "ADT/ACK -  Cancel transfer");
		putMap("A13", "ADT/ACK -  Cancel discharge");
		putMap("A14", "ADT/ACK -  Pending admit");
		putMap("A15", "ADT/ACK -  Pending transfer");
		putMap("A16", "ADT/ACK -  Pending discharge");
		putMap("A17", "ADT/ACK -  Swap patients");
		putMap("A18", "ADT/ACK -  Merge patient information");
		putMap("A19", "QRY/ACK -  Patient query");
		putMap("A20", "ADT/ACK -  Nursing/Census application updates");
		putMap("A21", "ADT/ACK -  Leave of absence - out (leaving)");
		putMap("A22", "ADT/ACK -  Leave of absence - in (returning)");
		putMap("A23", "ADT/ACK -  Delete a patient record");
		putMap("A24", "ADT/ACK -  Link patient information");
		putMap("A25", "ADT/ACK -  Cancel pending discharge");
		putMap("A26", "ADT/ACK -  Cancel pending transfer");
		putMap("A27", "ADT/ACK -  Cancel pending admit");
		putMap("A28", "ADT/ACK -  Add person information");
		putMap("A29", "ADT/ACK -  Delete person information");
		putMap("A30", "ADT/ACK -  Merge person information");
		putMap("A31", "ADT/ACK -  Update person information");
		putMap("A32", "ADT/ACK -  Cancel patient arriving");
		putMap("A33", "ADT/ACK -  Cancel patient departing");
		putMap("A34", "ADT/ACK -  Merge patient information - patient ID only");
		putMap("A35", "ADT/ACK -  Merge patient information - account number only");
		putMap("A36", "ADT/ACK -  Merge patient information - patient ID and account number");
		putMap("A37", "ADT/ACK -  Unlink patient information");
		putMap("A38", "ADT/ACK - Cancel pre-admit");
		putMap("A39", "ADT/ACK - Merge person - external ID");
		putMap("A40", "ADT/ACK - Merge patient - internal ID");
		putMap("A41", "ADT/ACK - Merge account - patient account number");
		putMap("A42", "ADT/ACK - Merge visit - visit number");
		putMap("A43", "ADT/ACK - Move patient information - internal ID");
		putMap("A44", "ADT/ACK - Move account information - internal ID");
		putMap("A45", "ADT/ACK - Move visit information - visit number");
		putMap("A46", "ADT/ACK - Change external ID");
		putMap("A47", "ADT/ACK - Change internal ID");
		putMap("A48", "ADT/ACK - Change alternate patient ID");
		putMap("A49", "ADT/ACK - Change patient account number");
		putMap("A50", "ADT/ACK - Change visit number");
		putMap("A51", "ADT/ACK - Change alternate visit ID");
		putMap("C01", "SRM - Register a patient on a clinical trial");
		putMap("C02", "SRM - Cancel a patient registration on clinical trial (for clerical mistakes only)");
		putMap("C03", "SRM - Correct/update registration information");
		putMap("C04", "SRM - Patient has gone off a clinical trial");
		putMap("C05", "SRM - Patient enters phase of clinical trial");
		putMap("C06", "SRM - Cancel patient entering a phase (clerical mistake)");
		putMap("C07", "SRM - Correct/update phase information");
		putMap("C08", "SRM - Patient has gone off phase of clinical trial");
		putMap("C09", "CSU - Automated time intervals for reporting, like monthly");
		putMap("C10", "CSU - Patient completes the clinical trial");
		putMap("C11", "CSU - Patient completes a phase of the clinical trial");
		putMap("C12", "CSU - Update/correction of patient order/result information");
		putMap("CNQ", "QRY/EQQ/SPQ/VQQ/RQQ - Cancel query");
		putMap("I01", "RQI/RPI - Request for insurance information");
		putMap("I02", "RQI/RPL - Request/receipt of patient selection display list");
		putMap("I03", "RQI/RPR - Request/receipt of patient selection list");
		putMap("I04", "RQD/RPI - Request for patient demographic data");
		putMap("I05", "RQC/RCI - Request for patient clinical information");
		putMap("I06", "RQC/RCL - Request/receipt of clinical data listing");
		putMap("I07", "PIN/ACK - Unsolicited insurance information");
		putMap("I08", "RQA/RPA - Request for treatment authorization information");
		putMap("I09", "RQA/RPA - Request for modification to an authorization");
		putMap("I10", "RQA/RPA - Request for resubmission of an authorization");
		putMap("I11", "RQA/RPA - Request for cancellation of an authorization");
		putMap("I12", "REF/RRI - Patient referral");
		putMap("I13", "REF/RRI - Modify patient referral");
		putMap("I14", "REF/RRI - Cancel patient referral");
		putMap("I15", "REF/RRI - Request patient referral status");
		putMap("M01", "MFN/MFK - Master file not otherwise specified (for backward compatibility only)");
		putMap("M02", "MFN/MFK - Master file - Staff Practioner");
		putMap("M03", "MFN/MFK - Master file - Test/Observation");
		putMap("M04", "MFD/ACK - Master files delayed application acknowledgement");
		putMap("M05", "MFN/MFK - Patient location master file");
		putMap("M06", "MFN/MFK - Charge description master file");
		putMap("M07", "MFN/MFK - Clinical study without phases but with schedules master file");
		putMap("M08", "MFN/MFK - Test/Observation (Nurmeric) master file");
		putMap("M09", "MFN/MFK - Test/Observation (Categorical) master file");
		putMap("M10", "MFN/MFK - Test/Observation batteries master file");
		putMap("M11", "MFN/MFK - Test/calculated observation master file");
		putMap("O01", "ORM - Order message (also RDE, RDS, RGV, RAS,");
		putMap("O02", "ORR - Order response (also RRE, RRD, RRG, RRA,");
		putMap("P01", "BAR/ACK - Add and update patient account");
		putMap("P02", "BAR/ACK - Purge patient account");
		putMap("P03", "DFT/ACK - Post detail financial transaction");
		putMap("P04", "QRY/DSP - Generate bill and A/R statements");
		putMap("P05", "BAR/ACK - Update account");
		putMap("P06", "BAR/ACK - End account");
		putMap("P07", "PEX - Unsolicited initial individual product experience report");
		putMap("P08", "PEX - Unsolicited update individual product experience report");
		putMap("P09", "SUR - Summary product experience report");
		putMap("PC1", "PPR - PC/Problem Add");
		putMap("PC2", "PPR - PC/Problem Update");
		putMap("PC3", "PPR - PC/Problem Delete");
		putMap("PC4", "PPR - PC/Problem Query");
		putMap("PC5", "PPR - PC/Problem Reponse");
		putMap("PC6", "PGL - PC/Goal Add");
		putMap("PC7", "PGL - PC/Goal Update");
		putMap("PC8", "PGL - PC/Goal Delete");
		putMap("PC9", "PGL - PC/Goal Query");
		putMap("PCA", "PGL - PC/Goal Response");
		putMap("PCB", "PPP - PC/Pathway (Problem Oriented) Add");
		putMap("PCC", "PPP - PC/Pathway (Problem Oriented) Update");
		putMap("PCD", "PPP - PC/Pathway (Problem Oriented) Delete");
		putMap("PCE", "PPP - PC/Pathway (Problem Oriented) Query");
		putMap("PCF", "PPP - PC/Pathway (Problem Oriented) Query Response");
		putMap("PCG", "PPP - PC/Pathway (Goal Oriented) Add");
		putMap("PCH", "PPP - PC/Pathway (Goal Oriented) Update");
		putMap("PCJ", "PPP - PC/Pathway (Goal Oriented) Delete");
		putMap("PCK", "PPP - PC/Pathway (Goal Oriented) Query");
		putMap("PCL", "PPP - PC/Pathway (Goal Oriented) Query Response");
		putMap("Q01", "QRY/DSR - Query sent for immediate response");
		putMap("Q02", "QRY/ACK - Query sent for deferred response");
		putMap("Q03", "DSR/ACK - Deferred response to a query");
		putMap("Q05", "UDM/ACK - Unsolicited display update");
		putMap("Q06", "OSQ/OSR - Query for order status");
		putMap("R01", "ORU/ACK - Unsolicited transmission of an observation");
		putMap("R02", "QRY - Query for results of observation");
		putMap("R03", "Display-oriented results, query/unsol. update (for backward compatibility only)");
		putMap("R04", "ORF - Response to query; transmission of requested observation");
		putMap("R05", "QRY/DSR- query fur display results");
		putMap("R06", "UDM-unsolicited update/display results");
		putMap("RAR", "RAR - Pharmacy administration information query response");
		putMap("RDR", "RDR - Pharmacy dispense information query response");
		putMap("RER", "RER - Pharmacy encoded order information query response");
		putMap("RGR", "RGR - Pharmacy dose information query response");
		putMap("ROR", "ROR - Pharmacy prescription order query response");
		putMap("S01", "SRM/SRR - Request new appointment booking");
		putMap("S02", "SRM/SRR - Request appointment rescheduling");
		putMap("S03", "SRM/SRR - Request appointment modification");
		putMap("S04", "SRM/SRR - Request appointment cancellation");
		putMap("S05", "SRM/SRR - Request appointment discontinuation");
		putMap("S06", "SRM/SRR - Request appointment deletion");
		putMap("S07", "SRM/SRR - Request addition of service/resource on appointment");
		putMap("S08", "SRM/SRR - Request modification of service/resource on appointment");
		putMap("S09", "SRM/SRR - Request cancellation of servic/resource on appointment");
		putMap("S10", "SRM/SRR - Request discontinuation of servic/resource on appointment");
		putMap("S11", "SRM/SRR - Request deletion of servic/resource on appointment");
		putMap("S12", "SIU/ACK - Notification of new appointment booking");
		putMap("S13", "SIU/ACK - Notification of appointment rescheduling");
		putMap("S14", "SIU/ACK - Notification of appointment modification");
		putMap("S15", "SIU/ACK - Notification of appointment cancellation");
		putMap("S16", "SIU/ACK - Notification of appointment discontinuation");
		putMap("S17", "SIU/ACK - Notification of appointmentdeletion");
		putMap("S18", "SIU/ACK - Notification of addition of service/resource on appointment");
		putMap("S19", "SIU/ACK - Notification ofmodification of service/resource on appointment");
		putMap("S20", "SIU/ACK - Notification of cancellation of service/resource on appointment");
		putMap("S21", "SIU/ACK - Notification of discontinuation of service/resource on appointment");
		putMap("S22", "SIU/ACK - Notification of deletion of service/resource on appointment");
		putMap("S23", "SIU/ACK - Notification of blocked schedule time slot(s)");
		putMap("S24", "SIU/ACK - Notification of open (¡°unblocked¡±) schedule time slot(s)");
		putMap("S25", "SQM/SQR - Query schedule information");
		putMap("S26", "notification that patient did not show up for schedule appointment");
		putMap("T01", "MDM/ACK - Original document notification");
		putMap("T02", "MDM/ACK - Original document notification and content");
		putMap("T03", "MDM/ACK - Document status change notification");
		putMap("T04", "MDM/ACK - Document status change notification and content");
		putMap("T05", "MDM/ACK - Document addendum notification");
		putMap("T06", "MDM/ACK - Document addendum notification and content");
		putMap("T07", "MDM/ACK - Document replace notification");
		putMap("T08", "MDM/ACK - Document replace notification and content");
		putMap("T09", "MDM/ACK - Document cancel notification");
		putMap("T10", "MDM/ACK - Document replacement notification and content");
		putMap("T11", "MDM/ACK - Document cancel notification");
		putMap("T12", "QRY/DOC - Document query");
		putMap("V01", "VXQ - Query for vaccination record");
		putMap("V02", "VXX - Response to vaccination query returning multiple PID matches");
		putMap("V03", "VXR - Vaccination record response");
		putMap("V04", "VXU - Unsolicited vaccination record update");
		putMap("varies", "MFQ/MFR - Master files query (use event same as asking for e.g., M05 - location)");
		putMap("W01", "ORU - Waveform result, unsolicited transmission of requested information");
		putMap("W02", "QRF - Waveform result, response to query");
		putMap("X01", "PEX - Product experience");

	}

}
